### ISSUE TITLE
broken links inside lessons

### ISSUE THREAD

**Issue by aschuerch** [carpentries/instructor-training#1007]
(Some of?) the links that link to another lesson do not work, i.e. in https://carpentries.github.io/instructor-training/14-live/index.html the link to error framing strategies links to https://carpentries.github.io/09-mindset/index.html#errors-are-essential-to-learning instead of https://carpentries.github.io/instructor-training/09-mindset/index.html#errors-are-essential-to-learning. I will attempt to create a pull request to fix this

**Comment by maneesha** [comment]
Another broken one - the icebreakers link (https://carpentries.github.io/icebreakers/index.html) from here (https://carpentries.github.io/instructor-training/01-welcome/index.html)

**Comment by maneesha** [comment]
`_config.yml` sets the `training_site` variable to `"https://carpentries.github.io/instructor-training"` but when that's rendered by using `[icebreaker question]({{training_site}}/icebreakers/index.html)` the repo name seems to get stripped.  I don't know why this is happening but can look into this more (although probably not until after I teach IT this week).

**Comment by maneesha** [comment]
Links that are defined using `{{ page.root }}` seem to work.

**Comment by ChristinaLK** [comment]
@fmichonneau said that we shouldn't use `page.root`. :(

**Comment by maneesha** [comment]
Linked PR is: https://github.com/carpentries/instructor-training/pull/1008
