### ISSUE TITLE
WIP drawings for improving concept diagram example from python to git

### ISSUE THREAD

**Issue by Denubis** [carpentries/instructor-training#1014]
@jduckles drew these as potential improvements to the concept map example during today's workshop. (We still need to polish them, but I'm snapping them so we don't lose them)
![IMG_20190717_120227](https://user-images.githubusercontent.com/243503/61342023-14d67e80-a88c-11e9-965c-1066f4fd09d9.jpg)
![IMG_20190717_120239](https://user-images.githubusercontent.com/243503/61342024-14d67e80-a88c-11e9-8f44-f15a412f20dc.jpg)
![IMG_20190717_120303](https://user-images.githubusercontent.com/243503/61342026-156f1500-a88c-11e9-88b0-9c199d2e608a.jpg)
![IMG_20190717_120315](https://user-images.githubusercontent.com/243503/61342028-1607ab80-a88c-11e9-86b2-8768fee15303.jpg)
![IMG_20190717_120413](https://user-images.githubusercontent.com/243503/61342031-16a04200-a88c-11e9-9b96-30b806500f2d.jpg)
![IMG_20190717_120427](https://user-images.githubusercontent.com/243503/61342035-186a0580-a88c-11e9-959c-73f8be9eaf5d.jpg)

**Comment by gcapes** [comment]
I have some very similar images I used in [this lesson](https://gcapes.github.io/swc-pr-tutorial/) - feel free to use them e.g. 
![](https://gcapes.github.io/swc-pr-tutorial/fig/upstream-repo.svg)
