### ISSUE TITLE
Link to demo rubric

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#1020]
In the lesson episode on the [checkout process](https://carpentries.github.io/instructor-training/20-checkout/index.html), in the section "Schedule a Discussion or Demo"  there is a link to the demo rubric.  However this links to the [live coding episode](https://carpentries.github.io/instructor-training/17-performance/index.html).  It should link to the [rubric](https://carpentries.github.io/instructor-training/demos_rubric/) itself.  

I can put in a PR; just making a note for now.

**Comment by raynamharris** [comment]
fixed with #1059
