### ISSUE TITLE
Require attendance info?

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#1021]
In the [How We Operate](https://carpentries.github.io/instructor-training/21-carpentries/index.html) lesson, we tell trainees:

> Carpentry workshops must cover core concepts, have at least one certified instructor, use our pre- and post-workshop surveys and report attendance information.

I believe the requirement for reporting attendance has been lifted by @sheraaronhurt -- can you verify?  Thanks!

**Comment by sheraaronhurt** [comment]
Yes. This is correct.

**Comment by raynamharris** [comment]
I only found one mention of attendance in this episode. Does any other text need to be removed or just that part in the keypoint?

**Comment by sheraaronhurt** [comment]
@raynamharris  just that part in the keypoint. Thanks!

**Comment by karinlag** [comment]
May I ask why this was lifted? Just curious.
