### ISSUE TITLE
Update checkout requirements

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#1024]
Our [checkout instructions](https://carpentries.github.io/instructor-training/checkout/) note:

> Part 1: Submit a Small Contribution to One of Our Lessons

This section goes on to describe how they must contribute to one of our *lessons*:  (emphasis mine)

>   Our **lessons** are maintained and improved by the people who teach them, so this part of the checkout procedure gives you a chance to familiarize yourself with our collaborative curriculum development process.   Trainees must make a contribution to a **lesson’s content**, exercises, or instructor’s guide by doing one of the following:

However as @ErinBecker  [has noted](https://github.com/carpentries/handbook/issues/489#event-2496320899), 

> We actually do accept any issue, comment, or PR to any actively maintained repo in the carpentries org (or swc, dc, or lc orgs) as valid for checkout.  

As we accept contributions to any repo, not just a lesson repo, we should consider updating the checkout instructions updated to reflect this.

**Comment by raynamharris** [comment]
How is this? **Additions or changes shown in bold**.

"Our lessons **and lesson infrastructure** are maintained and improved by the people who **use** them. **With** this part of the checkout procedure, **you will** familiarize yourself with our collaborative curriculum development process. Trainees must make a contribution to **any GitHub repository in The Carpentries organization that is actively maintained and supports a lesson (e.g. [LC Open Refine](https://github.com/LibraryCarpentry/lc-open-refine/), [SWC Unix Shell](http://swcarpentry.github.io/shell-novice/)) or lesson infrastructure (e.g. the [handbook](https://github.com/carpentries/handbook), [workshop template](https://github.com/carpentries/workshop-template)).**"

**Comment by raynamharris** [comment]
cc @ErinBecker @Denubis, how is this ☝️

**Comment by maneesha** [comment]
Checking back in on this @ErinBecker  (also including @karenword )

If we are accepting contributions to *any* Carpentries repo for instructor training checkout (as noted in https://github.com/carpentries/handbook/issues/489) I'd like to be sure that we have instructions in our various repos.  Happy to set up the issue templated text once this is resolved.

**Comment by ErinBecker** [comment]
@maneesha - yes, this is correct. We accept contributions to any of the repos @raynamharris mentioned.

**Comment by maneesha** [comment]
Thanks @ErinBecker 
Does this also include websites for The Carpentries and its lesson programs?

**Comment by ErinBecker** [comment]
Yes

**Comment by ha0ye** [comment]
Piggy-backing on this issue to request that info about the `instructors` mailing list be added to the checkout procedures - https://carpentries.topicbox.com/groups/instructors

**Comment by ErinBecker** [comment]
@maneesha  @karenword - did this ever get updated? Just checking back through my old notifications now and wanted to make sure this one was taken care of.
