### ISSUE TITLE
Too many branches

### ISSUE THREAD

**Issue by dpshelio** [carpentries/instructor-training#1034]
This repository has too many branches (103), many of them without a meaningful name (e.g., `name-patch-5`). 

I would suggest to clean them earlier than later (as later could be even more). This is a task for the people that have written permissions to the repository, as they can't be deleted otherwise.

As a volunteer, one could go and review whether these branches are still important or relevant and suggest a name for them. The "analysis" on each branch can be post it below - as a comment to this issue - mentioning the owner of the branch and suggesting its deletion, a new name for the branch or the creation of a pull-request (the pull-request can be created by anyone though).

Going forward, I would like to suggest that anyone - even these with written access - work their contributions on forks and create PRs when ready. This way the core repository is kept clean and neat :wink:.

**Comment by ErinBecker** [comment]
Thanks for the feedback @dpshelio! I've just gone through and deleted all branches for PRs that have either been merged or closed. There are still 13 left, so I'll leave this issue open for the @carpentries/instructor-training-maintainers to take a look at those remaining branches.

**Comment by raynamharris** [comment]
I closed a few more. @dpshelio let me know if we need to close any stale branches where PRs were never submitted as well.

**Comment by dpshelio** [comment]
This ended under my radar. I believe that most of the [18 stale branches](https://github.com/carpentries/instructor-training/branches/stale) can be removed. At least the ones that don't have any new changes (3), that have already been merged (6) or that its PR has been closed (1) (Note, that GH keep that info as a secret branch if a PR is closed but not been merged). 
There are two branches from @lexnederbragt with the same content that I would agree to have it merged.  One from @sheraaron (@sheraaronhurt is that you?) with a typo fix. And one from @karenword which seems reasonable to have it as a Pull Request.

As a note, there's a setting on the repository, under the main "options" and the "merge button" section, that automates the deletion of branches once they've been merged via a pull-request:
"Automatically delete head branches".

**Comment by lexnederbragt** [comment]
I turned one of my stale branches into a pull request. I somehow am not able to delete the other one...
