### ISSUE TITLE
Instructor Training: Suggested Lessons for Teaching Demonstrations

### ISSUE THREAD

**Issue by masamiy** [carpentries/instructor-training#1039]
"Project Organisation and Management for genomics" (https://datacarpentry.org/organization-genomics/) is marked as "all episodes are good to go" for demonstration under Data Carpentry: Genomics, but there is not much live demo in the content. I feel a bit unfair to other participants. Would it be possible to have a little more specific instruction there if it should stay as a demo topic?

**Comment by ChristinaLK** [comment]
@masamiy that sounds like a good idea.
