### ISSUE TITLE
Demo rubric criterion for learner environment could be clearer

### ISSUE THREAD

**Issue by alex-ball** [carpentries/instructor-training#1043]
I am not sure if this is the right place to raise this issue but I think it is something that we need to discuss.

One of the criteria for [assessing teaching demonstrations](https://github.com/carpentries/instructor-training/blob/gh-pages/_extras/demos_rubric.md) is this:

> Mirrors the learner’s environment (e.g. default terminal setup, simplified prompt)

This is, of course, an important principle when running a workshop and its heart is definitely in the right place. But in its current form it is not well suited for its intended purpose (assessing teaching demonstrations), for three reasons.

The first is that in the context of a demo session, there are no learners as such, only other (trainee) instructors. And the etherpad does not ask candidates to share what their environment is so that the others can try to mirror it. Even if they did, it would rarely be possible to mirror them all since there would typically be a variety.

Presumably what is really meant by this is 'Mirror a typical learner's environment': that is, using a setup as if freshly installed. But in the case of the Unix Shell in particular, this brings us to the metaphorical elephant in the room, which is that _there is no single default terminal setup_. Let me explain.

This is a fresh install of Git Bash on Windows 10:
![git-bash](https://user-images.githubusercontent.com/1890395/64542402-6abf2400-d31b-11e9-9a12-9f31e37d7f25.png)

This is a fresh install of the 'Ubuntu App' on Windows 10 (via WSL), which apart from the font is also what the command line looks like on a fresh installation of Ubuntu Linux:
![wsl-ubuntu](https://user-images.githubusercontent.com/1890395/64542649-dacdaa00-d31b-11e9-9876-f4ed691db519.png)

This is, as I understand it from the family member who supplied the screenshot, what the Terminal on macOS currently looks like by default:
![macos-bash](https://user-images.githubusercontent.com/1890395/64543033-6fd0a300-d31c-11e9-9191-584f77e0b42b.png)

These have elements in common but they are all different. The point here is that, unless a Trainer (or trainee instructor) has actually experienced all these alternatives, they are not in a position to know whether it is a default or not. (At my own demo, I was criticised for using a 'custom setup' when in fact I was using default setup 2 above.)

Which brings us to the third point. I was told what was actually expected was this:
![ideal](https://user-images.githubusercontent.com/1890395/64544280-aa3b3f80-d31e-11e9-842f-b95b73e93bef.png)

This is the "simplified prompt" mentioned in the criterion, but it neither mirrors a typical learner's environment, nor matches any default terminal setup. You actually have to put some effort in to achieve it. Merely (re)moving your `.bashrc` doesn't do it (example from Ubuntu again):
![ubuntu-no-bashrc](https://user-images.githubusercontent.com/1890395/64545092-0c487480-d320-11e9-8199-012940ba4733.png)

So if the criterion really is to use a black-on-white terminal simplified prompt as shown above, as opposed to mirroring a learner's environment by using one of the many default terminal setups, this should be explicit in the rubric, and ideally a `.bashrc` configuration file should be provided for achieving the desired result.

**Comment by raynamharris** [comment]
Thanks @alex-ball. You bring up an excellent point about not having a visual aid to accompany what we mean by "mirror the learners' environment". I wonder if it would make sense to include a single image in the [Live Coding is a Skill](https://carpentries.github.io/instructor-training/14-live/index.html) episode that shows a bad and good example of a terminal

**Comment by ndporter** [comment]
It would still be good to add an image in [Live Coding is a Skill](https://carpentries.github.io/instructor-training/instructor/17-live.html) to more explicitly demonstrate in a way learners can go back to after their training when they're preparing the demo. I'm adding a new issue #1722 specifically for that and closing this with comment.
