### ISSUE TITLE
Key point needs to be updated.

### ISSUE THREAD

**Issue by amyehodge** [carpentries/instructor-training#1044]
The first key point at the end of this episode (https://carpentries.github.io/instructor-training/21-carpentries/index.html) is "The Carpentry materials are all openly licensed, but Software and Data Carpentry names and logos are trademarked." This needs to be updated to include Library Carpentry.

**Comment by raynamharris** [comment]
This has already been mentioned in PR https://github.com/carpentries/instructor-training/pull/1054. The question at hand, I think, is whether the list of trademarked logos should include all the lesson programs AND the Carpentries.

**Comment by karenword** [comment]
This appears to have been addressed. Closing! :)
