### ISSUE TITLE
Inconsistent links to post-instructor survey

### ISSUE THREAD

**Issue by anenadic** [carpentries/instructor-training#1055]
In episode 25 "Wrapping up" the link to workshop survey is: https://www.surveymonkey.com/r/post-instructor-training

On the front page under the "Sample Schedule", under "16:40 post-training survey" the link it https://www.surveymonkey.com/r/instructor_training_post_survey?workshop_id=instructor-training. 

They seem to point to the same survey though with different URLs so this may not be a big deal, but one contains the parameter in the URL which may not be be of use here given that the link is specifically to "post instructor training" survey rather than a general "post any training" survey. The URL parameter is useful from individual instructor training workshop pages though. In any case, maybe we should make these links consistent.

A related issue spotted on the instructor training workshop website template too - where different links to pre- and post-instructor-training survey are used (see https://gcapes.github.io/2019-10-08-ttt-manchester/ for example): 
- pre-workshop survey link is https://www.surveymonkey.com/r/instructor_training_pre_survey?workshop_id=2019-10-08-ttt-manchester and points to the survey in Survey Monkey
- post-workshop link points to the page in instructor training material about surveys https://carpentries.github.io/instructor-training/06-feedback/#surveys where we do not have links to post instructor training surveys at all!
I'll report this issue in the instructor training workshop website template too.

I am happy to fix both issues (ping me in reply to this issue so I do not miss it) - just let me know what exact survey link URLs I should be using and with or without the URL parameter (which makes sense from the individual workshop pages).

**Comment by anenadic** [comment]
I've now reported the related issue in the instructor training workshop website template too, see: https://github.com/carpentries/training-template/issues/47

**Comment by karenword** [comment]
@fmichonneau any comments on what is correct for curriculum links? I expect the answer is different from the workshop website template.

**Comment by Denubis** [comment]
Ping me when there's a template, as I kind of guessed in my exporter.

**Comment by fmichonneau** [comment]
@karenword sorry I'm not sure I understand what you mean. What do you mean by "curriculum links"?

**Comment by karenword** [comment]
Sorry @fmichonneau I wasn't clear! There are links to the surveys in the workshop website templates, which I believe have already been fixed through a separate PR. That leaves, from this issue, the matter of whether the links to the surveys in the Instructor Training curriculum episode 25 and the Sample Schedule are both ok, or if one needs to be changed. I don't know the answer to that question, but I'm guessing that you do!

**Comment by fmichonneau** [comment]
I checked all mentions of the surveys in the repo, and I think everything looks good for now. I'm going to close the issue but if you believe that something is not right, please re-open and point to the problematic links. Thanks!

**Comment by fmichonneau** [comment]
actually, until #1060 is merged the links are wrong.

**Comment by raynamharris** [comment]
https://github.com/carpentries/instructor-training/issues/1060 is now merged. thanks!
