### ISSUE TITLE
Improving the tables in suggested lessons for Instructor training

### ISSUE THREAD

**Issue by gauravdiwan89** [carpentries/instructor-training#1063]
On the suggested lessons page for Instructor training, the tables that indicate good starting points for each lesson are a little misleading. Particularly, the use of "any other episode" in the Good starting points column led me to believe that this lesson has no good starting points. If the 'Avoid' column was before the 'Good starting points' column, then the suggestion would make sense.

May I suggest using "all other episodes" in both columns to improve the clarity of the suggestions?

**Comment by raynamharris** [comment]
Great suggestion @gauravdiwan89. Does this look okay? https://github.com/carpentries/instructor-training/pull/1065

**Comment by gauravdiwan89** [comment]
Thank you @raynamharris . That looks good.
