### ISSUE TITLE
add LC shell episode 6 to "to avoid" in demo table

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/instructor-training#1070]
Per feedback from trainee who is preparing for teaching demo. Could we please add this episode to the "do not use for teaching demos" section of the table? 

______
I am teaching the Library Carpentry classes. In https://carpentries.github.io/instructor-training/demo_lessons/index.html#lc it says that if I choose the lesson on OpenRefine, there is only one episode to prepare for, because the others involve no live coding OR contain dependancies.

If I choose the lesson on the Shell, I should prepare for almost all of the episodes. But actually there are dependancies in that lesson too. For instance in episode https://librarycarpentry.org/lc-shell/06-free-text/index.html you work with a file that has been created before.

**Comment by brownsarahm** [comment]
this is solved
