### ISSUE TITLE
Continuing to use blind spot in lesson 

### ISSUE THREAD

**Issue by sstevens2** [carpentries/instructor-training#1079]
In the Expertise lesson we still refer to the expert awareness gap as blind spot in ~3-4 places later in the lesson.  I’ll make a PR when I can if others agree we should be consistent with its usage.

**Comment by karenword** [comment]
paging @brownsarahm -  anything intentional here?

**Comment by brownsarahm** [comment]
not intentional. Last time I taught I also caught a few more places where it was still blind spot and did a PR on the spot.

**Comment by sstevens2** [comment]
I'll make a PR next week.  It is also in the etherpad template as an exercise name.
