### ISSUE TITLE
hierarchical summary for each sessions we learn.

### ISSUE THREAD

**Issue by gmhhope** [carpentries/instructor-training#1090]
Dear Carpentry colleague,

I think the website of Carpentry is linear and logical. However, they missed certain degree of hierarchy, which help learners to construct a tree of what they learned. I suggest making a mind-map (or any other graphs) for a summary or overview like below. 
<img width="443" alt="Screen Shot 2020-03-09 at 11 04 59 AM" src="https://user-images.githubusercontent.com/12982817/76227529-d2d0c300-61f5-11ea-8c17-3cfd88a5540f.png">

It may help learners to grasp knowledge after all linear elaboration of each session. Many thanks!

Best regards,
Minghao Gong
Carpentry Board member in UF
---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

---

**Comment by karenword** [comment]
This is a good idea for a visual organizer, but implementation for something detailed like this would really need to be done at a structural level to avoid maintenance tangles, and that is currently out of scope for work within this repo. For now, the [Sample Schedule](https://carpentries.github.io/instructor-training/) will have to suffice.
