### ISSUE TITLE
Add information on Carpentries Incubator?

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#1104]
In the [Culture of Contribution section on this page](https://carpentries.github.io/instructor-training/21-carpentries/index.html) we talk about lesson incubation.  This page should refer to the information on our website here: https://carpentries.org/involved-lessons/

**Comment by sstevens2** [comment]
Think this would be a great addition!  I'm wondering if it fits in the lesson program section?

**Comment by brownsarahm** [comment]
@tobyhodges is this something you could work on adding?

**Comment by tobyhodges** [comment]
Absolutely. Please assign the issue to me.
