### ISSUE TITLE
reference ideas from hilary parker in imposter syndrome session

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#1115]
https://medium.com/@hspter/practical-advice-for-imposter-syndrome-120586c30d6b

I think this article highlights another technique for imposter syndrome, which is emotional development and "withdrawing from the battle" so to speak.

**Comment by karenword** [comment]
I recently saw an article, which @kariljordan also brought to my attention, that I think relates to the same problems with framing imposter syndrome. 

https://hbr.org/2021/02/stop-telling-women-they-have-imposter-syndrome

I will aim to address these soon in ongoing updates.

**Comment by ChristinaLK** [comment]
I think the HBR article focuses on the aspect of imposter syndrome that Hilary specifically does not talk about. Both are important in addressing the "why" of imposter syndrome (and strategies for pushback), but I think the Hilary Parker essay makes more subtle points / would require a more nuanced conversation, so if I had to pick one, I would focus on the systemic issues raised in the HBR article.
