### ISSUE TITLE
Demoing Command Line for Genomics without the AMI instance?

### ISSUE THREAD

**Issue by embatty** [carpentries/instructor-training#1121]
[Introduction to the Command Line for Genomics](https://datacarpentry.org/shell-genomics/) is suggested as a suitable teaching demo lesson, and the [setup instructions](https://datacarpentry.org/genomics-workshop/teaching_demos/index.html) tell you to download and unzip some files as setup. However, the [Working with Files and Directories](https://datacarpentry.org/shell-genomics/03-working-with-files/index.html) episode asks you to look for files in `/usr/bin` and to look at file permissions assuming you are the user `dcuser`, which will give different results depending on the instructor's local setup. Should the setup instructions suggest that you use the AMI instance as for later lessons, so that your results will be consistent with the lesson material, or is this fine for the teaching demo?

**Comment by Denubis** [comment]
This feels like a great "teachable moment" for me -- as this can demonstrate if the instructor deals with variation. Since the goal is not to "read the lesson literally" I think this entirely fine. (It may be worth suggesting to the lesson maintainers that their instructions are a tad... specific, or could use a callout box about users).

**Comment by brownsarahm** [comment]
Agree that the difference is acceptable for the teaching demo. The lesson is fine to be specific because it's designed to be taught suing AMI. To make it more clear for future instructor trainees, I've proposed a change to the demo setup instructions.

**Comment by brownsarahm** [comment]
The instructions are changed on the DC-genomics repo, so I'm closing this. Let me know if it needs to be re-opened.
