### ISSUE TITLE
Capitalize Carpentries in venn diagram

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/instructor-training#1124]
Per #1074 

In `fig/carpentries-venn-diagram_20190522.svg` the word "carpentries" located in the center white space of the diagram should be capitalized to be "Carpentries".

**Comment by mikemhenry** [comment]
I can take care of this issue

**Comment by mikemhenry** [comment]
This issue can be closed now :)

**Comment by brownsarahm** [comment]
Closed with #1167

**Comment by brownsarahm** [comment]
Thanks @mikemhenry ... i don't know why the ink didn't work to close it automatically
