### ISSUE TITLE
Teaching demo rubric and 95% pass stat

### ISSUE THREAD

**Issue by arieldeardorff** [carpentries/instructor-training#1133]
I was recently providing feedback to a learner who did not pass their teaching demo and thought that the [demo rubric](https://carpentries.github.io/instructor-training/demos_rubric/) would be a good thing to share. However, I decided not to because the line in the second paragraph about how 95% of people pass. Could we change this to "the majority of people pass" or something like that? I am worried that this will make people feel bad if they are part of the only 5% that don't pass.

It would also be great to add "copying and pasting code from notes" (or something similar) under negative delivery. I think we talk around this but there isn't anything that explicitly says this would be a negative in the demo.

**Comment by brownsarahm** [comment]
I think that these are great changes, can you submit a PR?

**Comment by arieldeardorff** [comment]
Pull request #1134 submitted!
