### ISSUE TITLE
Remove AMY reminder?

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/instructor-training#1148]
Questions that come up about the AMY reminder are generally not things that any trainers can help with, only core team members. Does it make sense to remove that from the curriculum and move it to the reminder e-mail templates (or a workshop followup e-mail?). 

The last time I taught, Sher! did that section, but I answered a lot of questions about this via Zoom chat (with e-mail the core team). Trainees spent about 10 minutes trying this/chatting me instead of paying attention to what followed the reminder. 

Tagging @sheraaronhurt and @maneesha because I think they're the ones who know and then we can implement it in the curriculum.

**Comment by sheraaronhurt** [comment]
We do have a reminder in the email that is sent to them prior to the training. Also if they have not done so, when Talisha does attendance, she will send them a followup email to do so.

**Comment by karenword** [comment]
I actually can't find the content this issue refers to in the curriculum atm. Sorry @brownsarahm can you confirm if this issue has been addressed?

**Comment by brownsarahm** [comment]
it's still currently on [the checkout](https://carpentries.github.io/instructor-training/checkout/) page and the application stuff is [also on the checkout episode](https://carpentries.github.io/instructor-training/20-checkout/index.html)

**Comment by karenword** [comment]
OK -- I think I was thrown by trying to text-search "AMY" -- sounds like the issue here is reminding them to fill out the application. Thanks @brownsarahm! Will clean up accordingly.
