### ISSUE TITLE
 Mnemonics

### ISSUE THREAD

**Issue by RomiZP** [carpentries/instructor-training#1161]
In chapter 05, 'Memory and Cognitive Load' (https://github.com/carpentries/instructor-training/blob/gh-pages/_episodes/05-memory.md), there is a section on 'Strategies For Memory Management'. It would be useful to include a short paragraph here about synesthesia and mnemonics. This is important to highlight techniques that could be used to activate cognitive processes that put the long-term memory into use. This can go in particular between the sections 'Chunking' and 'Active learning through formative assessment',

I would add the following title and paragraph:

Mnemonics

It is interesting to consider synesthesia, the faculty to perceive a stimulus with a different sensory pathway than the expected. For example, seeing colors when listening to music or feeling geometric shapes when smelling certain perfumes. The phenomenon of synesthesia usually happens when two senses mix up, like when using mnemonics. These rules consist in a series of associations that allow us to organize the information for later recovery, involving the arbitrary association of concepts that are not related outside this rule. It is possible to memorize stuff without any sense or logical connection, using an active retrieval to bring it forward from long-term memory. This technique can be useful to memorize some tables, data or information, and could involve either of two techniques, the visual mnemonics (using words) and the verbal mnemonics (with words to memorize).

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

---

**Comment by karenword** [comment]
Thank you @RomiZP ! I often find myself talking about memory management strategies during this section even though this content is not in the curriculum, so I agree that this is a natural addition! I suggest we consider this point during our next curriculum update to be sure we can make room.

**Comment by ChristinaLK** [comment]
I agree with @karenword  - we mention memory management strategies but don't provide a lot of examples so this would be a nice addition.

**Comment by RomiZP** [comment]
Great, thanks for your feedback and I look forward to the community meeting. @karenword @ChristinaLK
