### ISSUE TITLE
Demotivation and Systematic Racism + Sexism

### ISSUE THREAD

**Issue by arieldeardorff** [carpentries/instructor-training#1162]
After teaching the [Motivation and Demotivation](https://carpentries.github.io/instructor-training/08-motivation/index.html) lesson this week it struck me that we don't really discuss the systemic barriers like racism and sexism that impact how learners and instructors might experience our classrooms. We talk about stereotype threat and imposter syndrome which seem to focus more on building up individual learners without really acknowledging that there are real systemic forces and implicit biases that might impact how we teach and how our learners interact with each other. As an example, one of our trainees brought up that as a petite woman she is often talked over in classes even when she is the instructor. This is a huge topic but seems worth addressing either as part of this section or as part of [Managing a Diverse Classroom](https://carpentries.github.io/instructor-training/18-management/index.html. ). Tagging @jt14den in case he wants to add anything.

**Comment by ChristinaLK** [comment]
Thanks @arieldeardorff ! I agree that we could do a much better job of "setting the stage" by talking specifically about systemic racism and sexism and then talk about imposter syndrome etc. in that context.

**Comment by karenword** [comment]
This tweet reminded me of this issue: https://twitter.com/ThesociologistS/status/1375284766656790531

**Comment by Lucy-Quirk** [comment]
I agree, educating educators on systematic barriers and implicit biases is crucial to creating a positive and inclusive teaching environment. I think that the training course does a great job of informing will-be instructors on building up the individual coder; but there is most definitely room for more information about how implicit biases show up in teaching and making aware how systematic barriers affect student's learning. Something I really appreciated about the instructor training was the room for contemplation we were given. I think the trainers model a sort of thoughtfulness to us that helped us become contemplative in the way we will go on to teach. In this way, I think that even a small section on these subjects could make a large impact.

**Comment by brownsarahm** [comment]
@Lucy-Quirk Thanks for this comment! Did you go through training recently? (we just did a major update that partially responds to this issue, so knowing when you did training will help us, as maintainers, put your comment in context)

**Comment by Lucy-Quirk** [comment]
@brownsarahm Hi Sarah! Yes I did and Ariel was actually my trainer! I took the instructor training course November 2021

**Comment by brownsarahm** [comment]
Yes, this issue pre-dates the current episode on EIA.  In summer 2021 you could have had the current version or the version with the issues that prompted this issue. 

I think at this time, I'm going to close this issue because @arieldeardorff's specific concerns are no longer the issue in the curriculum, (in fact she mentions an old episode title and the motivation/demotivation episode was significantly revised).  

The EIA episode can still be improved, but in new ways, I think, however @arieldeardorff you can re-open if you want.
