### ISSUE TITLE
Suggested Lessons for Teaching Demonstrations Missing Library Carpentry: Introduction to Git

### ISSUE THREAD

**Issue by mikemhenry** [carpentries/instructor-training#1174]
We currently don't have any suggested lessons for https://librarycarpentry.org/lc-git/
I had future instructor use [this episode](https://librarycarpentry.org/lc-git/02-getting-started/index.html) and it seemed suitable.

**Comment by karenword** [comment]
Tagging @tobyhodges for Curriculum Team attention :)
