### ISSUE TITLE
Note in demo info that some are "themed"

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/instructor-training#1189]
I learned about this while signing up.  I figure this should be documented in the curriculum at least so that trainers mention it/notice when preparing.

**Comment by ChristinaLK** [comment]
are demos themed, or discussion sessions?

**Comment by brownsarahm** [comment]
The signup now includes 

>Would you like to reserve this time slot for any particular community group? If so please note the group here. Note that this will be recommended on the Etherpad signup, but can not be enforced.

and maneesha confirmed that this is for demos

**Comment by maneesha** [comment]
There might be a better way to phrase this other than "themed."
The intent was to say the session was intended for certain groups.
Some examples:

* some of our Australian Trainers wanted to hold seats for Australian trainees
* demo may be conducted in Spanish

**Comment by ChristinaLK** [comment]
AHA, that makes sense. Got it. Agree w/ Sarah that we could add a note to the curriculum.
