### ISSUE TITLE
homework link to handbook is misleading

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/instructor-training#1204]
the homework page says it's going to the checklist, but it goes to this page: 
https://docs.carpentries.org/topic_folders/hosts_instructors/index.html

instead of the checklist directly: https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html

we should decide where we want to direct people and change the link or change the text.

**Comment by ChristinaLK** [comment]
I think we want the first page (the landing page) so they get an overview, but I'm not sure.

**Comment by karenword** [comment]
I think the handbook page has added some content that bumps the checklists down. However, agree that it's important content. I think it's ok to link to the main page and have them scrolling in confusion for a moment? We could modify the text to make it more clear what it's linking to if learners are confused.
