### ISSUE TITLE
Lesson Contribution: Live Coding Clarification

### ISSUE THREAD

**Issue by Talishask** [carpentries/instructor-training#1212]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

I would like to draw your (Library Carpentries etc.) attention to a formulation which might confuse instructor trainees as to whether you can give lessons in the usage of OpenRefine.

I and several others tried to clarify whether or whether not one could give an instructor demonstration in how to use OpenRefine, because the formulation was not quite clear:

https://carpentries.github.io/instructor-training/demo_lessons/index.html#dc-socialsci
![image](https://user-images.githubusercontent.com/45104071/106809335-8e35ed80-6639-11eb-8724-7a43d4692058.png)

![image](https://user-images.githubusercontent.com/45104071/106809353-92620b00-6639-11eb-8af7-d15f95daeaaf.png)

We asked the LC-community several times whether it would be possible to give an introduction to OpenRefine or aspects of OpenRefine, which was confirmed.

If you look narrowly at the expressions "has no live coding" and "Later episodes have dependencies", you could get the idea that it was out of the question.

But you can give structured Live instructions in how to use OpenRefine and you can introduce people to coding with GREL (Google Refine Expression Language) and (I think) with good results.

So maybe you should write: You can give Live instructions to OpenRefine and/or instructions in coding with GREL.

**Comment by karenword** [comment]
Thank you for this! There are many confusion points with respect to lesson selection but this is one that I think has a straightforward solution in adjusting our language around live coding to be more accommodating of participatory instruction of all of the tasks we teach. We will review this language and look for opportunities to clarify in the updates now in progress.
