### ISSUE TITLE
Reconcile episode titles with episode filenames?

### ISSUE THREAD

**Issue by Denubis** [carpentries/instructor-training#1217]
I'm preparing to split the lesson up into 8 days (https://github.com/Denubis/instructor-training-8-sessions-2021/) and just hit an interesting bit of frustration: the episode filenames have highly variable relation to episode titles. Is it worth reconciling them?

**Comment by Denubis** [comment]
Also https://denubis.github.io/instructor-training-8-sessions-2021/15-lesson-study/index.html as "preparing to teach" isn't titled correctly any more? The topics are more "preparing and organising episodes in a workshop" rather than the pragmatics of "So you're up in front of a bunch of people expecting you to teach them..."

**Comment by brownsarahm** [comment]
This is a good thing to fold into the "big revision" @karenword is working on, (and she has done some already). I think things have evolved over time and I know the IT revision between when I certified as an instructor and as a trainer changed some titles.

**Comment by Denubis** [comment]
I'm also happy to contribute the timings that @dvanic and I took last year online (and the ones that Sara and I will take next month -- though they're not mapped to 2 day in person.
