### ISSUE TITLE
How about adding resources on the proper use of pronouns?

### ISSUE THREAD

**Issue by annefou** [carpentries/instructor-training#1222]
In the first episode "[Welcome](https://carpentries.github.io/instructor-training/01-welcome/index.html)", there is a box "Pronouns and Names" highlighting the importance of using correct names and pronouns to setting a tone of respect. 

I agree but failed to implement it properly. I asked COC and Malvika sent the following resources which I believe would be useful to everyone so I think we could add links in The Carpentries instructor training material:
- The proper use of pronouns in language: [https://lgbt.ucsf.edu/pronounsmatter](https://lgbt.ucsf.edu/pronounsmatter) 
- The importance of using pronouns: [https://www.mypronouns.org/](https://www.mypronouns.org/) 
- How to use personal pronouns: https://www.mypronouns.org/how (as a non-native speaker, I find it important to have examples of usage)
- How to deal with situations when you use the wrong pronoun: https://www.mypronouns.org/mistakes

**Comment by karenword** [comment]
Thank you @annefou ! I will have a look at these resources in the context of the ongoing updates. 

This intersects with a broader concern I am wrestling with at the moment regarding the use of outside links in the curriculum. That is a separate issue, which I may open later today (and will connect here) if I can get the relevant ideas properly articulated. :)

But either way these will be very useful in the current updates! Thank you for sharing!

**Comment by fmichonneau** [comment]
an additional thing that Malvika noted which I believe should also be emphasized in the intro: "the use of pronouns should be completely optional, and we should emphasise that. This is to avoid unintentionally outing anyone who might not be ready for that."
