### ISSUE TITLE
Teaching is a Skill, change order of episode

### ISSUE THREAD

**Issue by tadamus** [carpentries/instructor-training#1238]
When teaching Instructor Training, I found that the learners engaged in the Feedback on Yourself activity with insightful feedback after reviewing the Feedback in Hard lesson section and participating in the Giving Feedback activity. I suggest reordering the lesson as such:

1. Reading it is not enough
2. Feedback is hard
3. Giving Feedback
4. Feedback on yourself
5. Feedback on Feedback 

then continue on as written.

**Comment by sstevens2** [comment]
I usually teach this in that order as well.

**Comment by brownsarahm** [comment]
This was solved in #1215
