### ISSUE TITLE
Changes to rubric  for instructor training applications

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#1242]
From @ErinBecker 

The following bonus points in the [application scoring rubric](https://github.com/carpentries/instructor-training/blob/gh-pages/files/rubric.md) should be removed:

- Library Carpentry
- Social Sciences Data Carpentry lessons
- Geospatial Data Carpentry Lessons

There is a [separate issue in AMY](https://github.com/carpentries/amy/issues/1914) to automatically add bonus points for other  areas of domain expertise.

**Comment by maneesha** [comment]
[This PR](https://github.com/carpentries/instructor-training/pull/1252) removes the bonus points for LC, DC Social Science, and DC geospatial.  

The rubric also includes: 

> Award +1 for being in economics or social sciences, arts, humanities, library science, or chemistry.

Should social science and library science be removed from this, as the corresponding lesson and lesson program are being removed?

Tagging @ErinBecker

**Comment by ErinBecker** [comment]
Yes. I thought these were removed a long time ago. Thanks for catching this. I've updated the PR.
