### ISSUE TITLE
Episode 5 - Clarify examples in section "Guided Practice At Work"

### ISSUE THREAD

**Issue by emcaulay** [carpentries/instructor-training#1254]
Caveat: Sharing my perspective, which may not be shared by the majority of the intended audience for instructor training. If that's the case, then there is no need to make any changes to the lesson.

Context: I vaguely know Python, but it's not one of my main teaching areas in the Carpentries or one of my skill areas in my work or hobby life. 

In the examples in this episode of a "faded example" in the section "Guided Practice At Work", I don't understand the examples myself so I can't extrapolate out to learn the concept of faded example. 

So, specifically, starting at the beginning of the code block: 

> `def total_length(words):`

>    ` """Returns the total length of all words in a list combined.`

What does `"""` mean?

And I'm lost from there. 

I keep pushing to understand this next block, but I'm also still lost. I recognize the for loop and the syntax of the iterator pattern. But I don't see any assignment for the what I assume is the variable `words`. I also don't understand why the `"""` is used again.

> `Example:
>        total_length(["red", "green", "blue"]) => 12
>     """
>     total = 0
>     for word in words:
>         total += len(word)
>     return total`

So, this may be an instance where you need a better learner than me to read this lesson, but I want to learn how to develop faded examples and I feel like I could use more help with these examples. 

By posting this issue I'm hoping to open a discussion, and I am not certain that the lesson needs any edits as a result. I just wanted to see what others thought and provide a perspective from a "pair of fresh eyes."

**Comment by brownsarahm** [comment]
Thanks @emcaulay We've removes thid from the new curriculum, that's in #1215 so I'm going to close this issue.
