### ISSUE TITLE
Note that IT is an eligible repo for checkout contribution

### ISSUE THREAD

**Issue by mbursell** [carpentries/instructor-training#1270]
While working on my own checkout I was reading through[ Instructor Training: Checkout Instructions](https://carpentries.github.io/instructor-training/checkout/#1-lesson-contributions) under the Eligible Repositories section and noticed that Instructor Training materials are not listed anywhere. It was mentioned during training that a few typos were found in the Instructor Training lessons so I thought that it would be a good idea to clarify if those are eligible for contributions for checkout. Or, if they are ineligible, to mention it specifically in that section.

**Comment by brownsarahm** [comment]
Thanks @mbursell! you caught an error in our docs, this repo is eligible, including that very clarification would be a welcome PR.

**Comment by brownsarahm** [comment]
renamed for easier maintaince
