### ISSUE TITLE
Checkout Suggestion on Suggested Lessons Page

### ISSUE THREAD

**Issue by geospatial-gill** [carpentries/instructor-training#1276]
When deciding on a lesson for my upcoming demo, I noticed that there were very few Library Carpentry lessons listed on the [Instructor Training: Suggested Lessons for Teaching Demonstrations](https://carpentries.github.io/instructor-training/demo_lessons/index.html) page.  These lessons in the Extended Library Carpentry Curriculum have a live coding component that might serve well for someone doing their demo:
- Introduction to Python
- Introduction to R
- SQL

**Comment by brownsarahm** [comment]
Thanks for this recommendation, @geospatial-gill. 

 @ErinBecker @tobyhodges Can you help address if this is possible or not?

**Comment by ErinBecker** [comment]
Thanks for this suggestion @geospatial-gill! I agree that adding more options from the Library Carpentry curriculum is a good idea. The Introduction to Python and Introduction to R lessons are still in "alpha" status, which means they're not ready for broad-scale teaching yet. However, the SQL lesson is stable and therefore a good candidate to add to the suggested episodes. 

I recommend the following: 
Good Starting Points
* [Selecting and Sorting Data](https://librarycarpentry.org/lc-sql/02-selecting-sorting-data/index.html)
* [Filtering](https://librarycarpentry.org/lc-sql/03-filtering/index.html)
* [Ordering and Commenting](https://librarycarpentry.org/lc-sql/04-ordering-commenting/index.html)
* [Aggregating and Calculating Values](https://librarycarpentry.org/lc-sql/05-aggregating-calculating/index.html)
* [Joins and aliases](https://librarycarpentry.org/lc-sql/06-joins-aliases/index.html)
* [Saving queries](https://librarycarpentry.org/lc-sql/07-saving-queries/index.html)
* [Creating tables and modifying data](https://librarycarpentry.org/lc-sql/09-create/index.html)

Avoid
* [Database design](https://librarycarpentry.org/lc-sql/08-database-design/index.html)
* [Other database tools](https://librarycarpentry.org/lc-sql/10-other-tools/index.html)
* [Extra-challenges](https://librarycarpentry.org/lc-sql/11-extra-challenges/index.html)
* [Good style](https://librarycarpentry.org/lc-sql/Bonus_GoodStyle/index.html)
