### ISSUE TITLE
Checkout Suggestion on Python Intro for Libraries Lesson: For Loops page

### ISSUE THREAD

**Issue by geospatial-gill** [carpentries/instructor-training#1277]
In the [Python Intro for Libraries Lesson: For Loops](https://librarycarpentry.org/lc-python-intro/12-for-loops/index.html) episode, it might be clearer to new learners if the first 2 blocks of code were reordered.  When I've taught this lesson as a demo, I've done it this way and it seems to go very well.  After the introduction on what a For loop does, show the steps the "long way" first, then demo the more elegant way of using a loop to accomplish the same task:
1. print(2)
print(3)
print(5)
2. This series of print statements is equivalent to a for loop:
for number in [2, 3, 5]:
     print(number)
3. And the output for both is the same:
2
3
5

**Comment by brownsarahm** [comment]
Hi @geospatial-gill this is a great contribution, but the maintainers of that lesson will not see it here? Can you open this issue on that [lesson's repository](https://github.com/LibraryCarpentry/lc-python-intro/issues)?

**Comment by geospatial-gill** [comment]
Ooops!  Yes, I re-submitted under their repository:  https://github.com/LibraryCarpentry/lc-python-intro/issues/92

**Comment by brownsarahm** [comment]
Great, I'm going to close this issue.
