### ISSUE TITLE
Hyperlink to CC-BY 4.0

### ISSUE THREAD

**Issue by c-rod51** [carpentries/instructor-training#1301]
It appears that the CC BY 4.0 link at the bottom-left of every Instructor Training page does not point to the correct link (https://creativecommons.org/licenses/by/4.0/). Instead, it points to the current page. This might be the case because the site is using [The Carpentries style](https://github.com/carpentries/styles/) version [9.5.3](https://github.com/carpentries/styles/releases/tag/v9.5.3).

I noticed the CC BY 4.0 links in other workshops using [The Carpentries Theme](https://github.com/carpentries/carpentries-theme/) were okay.

**Comment by brownsarahm** [comment]
@fmichonneau @zkamvar Can you either point me to directions for how to update the version of styles or submit a PR that does it so we can fix this?

**Comment by fmichonneau** [comment]
I opened #1303 to bring the template up to date with styles.
The issue with the CC-BY link stemmed from the variable for that link missing from the `_config.yml`.

**Comment by brownsarahm** [comment]
Thanks for the context @fmichonneau 

Thanks for bringing this to our attention @c-rod51 it should be fixed now
