### ISSUE TITLE
Change knowledge representation example to match diagram

### ISSUE THREAD

**Issue by fiveop** [carpentries/instructor-training#1317]
In [Expertise and Instruction](https://carpentries.github.io/instructor-training/04-expertise/index.html) the sentence

> jump directly from a problem to its solution because there is a direct link between the two in their mind. Where a competent practitioner would have to reason “A therefore B therefore C therefore D therefore E”, the expert can go from A to E in a single step (“A therefore E”).

matches the diagram above except for there being no direct arrow from A to E for the export. Even though an exact match is not important to get across the point, it tripped me up while reading. It should either match (for example, by extending the example to F) or it should be made clear that one has nothing to do with the other, for example by using different letters (a different alphabet?) in the sentence.

**Comment by brownsarahm** [comment]
Good catch, I've taught this multiple times and not noticed the disparity. 
I think we should extend to F to make it match.
