### ISSUE TITLE
Duplicate row for post-survey in the schedule in index.md

### ISSUE THREAD

**Issue by jevbelikov** [carpentries/instructor-training#1330]
NB: noticed by a trainee at a recent workshop.

  | 16:50 | Post-training survey | Please fill out our post-training survey after the course.
  | 17:05 | Post-training survey | Please ask your Trainer for a custom link to your post-training survey at the end of the course.

**Comment by Parcelli** [comment]
I did notice the same as a trainee. It might be thought that we are required to fill two post-training survey ,the first being the one the link has already been provided and the other one to be provided by the trainer. I do suggest that we have one row for post-survey in the schedule.

**Comment by brownsarahm** [comment]
@karenword can you confirm which of these two lines is the correct instructions?
