### ISSUE TITLE
Pre-Workshop Software Installation Opportunities

### ISSUE THREAD

**Issue by nkshin1** [carpentries/instructor-training#1347]
I think it's a good idea to have 30 minutes before each LC Workshop lesson to have students address their software installation problems before the lesson starts.  I found that people who did not successfully download the software before, dragged the students who did behind schedule.  

Often times, the class would have to wait for 3-5 students to get their software installation done correctly with the help of the instructors or helpers.  If the helpers were assisting, the instructors would wait for the installation of late students to be done before carrying on with the lesson so that the ones struggling with software problems did not fall behind on the lesson at hand.

Having a Pre-workshop Software Installation Opportunity planned into the LC workshop schedule would really help accelerate the LC lessons and how much content is covered.

- Nancy Shin (nkshin1)

**Comment by brownsarahm** [comment]
I edited to unhide the text. 

Thanks @nkshin1 this is a common practice in the carpentries. This advice is already documented on the [instructor checklist in the handbook](https://docs.carpentries.org/topic_folders/hosts_instructors/instructor_tips.html) so I'm going to close this issue.

**Comment by nkshin1** [comment]
Hi Sarah,
  Do I need to keep looking for ways to improve the lessons since mine was
already addressed?  Thanks!!!

Best,

Nancy :)

**Comment by brownsarahm** [comment]
FYI, this is a public comment, not an e-mail. 

It is not required for your contribution to be accepted to count for your contribution
