### ISSUE TITLE
Jargon Busting Lesson ... Shorten it or Get Rid of it

### ISSUE THREAD

**Issue by nkshin1** [carpentries/instructor-training#1348]
UW NNLM R5 recently hosted a LC Workshop and Jargon Busting was part of the lesson plan - I received sooooooooooooo much negative feedback about this part of the lesson.  Many people, to which I agree with, felt like it was an obvious exercise and an useless one - time on other content would have been better spent.  Many people, including myself felt the brainstorming session was futile if you weren't going to learn what you didn't know in this class (and on the brainstorm list) and since this class is limited and structured to teach certain concepts, the brainstorm list proved to be futile if some concepts were not addressed in the current LC workshop.

**Comment by brownsarahm** [comment]
edited to remove `<detail> tag. 

This issue should be opened on the [lc-overview repo](https://github.com/LibraryCarpentry/lc-overview) 

I'm closing because it does not pertain to instructor training.
