### ISSUE TITLE
List missing for Introductions exercise

### ISSUE THREAD

**Issue by jcoliver** [carpentries/instructor-training#1349]
In the "Launches and Landings" episode (23), the first exercise (What is an Introduction?) refers to a list of things to include "below", but there is no list.

> Finally, compare your ideas with the list of topics below. Did you miss anything? Did you come up with something that is not listed below?

Could a bulleted list be added to the exercise - maybe as a solution?

**Comment by brownsarahm** [comment]
below refers to the rest of that section, but yes I think adding it to the exercise would be more complete
