### ISSUE TITLE
Refer to Handbook for AMY instructions

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#1354]
We keep instructions for how Instructors can manage their AMY profile in our [Handbook](https://docs.carpentries.org/topic_folders/for_instructors/current_instructors.html#accessing-and-updating-your-instructor-profile).  This should be considered the canonical source of information on how to use AMY.  The [Tracking your Progress](https://carpentries.github.io/instructor-training/checkout/index.html#4-tracking-your-progress) section of the curriculum should refer to this, and not duplicate any information in the Handbook.

**Comment by calvpang** [comment]
This section needs to mirror the information in the handbook or point towards it as a single source of truth. At the moment, the information is inconsistent with who to email to address login issues for instance.

## Tracking your Progress
If you have any questions or did not provide a GitHub username in your form, please email us at [instructor.training@carpentries.org](mailto:instructor.training@carpentries.org).

## Handbook
If you are unable to login to AMY, please submit your GitHub username to [team@carpentries.org](mailto:team%40carpentries.org) so we can update your access.

**Comment by brownsarahm** [comment]
Thanks @calvpang for the additional details.  This issue is already labeled with `pr-requested` we're just waiting for someone to submit the pull request (actual changes that can be merged; issues are like a flag/ or to-do list item) .  

The best thing to do is to point to the handbook page.
