### ISSUE TITLE
Creating Folder in Starting with data in R

### ISSUE THREAD

**Issue by Loz4** [carpentries/instructor-training#1369]
In "[Starting with data in R](https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html)" lesson the early instructions before the code to `download.file` the lesson states:
"The text after the comma (“data_raw/portal_data_joined.csv”) is the destination of the file on your local machine. You’ll need to have a folder on your machine called “data_raw” where you’ll download the file."

This is vague/out of context without more intro context to using R/RStudio, as you can't just create a folder anywhere on your machine called "data_raw" and have R send the file there via `download.file`. 

Suggest adding instructions to use and script instructing use of `dir.create("folder_name")` to create the folder directory. It is the simplest/quickest way to create a folder so the module works for instructors and students to follow the script.

So suggest addition of something like the following (plus adding `dir.create("data_raw")` to the code line):
"The text after the comma (“data_raw/portal_data_joined.csv”) is the destination of the file on your local machine. You’ll need to have a folder on your machine called “data_raw” where you’ll download the file. The easiest way to create a directory folder in your project is to use `dir.create("folder_name")`"

**Comment by brownsarahm** [comment]
Hi @Loz4 This is a great suggestion, but this is the wrong place for it.  Can you open this issue on the [repository for that curriculum](https://github.com/datacarpentry/R-ecology-lesson) ? 

On that repository you can also see if someone else has suggested fixing that already and join the discussion around it.

**Comment by Loz4** [comment]
@brownsarahm Will do! Thanks for pointing out.
