### ISSUE TITLE
Rewrite temporal references to 4 parts instead of two days

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/instructor-training#1385]
we currently have references to "tomorrow afternoon" and tomorrow morning that could be rephrased to part 3, part 4. This will accommodate longer workshops better.

**Comment by AndrzejRomaniuk** [comment]
I agree, especially tha 8h workshops, even for teaching new instructors, may be too exhausting for many people. 

By the way, is there a possibility to add a possibility to switch in-page between suggested timeframes? e.g. full days, half days or completely unrelated to days.

**Comment by brownsarahm** [comment]
I  plan to remove all reference to "days" in the training in the linked PR.  It would reference part 1, part 2, etc.
