### ISSUE TITLE
Accidental/Intentional coding mistakes as a resource in teaching basic Quality control skills

### ISSUE THREAD

**Issue by AndrzejRomaniuk** [carpentries/instructor-training#1394]
I hope I did it right, it's my first contribution in that form to a repository.
There are a couple of topics similar to mine, though I would like to take a different angle. It is signposted in the instructor course, but I think it could be developed further, even if to be explored as additional materials. Would be thankful for any comments (including if Im doing issues entry right).

Errors in live coding, whether accidental or intentional, are a great method of teaching basic quality control. Given code QA becomes a thing even for non-technical audience (since 2010 I think we all are slowly becoming programmers, without realising it) it would be good to stress its importance during teaching. Instructors need to be shown to use accidental (or intentional) errors/mistakes as a source of information about teaching audience how to perform QA/debugging. Learners should also have this topic signposted very early during coding, to be able to solve very basic issues on their own, not to get demotivated early on and understand, that issues "happen". In the same time, instructors may treat own mistakes as unintended teaching resources, and may be calmer knowing, it is still a contribution to the learning process. 

Personally, during early coding in R, I prefer to showcase the syntax error (usually it performs itself, but if not, I just show how it may happen), as it is most likely the first thing people will encounter. I also teach where to encounter them (misspelled functions, not enough/too many brackets, etc.).

**Comment by brownsarahm** [comment]
Hi @AndrzejRomaniuk this is great advice.  how would you like to see this incorporated in the lesson?

**Comment by AndrzejRomaniuk** [comment]
Thank you for the kind words! And sorry for a really late response....

I have hard time envisioning this as it is already in some form in the lesson. Especially in the 'Motivation and Demotivation' episode, under 'Encourage a Growth Mindset' section, one can see very similar points to mine ('Positive error framing','Presenting the instructor as a learner'). It is detailed, but relatively general in content and delivery. Errors are also briefly mentined in 'Live Coding is a Skill' - especially important was the mention that learners may not know what error messages may mean, but it is a rather brief entry.

As a minimum perhaps an addtional point can be included, for example "Handling Errors in Coding as a Basic Programming Skill", linking what is being said in other points to an actual skill (Quality Control/Assurance, or more common "debugging"), with some practical hints how to introduce it in the teaching (intentionally, or when making error ourselves). Also, in the separate project, Glossary, it would be good to mention the term Debug or Quality Control/Assurance.

**Comment by brownsarahm** [comment]
This is mentioned briefly because we've tried to reduce some of the reliance on programming specific things to be more inclusive to eg the people teaching library carpentry lessons that do not include programming, but this is a good point.  I think this is implied in lots of places it could be more complete.  

If you want to add it to glossario, you should go directly to that repository, different volunteers maintain each separate lesson/subproject.  

To add it here, you could write a callout and submit a pull request or we can leave this open as a discussion.  If you know what you want to see added, but you are not comfortable trying to make a pull request, you can write out the text you'd like in the call out here and we'll tag it for someone else to make the pull request.

**Comment by AndrzejRomaniuk** [comment]
Terribly sorry for yet another late answer.
May practice writing a pull request on Monday, but am still thinking about what I specifically want to write, perhpas:

**Handling errors in coding as a basic programming skill** – _one way of encouraging learners to deal with coding errors that may occur in their own work is to introduce them to the idea of a “bug”. Properly identifying possible “bugs” (errors) in a code and “debugging” them (finding a solution to remove/resolve them) is a unique skill on its own. It is not too distant to what could be considered as “proofreading” of a written text, from finding and hopefully fixing issues as simple as spelling mistakes or character omissions (syntax errors) up to as complex as wrong logical sequences (logical errors) or incorrect calculations (arithmetic errors). However, “debugging” goes a little bit beyond that, as not only a good grasp of specific coding language principles is needed, but also experience in reading the feedback software that executes the code can provide about encountered problems (error messages)._ 

_A few minutes of a lesson can be spent on intentionally making a few basic errors to explain the idea and to familiarise the learners with error messages and how to read them. The simplest and reproducible errors are definitely syntax errors; they are also ones that learners will most likely encounter first and may start to spot on their own. Syntax errors also have relatively well-defined error messages in the majority of interpreting software. However, explaining debugging beyond this point should be done only when opportunities arise. Own coding mistakes and errors made by learners when either copying the instructor or while working on their own should be considered a teaching/learning resource, giving a chance to digress about more specific issues and how to deal with them when writing or reviewing the code._

In terms of a glossary, been looking at it for a while and preparing to write an issue about it on their own page.

**Comment by brownsarahm** [comment]
This is a great start, there is also a longer discussion in #1235 about where to place this sort of point

**Comment by AndrzejRomaniuk** [comment]
Just created a pull request #1412 

Read the discussion, and I guess best would be to add it in the live coding episode. However, it can be divided into separate episodes (motivation + live), with the first paragraph acting as a summary for motivation, and the second, perhaps with elements added from the discussion, in live coding as an example how to include fixing errors.
