### ISSUE TITLE
Improve accessibility of Instructor Training for people with ASD

### ISSUE THREAD

**Issue by sjmf** [carpentries/instructor-training#1395]
This issue regards improving the accessibility of the instructor training for people with autism spectrum disorder and other learning and attention disabilities (e.g. ADHD), in line with the Carpentries Core Value of Access for All. I have a small number of suggestions– not a comprehensive list by any means– of ways in which the accessibility of the content could be improved. These are intended as an __introduction__ to adjustments for the instructor training, and the start of a conversation about inclusion: not a complete guide.

I will post the detail of this issue as individual comments for accessibility purposes: please see below for further information.

Contents:

  0. [Background on Autism Spectrum Disorder](https://github.com/carpentries/instructor-training/issues/1395#issuecomment-1163277702)
  1. [Invite participants to disclose a disability](https://github.com/carpentries/instructor-training/issues/1395#issuecomment-1163277885)
  2. [Clarify the cancellations and attendance policy for disabled participants](https://github.com/carpentries/instructor-training/issues/1395#issuecomment-1163278095)
  3. [Consider mental fatigue when scheduling workshops](https://github.com/carpentries/instructor-training/issues/1395#issuecomment-1163278279)
  4. [Reduce visual noise and task switching](https://github.com/carpentries/instructor-training/issues/1395#issuecomment-1163278573)
  5. [Improve information presentation for working memory](https://github.com/carpentries/instructor-training/issues/1395#issuecomment-1163278798)
  6. [Useful adaptations - things that went well](https://github.com/carpentries/instructor-training/issues/1395#issuecomment-1163278874)

**Comment by sjmf** [comment]
## 1. Invite participants to disclose a disability

We can invite participants to disclose any disabilities which may impair their ability to participate in the training as part of the the sign-up process, or as a part of the welcome email. Inviting participants to declare a disability will help both the individual and the instructors to make adjustments for better inclusion of that person. For example, by adding a line to the training invitation email similar to the following: 

> If you have a disability which might prevent you from being fully included in the instructor training workshops, and you would like us to know about it in advance, please let us know by emailing your trainers directly, or by contacting [instructor.training@carpentries.org](mailto:instructor.training@carpentries.org).

Instructors can then have a conversation with an individual with regards to specific adaptations that can be made to the scheduled training to better include them. This goes beyond autism and is good practice for people with other disabilities (both visible and invisible).

**Comment by sjmf** [comment]
## 4. Visual noise and Task Switching (Etherpads)

While an incredibly useful teaching tool, the use of Etherpad for presenting information-heavy content may be exclusionary to some people. In particular, for dyslexic people and people who use screen readers this format may be almost _completely_ inaccessible. There may also be issues experienced by colorblind people with distinguishing between typists as denoted by the background colour.

I found the Etherpad useful during the lesson exercises, when participants were populating content into the page shared between the group. However, the instructor checkout process requires signing up for a community discussion and a teaching demo using the pads at https://pad.carpentries.org/community-discussions and https://pad.carpentries.org/teaching-demos. 

The information density of these two pages can be stressful when just five minutes is allocated for signing up within the training schedule. Being presented with this page (with no indexes or hyperlinks to find specific sections within it!) is a high amount of visual noise and it is difficult to navigate, especially when attention is also split with the Zoom call. Philipp handled this really well and clarified that I could come back to these later, but this could be emphasised within the teaching material, or perhaps a more streamlined way could be found to track sign ups to these sessions.

This could also be due to difficulties task switching: changing from a lecture-based learning approach to having to interpret large amounts of data.

**Comment by sjmf** [comment]
## 5. Information presentation

Working memory is often a cause of difficulty in neurodiverse individuals, both within autism (executive dysfunction) and ADHD. In the format of the online training, the instructors used slides with the tasks to direct learners, but when moving into breakout rooms these were no longer visible. As a result, I was not always able to remember what we were supposed to do as a group. 

There were a few occasions like this during the training where it was difficult to keep track of the task because these exercises were not readily visible in the course content (perhaps because I couldn't find them, or the course page did not match the slide). One example is the the [Launches and Landings](https://carpentries.github.io/instructor-training/23-introductions/index.html) section on the second day. 

Finding some way to ensure that participants can always see the task they are currently on, to glance back and refresh their memory, would be helpful here.

**Comment by brownsarahm** [comment]
Hi @sjmf  thanks SO MUCH for this very detailed information and specific actionable feedback.  In order for us to actually act on all of these great ideas, I have created a number of separate issues both in this repository and in other places when the way the carpentries operates suggests that those changes would live in other repositories.  Smaller, more digestible issues are easier for us to act on and triage appropriately, so I will close this one with this comment. All of those issues link back here, as this one links out to all of them above this comment. 

If you think my breakdown of your advice into actionable chunks is insufficient, please re-open the issue and continue this discussion.


The only point I have not left in other issues is the part about the timing of trainings, we are already actively experimenting with that, though it is not well documented that we are.

**Comment by brynnelliott** [comment]
Thank you @sjmf ! This is great information. I am the new Accessibility Manager for The Carpentries. Your suggestions are very timely! We are in the process of creating a Toolkit of IDEAS (Inclusion, Diversity, Equity, and Accessibility Strategies) to better support our community. We are also in the process of making some changes/additions/suggestions related to accessibility for the instructor training and the lessons in general. If you have the time, I would also encourage you to fill out this form with any other suggestions you may have. https://docs.google.com/forms/d/e/1FAIpQLSe5PyzhE7uaAdX3jE-RWoKSYS0ILF0x42c3Y0KXMlNg3V2HKQ/viewform?pli=1 

Thank you @brownsarahm for splitting these up. Very helpful.
