### ISSUE TITLE
Pedagogy vs Andragogy

### ISSUE THREAD

**Issue by Aoife4** [carpentries/instructor-training#1397]
I was just wondering if  the use of the phrase [Pedagogical Model ](https://carpentries.github.io/instructor-training/02-practice-learning/index.html#the-carpentries-pedagogical-model)is a good fit for the Carpentries. As all the Carpentries cater largely to adult learners should it not be [andragogy ](https://en.wikipedia.org/wiki/Andragogy)which describes adult learning. My understanding of andragogy is that is that a core principle is that it is self driven which very much describes learners engagement with the Carpentries. 

But I am by no means an expert but maybe this is something to discuss?

**Comment by brownsarahm** [comment]
This topic has been moved to a [discussion on the trainer's repo](https://github.com/carpentries/trainers/discussions/92)
