### ISSUE TITLE
Considering to host research-themed gathering or events?

### ISSUE THREAD

**Issue by mecui22rri** [carpentries/instructor-training#1410]
I appreciate the amount of support and resources available on this site, especially, the themed workshops that are being offered to us. I would suggest the community to consider the possibility of hosting research-themed events or meetings. For example, a meeting that is dedicated for people studying psychology. The benefits and effectiveness of such meetings could be amplified because people in the same research stream would share many things in common, such as the research method, preferred programming languages and styles, teaching audience, issues, and etc. In addition, this could also facilitate the communication and even collaboration of people across institutions and countries, considering the large supportive community here.

**Comment by brownsarahm** [comment]
This would fit as a [community discusison](https://carpentries.org/community_discussions/) there is a form on that page to volunteer.
