### ISSUE TITLE
"up and down" exercise title is confusing

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/instructor-training#1419]
[in live coding is a skill ](https://carpentries.github.io/instructor-training/17-live/index.html#up-and-down)

it confounds with the "one up one down" feedback mechanism we teach.

**Comment by Nazeeefa** [comment]
Suggestion: title could be replaced with 'pros' and 'cons' or 'benefits' and 'challenges'

**Comment by brownsarahm** [comment]
closed by #1426
