### ISSUE TITLE
vcf.csv file for Data Analysis and Visualization in R lesson.

### ISSUE THREAD

**Issue by sohyunbk** [carpentries/instructor-training#1421]
The half of the episodes in [Data Analysis and Visualization in R](https://datacarpentry.org/genomics-r-intro/), requires "/home/dcuser/r_data/combined_tidy_vcf.csv" file for variants object.
Some people might not have the file if they did not perform analysis from the previous lesson, but want to learn data analysis in R.
It would be great if we connect the link to download the vcf.csv file in https://datacarpentry.org/genomics-r-intro/03-basics-factors-dataframes/index.html page.

**Comment by brownsarahm** [comment]
Thanks for this information, but this is the wrong place for this issue, this repository is only for the instructor training curriculum.  Please open it on the [repository corresponding to that lesson](https://github.com/datacarpentry/genomics-r-intro/issues) 

GitHub doesn't allow us to transfer it for you from the [Carpentries GitHub organization](https://github.com/carpentries) to [Datacarpentry GitHub organization](https://github.com/datacarpentry), so I'm going to close this one (it can still be viewed) and you will have to open a new issue.
