### ISSUE TITLE
Re-organize checkout instructions page

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#1449]
I just sent an email to Trainers letting them know we have changed the instructions on how trainees should submit their lesson contributions.  I made a few quick and dirty updates to the [checkout instructions](https://carpentries.github.io/instructor-training/checkout/index.html) page, but I think it could use some more thorough re-organization.

Some points:

* The page is top-heavy with instructions on how to use GitHub and contribute, often duplicating what's in the linked [resource for novice contributors](https://github.com/carpentries-incubator/swc_github_flow/blob/main/for_novice_contributors.md).
*  The instructions for this checkout task are buried at the bottom in a section called "Alternatives to GitHub" -- this should probably be in its own section.  (Note the instructions used to say to email us the contribution; I changed that to say submit it by logging into AMY, but that was still in the same section)
* We offer people a chance to share how we can make our resources more contributor-friendly by emailing us a link.  If someone was to do that, I would actually consider those recommendations to be contributions fulfilling checkout requirements.  
* "What comes next" section could probably include a reminder to check back in AMY in 7-10 days to make sure their contribution was approved for checkout, even if it was not responded to in GitHub.

**Comment by ndporter** [comment]
Closing issue as outdated following launch of new checkout process in 2023.
