### ISSUE TITLE
LinkedIn Badges

### ISSUE THREAD

**Issue by jensbri** [carpentries/instructor-training#1455]
Kia ora/hello from New Zealand.

I was wondering if you have thought about creating a badge that can be easily posted to a LinkedIn page. 
There is a service that creates such badges, https://credly.com/, but there might be other/better options. 
Completing the Instructor Training and having the result posted to the LinkedIn network with just a couple of clicks, that 'result' being officially certified seems neat.

Cheers,
Jens

**Comment by karenword** [comment]
I believe this suggestion has received attention via email from @carpentries/core-team-community . Closing as this does not directly relate to the Instructor Training Curriculum (until/unless it is implemented elsewhere).
