### ISSUE TITLE
Broken link in instructor material: Error 403

### ISSUE THREAD

**Issue by arockenberger** [carpentries/instructor-training#1479]
Dear maintainers!

I found the link https://preview.carpentries.org/instructor-training/icebreakers/ to lead to an error 403 "Forbidden". See the full error message in the screenshot.
![Screenshot 2023-02-14 at 12 29 49](https://user-images.githubusercontent.com/12702667/218725488-bc81ca4f-e49d-44de-92f3-21fc033a7e41.png)

Best,

Annika

**Comment by tobyhodges** [comment]
Good catch @arockenberger, thanks for reporting this. The Icebreakers page is now at https://preview.carpentries.org/instructor-training/instructor/icebreakers.html. Can you tell me where you found the incorrect link?

**Comment by arockenberger** [comment]
I.E. "More examples of Icebreakers" gives me the 403

**Comment by zkamvar** [comment]
Thank you again for reporting this! The link should be fixed now thanks to @tobyhodges and @ndporter!

I apologise for the mixup, it was a link that was missed during the transition to The Workbench, and thus, _mea culpa_
