### ISSUE TITLE
Remove Registration Confirmation Page from menus

### ISSUE THREAD

**Issue by karenword** [carpentries/instructor-training#1486]
[this page](https://preview.carpentries.org/instructor-training/instructor/registration_confirmation.html) doesn't need to be in the Instructors OR the learners' menu -- it is a page that exists only to be linked from Eventbrite. 

Will it break anything if we just take it off the list in the yml? @zkamvar

**Comment by maneesha** [comment]
In the old setup, this was achieved by having `exclude: true` in the yml frontmatter.

**Comment by zkamvar** [comment]
I was _wondering_ where the h\*ck to put that page. Right now, there is no `exclude` parameter. I can add one, but a more immediate solution would be to move https://github.com/carpentries/instructor-training/blob/main/instructors/registration_confirmation.md to the root folder (and don't forget to remove it from the config list
