### ISSUE TITLE
Amy account not recognizing GitHub Account

### ISSUE THREAD

**Issue by pageneck** [carpentries/instructor-training#1495]
Have faced this issue, which I wish to bring to the team that my Amy account cannot associate to my GitHub account and provides the following error when i try to login as instructor.

No account is associated with your GitHub account.

yet i have created an Amy profile and have added permission to my GitHub account

**Comment by brownsarahm** [comment]
Please e-mail the team at: [instructor.training@carpentries.org](mailto:instructor.training@carpentries.org)
