### ISSUE TITLE
Add solution for Sticky Situations 1: 'What Are the Challenges?' exercise in episode 21

### ISSUE THREAD

**Issue by anenadic** [carpentries/instructor-training#1506]
While this is a discussion exercise that does not require a solution necessarily, perhaps we should add it nonetheless to help trainers with some talking points. For example, the challenges when teaching learners with a broad range of expertise may include:
- Varying prior knowledge
- More varied interests, expectations and goals for coming to the workshop
- Getting the pace right with both novice and more advanced learners - more difficult to keep all learners motivated
- More varied/customised setups at machines used by learners that instructors may be expected to understand/support
- etc.

More suggestions welcome!

**Comment by ndporter** [comment]
@anenadic I like this idea. I've added your list with some prefatory text as an instructor note in #1585 . We'd love it if you take a look and suggest any edits or additions there. Thanks!
