### ISSUE TITLE
Correct link to Instructor Training etherpad in Instructor Training Instructor Notes

### ISSUE THREAD

**Issue by karlbenedict** [carpentries/instructor-training#1534]
In trying to relocate the etherpad template [https://pad.carpentries.org/ttt-template](https://pad.carpentries.org/ttt-template) to make a needed correction to the default break times I discovered that the template link in the Instructor Training Instructor Notes ([https://carpentries.github.io/instructor-training/instructor/instructor-notes.html](https://carpentries.github.io/instructor-training/instructor/instructor-notes.html)) points to a non-existent etherpad. The link should be corrected from [https://pad.software-carpentry.org/ttt-template](https://pad.software-carpentry.org/ttt-template) to [https://pad.software-carpentry.org/ttt-template](https://pad.software-carpentry.org/ttt-template). This link is near the top of Section II of the Instructor Notes document. 

BTW - the [Edit on GitHub](https://github.com/carpentries/instructor-training/edit/main/README.md) link takes you to the top level of the Instructor Training repository without a clear reference to the Instructor Notes content that needs to be corrected.

**Comment by ndporter** [comment]
Closed by #1535
