### ISSUE TITLE
Python code typo: Foundations of Astronomical Data Science lesson / Episode 8 / 'rcParams' section

### ISSUE THREAD

**Issue by nothgid88** [carpentries/instructor-training#1537]
Hi,

The issue is regarding a small typo that needs correcting in the Foundations of Astronomical Data Science lesson / Episode 8 / 'rcParams' section (half way down the page). The link for the page is: https://datacarpentry.org/astronomy-python/08-plot/index.html

If you scroll half way down the page, you will see the five-minute exercise about plotting _"the previous figure again, and see what font sizes have changed. Look up any other element of rcParams, change its value, and check the effect on the figure"_.

If you click on the solution, there will be some python code and it's the word in bold below that needs to change from axis to axes:

Current version:
plt.rcParams['**axis**.edgecolor'] = 'red'

Correct version:
plt.rcParams['**axes**.edgecolor'] = 'red'

Thank you.

**Comment by brownsarahm** [comment]
Hello you should open an issue on the [data carpentry/astronoy-python](https://github.com/datacarpentry/astronomy-python/issues) repo.
