### ISSUE TITLE
On "Summary and Setup" page, link to "Tracking Changes in git" is broken

### ISSUE THREAD

**Issue by allie-tatarian** [carpentries/instructor-training#1549]
Under the [Recommended Episodes]( https://carpentries.zoom.us/my/carpentriesroom2?pwd=WmVCOUlPUm1laFk5SUp1UWg5cjhEUT09), "Tracking Changes in git" currently leads to a [Page Not Found](https://swcarpentry.github.io/git-novice/04-changes/) within the git lesson.

**Comment by sjvrijn** [comment]
I believe this issue can be closed, since it seems like #1559 has indeed fixed the broken link(s) on the Summary and Setup page under [Recommended Episodes](https://carpentries.github.io/instructor-training/index.html#recommended-episodes)
