### ISSUE TITLE
Broken link in instructor training post survey

### ISSUE THREAD

**Issue by nicole-brewer** [carpentries/instructor-training#1552]
At the very end of the instructor training post survey (made with typeform), there is a hyperlink to the checkout instructions page. The link is incorrect. It is currently https://carpentries.github.io/instructor-training/checkout/index.html, but it should be https://carpentries.github.io/instructor-training/checkout.

**Comment by brownsarahm** [comment]
@karenword who maintains the survey? 

PS. @nicole-brewer this can count as your checkout contribution if you would like.

**Comment by klbarnes20** [comment]
Thanks for letting us know @nicole-brewer! This has been fixed and so I'm closing this.
