### ISSUE TITLE
Improve this page -> Edit this page

### ISSUE THREAD

**Issue by gurinovich** [carpentries/instructor-training#1575]
Episode: https://carpentries.github.io/instructor-training/instructor/checkout.html#contributions

The interface looks a bit different than the one shown for editing the page. Instead of "Improve this page" button, that is also shown as a screenshot for demonstrating purposes, to edit the page, one needs to click "Edit this page" under the title "Checkout Instructions".

**Comment by ndporter** [comment]
Closing issue as this appears to have been included in updates (see [current version](https://carpentries.github.io/instructor-training/checkout.html#how-to-contribute-github-101)) when the revised checkout process was launched or thereafter (though I couldn't find the actual commit). Thanks for calling to our attention!
