### ISSUE TITLE
Typo in "A Note on Cutting"

### ISSUE THREAD

**Issue by geneticwitch** [carpentries/instructor-training#1642]
### What is the problem?

The note starts with "This episode is a common place to Trainers to cut while preparing to teach." It would probably make more sense if it was phrased more along the lines of "This is a common episode that gets cut when preparing to teach."

Also, this note might be better placed after the page introduces "cutting" later on, rather than before. 

### Location of problem (optional)

https://carpentries.github.io/instructor-training/18-preparation.html

**Comment by brownsarahm** [comment]
My PR is a little bit different from your suggestion, because we generally do not skip the whole episode but cut parts of it. But please do let me know if that clarifies for you or is still confusing. 

I also explained why I prefer the box where it is, but I welcome other thoughts.
