### ISSUE TITLE
Callouts are all in capitals

### ISSUE THREAD

**Issue by marklcrowe** [carpentries/instructor-training#1646]
### What is the problem?

Callout sections are coming up as all capitals and underlined - see https://carpentries.github.io/instructor-training/02-practice-learning.html#analogies-at-work-software-carpentry for an example, but it seems to be happening throughout the lesson. It should be just the title is capitalised and underlined. 

Behaviour is as expected in other lessons (e.g. https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro.html#tip-running-segments-of-your-code in R for Reproducible Scientific Analysis), so although it's universal within the Instructor Training lesson, it's not apparently affecting others.

**Comment by brownsarahm** [comment]
For me it is all caps in both of those lessons' callouts... 

However, the R lesson was rebuilt between this issue being posted and today. Per [commit history](https://github.com/swcarpentry/r-novice-gapminder/commits/main/) the [most recent commit](https://github.com/swcarpentry/r-novice-gapminder/pull/884) upgraded versions of dependencies

By inspection it looks like this is a sandpaper issue, so i am going to open one over there.

**Comment by froggleston** [comment]
This was fixed in https://github.com/carpentries/sandpaper/pull/574
