### ISSUE TITLE
Checkout Instructions - Get Involved! - Attend a Regional Call, Skill-Up Session, or Other Community Programming

### ISSUE THREAD

**Issue by jelollar** [carpentries/instructor-training#1652]
### What is the problem?

In the Checkout Instructions episode, under the header Get Involved and then Attend a Regional Call, Skill-Up Session, or Other Community Programming, there is a link issue. The hyperlink for "Community Sessions Etherpad" goes to the 2023 etherpad, rather than the 2024 etherpad. 

Link should be replaced with the current one, which is https://pad.carpentries.org/community-sessions-2024

![etherpad link](https://github.com/carpentries/instructor-training/assets/163005936/485f9eb8-f454-4a87-a9dc-407ecc1a9e9e)
![etherpad link 2](https://github.com/carpentries/instructor-training/assets/163005936/2b149704-0906-4199-b210-0016c68e6f4a)

**Comment by brownsarahm** [comment]
When I look at the source, it appears to me to be correct now, could you link to the page where it is wrong?

**Comment by sjw46** [comment]
I have a suggestion for how to improve the checkout instructions:

I think it should be made explicit that the three checkout steps can be completed in any order.
Currently the steps are written out as a numbered list (1., 2., 3.), and to me at least, this implies that they should be completed in that specified order. 
<img width="790" alt="Screenshot 2024-07-08 at 3 29 48 PM" src="https://github.com/carpentries/instructor-training/assets/123393588/2c6e0326-53c5-4518-8684-dbe6717f53ea">

https://carpentries.github.io/instructor-training/checkout.html#getinvolved

**Comment by brownsarahm** [comment]
@sjw46 I opened a new issue for your suggestion, because these are two separate fixes.
