### ISSUE TITLE
Jargon definitions needed

### ISSUE THREAD

**Issue by marklcrowe** [carpentries/instructor-training#1655]
### How could the content be improved?

In episode 15 there is a discussion exercise about definitions of some jargon terms. There aren't definitions included in the manual at this point, and I've not been able to find any good source of definitions for those six terms. Most of them I've been able to track down somewhere, but I've yet to find a clear and concise description of perhaps the most critical, which is what a lesson is (other than a collection of episodes, but that's just a circular definition since an episode is defined as part of a lesson). Would it be possible to provide definitions, links to definitions, or consider dropping this actvity?

### Which part of the content does your suggestion apply to?

https://carpentries.github.io/instructor-training/15-carpentries.html#test-yourself

**Comment by brownsarahm** [comment]
@sheraaronhurt are there official definitions for these terms somewhere that you could help us find (and/or let me know if you are the wrong person to ask)

If not maybe this is a good trainer meeting topic? @ndporter

**Comment by sheraaronhurt** [comment]
@brownsarahm this is a great question. This came up at the past trainer meeting. I am going to check with the Core Team to see but if not, I will definitely add as an upcoming trainer meeting topic.

**Comment by annajiat** [comment]
- [Lesson](https://carpentries.github.io/curriculum-development/our-curriculum-structure.html#lessons)
- [Episode](https://carpentries.github.io/curriculum-development/our-curriculum-structure.html#episodes)
- [Workshop](https://carpentries.org/workshops/#workshop-core)
- [Lesson Program](https://carpentrieshandbook.readthedocs.io/en/latest/topic_folders/governance/lesson-program-policy.html)
- [Instructor](https://docs.carpentries.org/topic_folders/for_instructors/new_instructors.html#who-are-the-instructors)
- (Instructor) [Trainer](https://docs.carpentries.org/topic_folders/instructor_training/duties_agreement.html)

I had linked to the Curriculum Development Handbook which may get retired as discussed in https://github.com/carpentries/curriculum-development/issues/81

It would be great to learn if there are more appropriate references to the six jargons above in the context of The Carpentries.

Tagging @tobyhodges for potential input.

**Comment by kariljordan** [comment]
Some of these terms are also defined in the [community glossary.](https://github.com/carpentries/community-development/blob/main/glossary.md#lesson)
