### ISSUE TITLE
Change references to Executive Council to Board of Directors

### ISSUE THREAD

**Issue by froggleston** [carpentries/instructor-training#1673]
### How could the content be improved?

As the Executive Council no longer exists and is replaced by the Board of Directors, references to the EC should be replaced with descriptions and links to the new information: https://carpentries.org/governance/

### Which part of the content does your suggestion apply to?

https://carpentries.github.io/instructor-training/instructor/15-carpentries.html

**Comment by brownsarahm** [comment]
@kariljordan while we are in the transition period and have two bodies, should we explain the currents status or the future model?  Should we wait and revise to BoD when the transition is complete?

**Comment by brownsarahm** [comment]
a PR would be great.

**Comment by kariljordan** [comment]
#1689 is ready

**Comment by brownsarahm** [comment]
closed via #1689
