### ISSUE TITLE
Update Data Carpentry Ecology Suggested episodes for practice and demos

### ISSUE THREAD

**Issue by ndporter** [carpentries/instructor-training#1683]
### How could the content be improved?

Update all episode links to Data Carpentry ecology R curriculum (on the setup page, the suggestions on day 1 homework, and the suggested teaching demo episodes) to match the revised version of the curriculum - including both link checking and verifying the episodes are still suitable. Ideally, this should be launched simultaneously or as soon as possible after July 8, when the curriculum officially transitions.

**Comment by ndporter** [comment]
@tobyhodges is there a good way to plan for what the links will be and queue this to merge when the changeover happens?

**Comment by tobyhodges** [comment]
I am aiming to handle all of this on 8th July, so you can expect a PR on that date.
