### ISSUE TITLE
Confusion regarding use of "lesson" in exercise

### ISSUE THREAD

**Issue by murraycadzow** [carpentries/instructor-training#1718]
In the learning objective exercise, it is unclear (especially in the Carpentries lesson/episode definition context) if this is referring to the lesson as a whole, or in the selected episode

https://github.com/carpentries/instructor-training/blob/404c641bea073708f20dedd8d8be7558facc18d6/episodes/18-preparation.md?plain=1#L147

**Comment by brownsarahm** [comment]
thanks @murraycadzow I agree this point should refer to episode, I've put in a PR.
