### ISSUE TITLE
Refer to new lesson infrastructure

### ISSUE THREAD

**Issue by fiveop** [carpentries/instructor-training#1720]
### What is the problem?

In episode 15, in section [Setting Out On Your Own](https://carpentries.github.io/instructor-training/instructor/15-carpentries.html#setting-out-on-your-own-together-lesson-incubation) we link to the old example lesson repository and page. The page does refer directly to then new lesson infrastructure, but we should directly link to it from IT material.

### Location of problem (optional)

https://carpentries.github.io/instructor-training/instructor/15-carpentries.html#setting-out-on-your-own-together-lesson-incubation

**Comment by ndporter** [comment]
Closed by #1721
