### ISSUE TITLE
Add links to the Keep in Touch section

### ISSUE THREAD

**Issue by astroDimitrios** [carpentries/instructor-training#1739]
### How could the content be improved?

In episode 15 there are lots of ways to keep in touch with the community mentioned (slack etc.). Can we add links to help people sign up / navigate to these communication methods?

### Which part of the content does your suggestion apply to?

https://carpentries.github.io/instructor-training/instructor/15-carpentries.html#keeping-in-touch

**Comment by brownsarahm** [comment]
For maintainance reasons, we link to the page where those links are instead of directly to them.  This way, when thy change there are fewer things to fix.
