### ISSUE TITLE
Add testimonial to list of suggestions for get involved step

### ISSUE THREAD

**Issue by ragamouf** [carpentries/instructor-training#1749]
### How could the content be improved?

Could trainees submit a testimonial on instructor training as per the website updates in Nov 2024? Seems like great advocacy, and a low bar effort with pretty good pay off. Here's an excerpt from the blog post:

> As such, we ask you to please:
> Share a testimonial: One brief sentence with your photo that we can add to the website’s testimonial section. We would like to update these testimonials once every quarter to showcase the diversity of our community. Please email your testimonial to [community@carpentries.org](mailto:community@carpentries.org).

### What it would look like:
At https://carpentries.github.io/instructor-training/checkout.html#getinvolved the new bullet list would read like this:

- Serve as an Instructor or a Helper at a workshop
- Attend a regional call, skill-up session, or other community programming
- Submit a contribution to a Lesson, Glossario, or other Carpentries repository
- Submit a 1 sentence testimonial with your photo to The Carpentries Website section on the value or benefit of Instructor Training. Please email your testimonial to [community@carpentries.org](mailto:community@carpentries.org).

### Which part of the content does your suggestion apply to?

https://carpentries.github.io/instructor-training/checkout.html#getinvolved

**Comment by OscarSiba** [comment]
Here is a summary on my view on this suggestion, as discussed on the #Trainers channel on Slack: 

The options that are currently suggested as forms of participation in Carpentries activities as part of Checkout seem to aim at meaningful participation: serving as an Instructor or a helper at a Carpentries workshop, attending a regional call, making a contribution to lessons, etc. - all these seem to be engaged activities by way of which the person checking out gets an opportunity to learn more about The Carpentries before making their contribution. Any one of these activities would be equivalent in terms of engagement with the community. 

However, I do not think that submitting a 1 sentence testimonial on the value or benefit of Instructor Training has the equivalent level of engagement with the community or its processes as the other suggested activities. As such I would not include it on this list. If more experienced Trainers and other community members , as well as @sheraaronhurt who overlooks this programme from the Core Team, think that this activity is equivalent, I would of course support that decision.

**Comment by brownsarahm** [comment]
I think most people will be able to contribute more testimonials that are more informative and actionable for prospective instructors and learners after they complete the checkout process and teach at least once.

**Comment by sheraaronhurt** [comment]
Thanks @OscarSiba and @brownsarahm after reviewing the feedback, I must agree with you both. This should not be a part of checkout. Thanks @ragamouf for starting the conversation.

**Comment by ragamouf** [comment]
Ah that's fair I guess.
