### ISSUE TITLE
Explicit instructor agreement

### ISSUE THREAD

**Issue by gvwilson** [carpentries/instructor-training#349]
Library Carpentry instructor agreement taken from <http://pad.software-carpentry.org/library-carpentry> - we should generalize and have instructors agree to it in training.

*   I agree to use one or more of the Library Carpentry modules in my Library Carpentry workshops.
*   I understand that the secondary learning outcomes of Library Carpentry workshops are as important as their stated goals. These include (but are not excluded to) learners a) being introduced to the value of non-proprietary file formats, good data management, peer-to-peer learning, not always using GUIs, computational approaches to working with library data; and b) feeling more confident to admit what they don't know, collaborate with developers, pursue further self-directed learning.
*   I agree to support and encourage learners and I endeavour to ensure that attendees have an enjoyable and fulfilling experience.
*   I agree to honour the Software Carpentry code of conduct.
*   I am aware that as Library Carpentry grows, it has an ambition for the lead instructor of every Library Carpentry workshop to have undergone Software/Data Carpentry instructor training. I am aware that by becoming a Software/Data Carpentry approved instructor I can help grow and enrich the Library Carpentry community. Having therefore been a instructor at a Library Carpentry workshop, I agree to consider becoming a Software/Data Carpentry approved Instructor.

**Comment by karinlag** [comment]
I am wondering if we should send this one out to the community for comments, once we have software/data carpentried it...?

**Comment by ErinBecker** [comment]
No comments on this in quite a while. If anyone feels strongly about following up on this, please comment and add your suggestions. Else will be closed due to lack of activity on 3/22.

**Comment by karinlag** [comment]
I started a doc for this here:

https://docs.google.com/document/d/1LWxy_hs3FRm3K2Q6eZti4FXqsbl574f5aCXwbWJ5adk/edit?usp=sharing

NOT done by any means, but just to get the ball rolling.

**Comment by karinlag** [comment]
Maybe we could address this one on the instructor discussion session next week? (aka the 19th of April).

**Comment by naupaka** [comment]
I am +1 for having something like this.

**Comment by mkuzak** [comment]
+1 for having the agreement

**Comment by ChristinaLK** [comment]
I was under the impression that this would be an agreement for the *instructors* not the trainers.  Personally I'm in favor of both -- should this be two separate issues?

**Comment by mkuzak** [comment]
@ChristinaLK I made a similar comment in the google doc. I agree to have both. I'm in favour of two separate issues. The content/wording will be slightly different in both.

**Comment by mkuzak** [comment]
@ErinBecker this issue got some traction now, can we remove the `stale` label?

**Comment by ErinBecker** [comment]
Thanks @karinlag for setting up this document. I have a set of expectations that I drew up along with @maneesha for the Trainers who are going through Training now. This was done in order to ensure that new Trainers understood the time requirements for the position, and so that we would be able to ensure that we know how much time we have available to schedule for trainings. The nine new Trainers have agreed to the requirements described [in this document](https://docs.google.com/document/d/14Zi_W9uk1wua2v3zy8um6oMCnvO41Qfo1KwStCA-hos/). I had planned an update on this to the SC at your meeting this week (cc @k8hertweck). 

The document I drew up mostly deals with time commitments, and not with other aspects that you had covered in your document. I think that synthesizing these two documents will put us very close to covering all of the needs we have of this agreement. 

cc @tracykteal

**Comment by karinlag** [comment]
Thanks for all of the input that has come on this issue. I will wait with stitching all of this into a (semi-)coherent whole until after the business meeting tomorrow, to ensure that everybody have had a chance to give feedback on this. If nobody disagrees on the general direction this thing is taking, I think we could aim to have this settled by the next business meeting.

**Comment by ErinBecker** [comment]
I started a new issue (#477) to discuss the Trainer agreement.

**Comment by ErinBecker** [comment]
We now have [a Trainer agreement](https://github.com/carpentries/policies/blob/master/trainer-agreement.md) that was voted on and approved by the Trainers group, but no forward movement on an instructor's agreement. Does anyone want to take lead on putting a draft together and getting community input?

**Comment by ErinBecker** [comment]
Adding an "after-release" label as I don't think we'll have a new policy in place by the time of new release.

**Comment by kariljordan** [comment]
Ready to close this issue?

**Comment by karinlag** [comment]
This ball has been resurfaced, don't close yet.

**Comment by brownsarahm** [comment]
I think this can be closed? general volunteer agreements are out of scope for this repository, though we would link to such a policy once it exists.
