### ISSUE TITLE
change concept map?

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/instructor-training#505]
The concept map used in the lesson illustrates a for loop in python. However, it seems that a significant fraction of people participating in our instructor training (as well as the instructor trainers) may not be  fluent in python. For them, having to decipher what the loop does distract them from focusing on the point of learning about concept map.

I can think of a few ways to improve this:
- create a concept map on something that is language agnostic, maybe using one of the concepts taught during instructor training instead
- set up the concept map by explaining first what is the "loop variable", the "loop body" and "collection" in relation to the piece of code. By making clear which part is which, it reduces the distraction of having to decipher what the loop does.

Personally, I always find it difficult to explain concept maps put together by others, so adding a note in lesson to encourage instructor trainers to come up with their own maps could also be useful.

**Comment by gvwilson** [comment]
My experience is the same as yours - enough participants are unfamiliar with Python that we should choose something language-agnostic. Would a subset of <http://third-bit.com/toronto-zoo-concept-map.jpg> or something like <http://third-bit.com/hijab-concept-map.jpg> work for more people? (I hesitate to use a map of concepts in education - that feels a little too self-referential.)

**Comment by gvwilson** [comment]
This concept map is also very accessible (if a bit crowded in places): <http://cmap.ihmc.us/docs/images/Theory/Fig5CmapSeasons-large.png>

**Comment by ChristinaLK** [comment]
I agree with @fmichonneau that we could have a more widely accessible concept map.  @gvwilson I like all of your examples except, as you note, some of them are larger/more complex than we'd want to use for an initial example in teaching.

**Comment by karinlag** [comment]
Referring to the Seasons concept map,  maybe we could use the things in it to gradually build up a concept map? If we do it gradually, we could build something slightly "larger" without making it too complex.

**Comment by karenword** [comment]
I do like the staged construction in the Python example, even though I don't speak Python. @ErinBecker  did a really great explanation of this example that I think worked well for everyone, in which she connected the code to the concept map more explicitly, getting the basic idea across with just enough information for the map to make sense without over-doing it. If it stays I think we should build in some of her explanation. I think it might be nice to have multiple examples here, ideally also simple and staged.

**Comment by ErinBecker** [comment]
A good discussion here! Thanks @gvwilson for the example concept maps. I agree with @karenword that there is great value in keeping our examples related to the material that is part of the SWC/DC cannon whenever possible. This helps with buy-in (learners can more immediately see utility) and gives them a clearer model for when they do their own concept mapping exercise.

I don't speak Python myself and actually have found that the example we have in the materials is good for this reason. Coming at it from a novice perspective, I'm able to explain it (based on familiarity with the concept of for loops and their implementation in R), yet am able to see the points that would be confusing to a novice learner. I've also found that we have a good distribution of people who speak either R or Python, and the concept of a for loop isn't completely novel to them. 

What about having an alternative concept map that did the exact same thing with R syntax? Or for a bash for loop?

**Comment by allisonweber** [comment]
I am a new trainee who recently took the instructor training.  I would like to suggest a concept map based on Git version control (see attached document).  From what I've heard, most of the Software carpentry and data carpentry workshops are teaching Git as the version control portion of the workshop so this might be more accessible to a broad audience than R or python.  I have attached the powerpoint slide so that anyone can make edits to the concept map to improve it.  
[GitConceptMap.pptx](https://github.com/carpentries/instructor-training/files/1518099/GitConceptMap.pptx)

**Comment by ErinBecker** [comment]
@allisonweber - Thanks for this suggestion. However, Data Carpentry does not teach Git in any of our workshops (currently) and I'm hesitant to include this in the materials for that reason. 

I'd be happy to add an alternate concept map illustrating a for loop in Bash or R if anyone would like to put in a PR for one of those.
