### ISSUE TITLE
Fluid representation

### ISSUE THREAD

**Issue by weaverbel** [carpentries/instructor-training#508]
Having taught this part of the lesson today, I found it really hard to get this concept across in a way that people could use to do the given exercise. I tried to make it more concrete and to give more examples but people still didn't get it and just ended up confused. Has anyone got any good ideas for doing this? Happy to hear anything that brings this to life for me.

**Comment by ErinBecker** [comment]
- Referring to R object types as "characters" vs "strings," or switching back and forth between "df[,1]" and "df[,'foo']" notation when talking about columns in a data.frame
- Common name vs latin name of a species.  
- Biology: Three letter vs one letter amino acid codes.
- Mathematical example: thinking of things algebraically vs geometrically
- Navigation -- being able to create new paths between locations

**Comment by ChristinaLK** [comment]
One example that I now remember I've used before is navigating when driving (or walking, or biking, or whatever).  An expert (local person) can navigate using landmarks, cardinal directions, step-by-step directions, etc. For example, they can "fact-check" the step-by-step directions given by their phone's nav program, by switching to the representation of the place they have in their head.  Or think of a street name OR a landmark when giving/receiving directions.  But a novice or even competent practioner can only think using either the map or step-by-step directions, and won't necessarily know landmarks.
