### ISSUE TITLE
Faded example

### ISSUE THREAD

**Issue by weaverbel** [carpentries/instructor-training#509]
I find it hard to teach the faded example to people who are not programmers. Since they don't know what the parts are, they can't identify what is missing, so they miss out on how and why this might be a useful tool.

I would prefer to see this taught with something more concrete - maybe the shell example we use in the lesson, or even something like a recipe - something that most people could relate to.

**Comment by karenword** [comment]
I think this is related to the problem stated in https://github.com/swcarpentry/instructor-training/issues/505 -- I think coming up with general examples and/or multiple examples that people can pick and choose from is a good idea.

**Comment by amyehodge** [comment]
Agreed! We had someone in the training yesterday who was finally able to explain this example to me... but then also picked a bunch of holes in it. :P More options would be nice.

**Comment by ErinBecker** [comment]
Agreed that it would be great to have multiple examples here for the Trainer to choose from. Would anyone be able to put in a PR with a couple of alternate examples?
