### ISSUE TITLE
"official" mindset assessment??

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#518]
In the mindset section 
https://carpentries.github.io/instructor-training/09-mindset/
this: https://mindsetonline.com/testyourmindset/step1.php
is referred to as the "official mindset self-assessment."

What makes it "official"?

**Comment by arokem** [comment]
Just a guess: the "(C) Carol Dweck" at the bottom :-)

**Comment by maneesha** [comment]
I get that Carol Dweck is the source so it connects to the other research we cite.  The word "official" implies some soft of certifying authority.
