### ISSUE TITLE
home page could use a photo and short summary

### ISSUE THREAD

**Issue by raynamharris** [carpentries/instructor-training#527]
You know how paste a hyperlink to a website on social media, sometimes you get a little pop-up window with a photo and some text from the website? Here are two examples of pop-ups from the instructor training website.

![screen shot 2017-10-11 at 2 34 15 pm](https://user-images.githubusercontent.com/7544197/31462502-963b4866-ae92-11e7-8209-3758a7926dab.png)

![screen shot 2017-10-11 at 2 36 11 pm](https://user-images.githubusercontent.com/7544197/31462505-99e24dca-ae92-11e7-81a2-7d09ecbb1e3d.png)

I think we could improve our home page by adding:

1. a single image with both the SWC and DC logos
2. an opening sentence that states the mission/vision/purpose/objective of instructor training. 

What do you think? Does anyone else agree that we should add these two things

**Comment by weaverbel** [comment]
I agree @raynamharris but won't volunteer to try to add images as that won't end well!

**Comment by ChristinaLK** [comment]
I agree, if we can figure out how to produce the outcome you're looking for.  @raynamharris do you know if we need to tag/flag that material specifically?  Does it go in the header?

**Comment by fmichonneau** [comment]
Resources for facebook are listed here: https://developers.facebook.com/docs/sharing/webmasters and for twitter here: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

From a quick glance, it looks like twitter will use the facebook system (OpenGraph) if it doesn't detect twitter specific tags. 

A couple more thoughts:
- this changes should probably affect not only the templates for the lessons (including instructor training) but also the main sites (e.g. software-carpentry.org)
- I think the main site has recently implemented this, but I also think that the image used (the logo) is on transparent background which doesn't look good on twitter dark background for instance.

**Comment by ChristinaLK** [comment]
Thanks @fmichonneau!

**Comment by raynamharris** [comment]
Thanks @fmichonneau! Yes, the old SWC sites used to have the logo on them, so that would appear on facebook and such.

**Comment by ErinBecker** [comment]
I think this is a good idea. I don't know anything about Facebook, however. Could someone put together a PR to implement this?

**Comment by weaverbel** [comment]
I think this is done via the `excerpt` text in the page header @ErinBecker - Jonah and I added excerpt text to all SWC pages so that real text rather than boilerplate text would appear in Twitter grabs.

**Comment by brownsarahm** [comment]
This has been determined to be an issue for styles in #1246 so we'll get those updates when [the styles PR is merged](https://github.com/carpentries/styles/pull/604) and the updates propagate. I'll close this here.
