### ISSUE TITLE
Add references to mentoring program

### ISSUE THREAD

**Issue by karenword** [carpentries/instructor-training#529]
In places where we talk about the importance of practice, opportunities for lesson contribution & development, & other relevant areas where new instructors might specifically want continuing support, we should add links out to mentoring program documentation as a resource.

**Comment by ErinBecker** [comment]
@karenword - This seems like a good idea. Right now, the mentoring program is not something that new instructors can sign up to at just any point. There are start dates and end dates for each round of the program, and so it may be a while after a trainee completes training before they're able to join the program. @kariljordan - given this, do you think it would be useful to have this information for trainees during the training?

**Comment by kariljordan** [comment]
We had a conversation during the mentoring subcommittee meeting and @tobyhodges suggested that we have a place for people to at least be able to sign up to receive updates about the program. I put that on my list to do, and to add a mentoring page to the website, so we could point them to those places. It's nice for them to know that support will be waiting for them once they complete their training.

**Comment by kariljordan** [comment]
@karenword the Mentoring Page has been added to Data Carpentry's website.

[Here is the page.](http://www.datacarpentry.org/mentoring/)

Feel free to add it to the instructor training wherever you see fit! @weaverbel will add the info about mentoring groups to SwC's mentoring subcommittee page this week.

**Comment by weaverbel** [comment]
Maybe we should just point to DC's page and not try to replicate the info on SWC given the complexity of the subcommittee page ? If so, I can revert the page to what it was before I tried to edit it.

**Comment by weaverbel** [comment]
I have reverted now and it passed checks. Will try to add link to DC info tomorrow.

**Comment by karinlag** [comment]
We could also consider adding this info to the discussion session etherpad? That is a site that all that want to certify have to go to, no matter the carpentry flavor.

**Comment by kariljordan** [comment]
Done.
