### ISSUE TITLE
Add GitHub Etiquette Resource Page?

### ISSUE THREAD

**Issue by karenword** [carpentries/instructor-training#535]
@ChristinaLK and I talked this morning about lesson maintenance and one idea to ease community entry in this area was a "Carpentries GitHub Etiquette Guide." Specifically this would include some detailed examples of different ways of contributing (issues, PRs, commenting on PRs) along with potential errors / reassurances. This is something that would require some input from maintainers, and should be a resource for the community at large, but the Instructor Training curriculum seems like an ideal place to house such a thing, since this is often where the lesson contribution journey begins.

**Comment by ChristinaLK** [comment]
A starting point might be the `CONTRIBUTING.md` that's in all the lesson repos.

**Comment by ErinBecker** [comment]
I agree that it would be helpful for our community to have more guidance about the lesson contribution process, but just adding documentation is usually not an effective answer to this sort of problem. Some combination of documentation and community education (e.g. by adding lesson contribution etiquette and workflow to the instructor training materials) would probably be a good route. 

I've been having meetings with the SWC and DC Maintainers around this and other issues relevant to the Maintainers community. @ChristinaLK and I are meeting to follow up about those conversations and make a cohesive action plan. Can we hold off on this issue until we've had a chance to plan the broader strategy around maintenance and lesson contribution?

**Comment by ChristinaLK** [comment]
added to #711

**Comment by raynamharris** [comment]
these are more related to lesson maintenance, but I use https://help.github.com/articles/configuring-a-remote-for-a-fork/ and https://help.github.com/articles/syncing-a-fork/ a lot.

**Comment by karenword** [comment]
Also maintainers are suggesting that we give new instructors more guidance as to the need to read contribution guidelines for a repository before submitting their contributions. This could go in checkout and/or a separate section on GitHub etiquette.

**Comment by karenword** [comment]
This issue has been addressed to the extent that it can be in this repo; further work is out of scope for this repo but is rumored to be under development elsewhere.
