### ISSUE TITLE
Enable syntax highlighting in Jekyll?

### ISSUE THREAD

**Issue by naught101** [carpentries/instructor-training#543]
As noted at https://github.com/carpentries/instructor-training/pull/536, when using the language-specific code block notation, syntax highlighting is not enabled. I'm not sure if this is intentional or not, but I think syntax highlighting vastly improves code readability, and would be great to have in this course.

I am happy to figure out how to enable this, and create a PR if others thing that's a good idea.

**Comment by ChristinaLK** [comment]
I think this would be a great addition!  

Per comments in the example lesson (built from our template - http://swcarpentry.github.io/lesson-example/04-formatting/): "The following styles are all synonyms for `.source;` please use them where possible to indicate the type of source being displayed, in case we decide to adopt syntax highlighting at some point:"  

So it would be great to actually have it!  It should probably be added at the repo that templates all the lessons (https://github.com/swcarpentry/styles) -- can you open this issue there?

**Comment by naught101** [comment]
Cool, done.

**Comment by weaverbel** [comment]
And @naught101 you are welcome to use this as your checkout lesson contribution - just email the link to it to checkout AT carpentries.org.

**Comment by alistairwalsh** [comment]
Nice.

**Comment by naught101** [comment]
@weaverbel thanks, but I already submitted a separate PR that has been accepted :) https://github.com/carpentries/instructor-training/pull/536

**Comment by naught101** [comment]
(and sent that to the checkout email)
