### ISSUE TITLE
replace amazon links

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#544]
Per this PR (#538) it makes sense to have more general links to recommended books instead of a specific seller.

**Comment by ErinBecker** [comment]
Related PR: https://github.com/carpentries/instructor-training/pull/583

**Comment by ErinBecker** [comment]
This shows all places in the lesson files where we link to Amazon: https://github.com/carpentries/instructor-training/search?utf8=%E2%9C%93&q=amazon&type=

**Comment by karenword** [comment]
Looks like these are all done! Thanks @murraycadzow !
