### ISSUE TITLE
Add Code of Conduct to Motivation lesson?

### ISSUE THREAD

**Issue by tracykteal** [carpentries/instructor-training#546]
In the 'Creating a Positive Learning Environment' section of the 08-motivation lesson, should we add something about saying that there is a code of conduct for the workshop?

**Comment by maneesha** [comment]
This is in the motivation section (https://carpentries.github.io/instructor-training/08-motivation/).  
We mention it second bullet (Establishing norms for interaction) under "Creating A Positive Learning Environment" at the top.  Maybe here we can explicitly link to our CoC?

Our CoC is explicitly linked to in  "The Importance of Having Rules" callout about half way down.

**Comment by tracykteal** [comment]
I saw it in the Rules section. Just thought it could be mentioned at the top, since it is core to our workshops. I mentioned it when I did this section. We could leave it to individual instructors.

**Comment by karinlag** [comment]
I taught this week. As the materials are right now, I seem to recall that they come up first thing in the welcome, then in workshop introductions (IIRC), and we also mention them in the last module, the teaching practices.

**Comment by tracykteal** [comment]
OK, seems like this isn't an issue. I'll close.
