### ISSUE TITLE
Instructor training sign up form

### ISSUE THREAD

**Issue by tracykteal** [carpentries/instructor-training#547]
This isn't about the instructor training materials, but about the sign up form. We had someone bring something up about the 'obligation' checkboxes in the instructor sign up form. I created an issue for it in the Amy repo.

https://github.com/swcarpentry/amy/issues/1219

**Comment by tracykteal** [comment]
Also, if we're re-doing the gender question in our surveys, we might also consider re-doing it in the instructor sign up form as well.

**Comment by ChristinaLK** [comment]
From @karinlag's comment on the AMY issue, it sounds like this could prompt a discussion about the goals of instructor training, which should probably start at the executive/steering committee level and then trainers could be solicited for input from those groups.
