### ISSUE TITLE
K-12

### ISSUE THREAD

**Issue by aschuerch** [carpentries/instructor-training#550]
Most people at the instructor workshop (non-US) did not understand the term. Neither did I the first time I encountered it (and answered 'no' even though I did teach there). I would prefer "primary and secondary education" or "pre-university level".

**Comment by ChristinaLK** [comment]
+1 to "primary and secondary education"

**Comment by anenadic** [comment]
+1, K-12 is foreign to us in the UK, too.

**Comment by ErinBecker** [comment]
Thanks @aschuerch for catching this. I wasn't aware that wasn't a global term! I've put in a PR and am closing the issue.

**Comment by karinlag** [comment]
On that note, do we have something referring to graduate, as in for instance under/postgraduate in our material? That is also something that confuse people (speaking from experience, and still not completely steady on it).
