### ISSUE TITLE
taking over keyboard

### ISSUE THREAD

**Issue by aschuerch** [carpentries/instructor-training#551]
Preferably in the list of "Things You Shouldn’t Do in a Workshop" there should be a mention of taking over the learners keyboard as a demotivating practice

**Comment by ChristinaLK** [comment]
I strongly agree!!!!  I don't think we ever actually address this in instructor training but it's very important for both instructors + helpers.

**Comment by jttkim** [comment]
+1 from me as well. I've always asked helpers or equivalent (e.g. teaching assistants) to never type anything for students or learners. It can be demotivating and also it amounts to not using an opportunity to learn skills and habits that, over time, sink into "muscle memory" and are essential for working independently (i.e. after the workshop when the helpers aren't around anymore).

For this reason I'd additionally encourage instructors to make helpers aware in this regard, ahead of a workshop if at all possible. This is especially important where people who are new to helper roles are brought in, as it's not uncommon that genuine best intentions to help drives new helpers into grabbing the keyboard (+ mouse) from learners.

**Comment by ErinBecker** [comment]
Thanks @aschuerch and all. I strongly agree with this and was surprised to notice it isn't already listed! I've added a PR and am closing this issue.

**Comment by karinlag** [comment]
...with one caveat, if it's to fix deep weird vodoo setup stuff which is way way beyond anything and which is precluding the student from participating, I think that's acceptible. Helper should however then aim to explain what the issue was in the break.

**Comment by weaverbel** [comment]
+1 to that @karinlag because there have been 'deep voodoo' times when an attendee has actually pushed the keyboard across to me and asked me to fix the issue so they can catch up.
