### ISSUE TITLE
organise your knowledge exercise takes longer

### ISSUE THREAD

**Issue by mkuzak** [carpentries/instructor-training#552]
The firts exercise in episode 22-practices can take much longer than 10 minutes. It's an oportunity for people to review all the practicises from two days. I think it's worth leaving the time for discussions in the groups.

**Comment by karinlag** [comment]
I taught this module at Imperial College of London this week, and we didn't do the "organize your knowledge" exercise. We had at that time reached 1545, people were tired, and doing such a big task then did not seem like it would fit. I am also uncertain about how to... administer it, if that word makes sense? Anyhow, just my 2 cents.

**Comment by amyehodge** [comment]
We just did this exercise yesterday, and while people seemed tired, they very much appreciated not just sitting and listening to more talking. Some of them were literally falling asleep, and even tired exercises seemed better than no exercises at this point in the day. @karenword did an excellent job leading this piece. She may be able to advise on administering it, @karinlag .
