### ISSUE TITLE
learning posters

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#562]
Helpful reference? http://www.learningscientists.org/posters

Not sure where this would go, but it seems relevant.

**Comment by ErinBecker** [comment]
Thanks @ChristinaLK. These are nice infographics. The first four (spaced practice, retrieval practice, elaboration and interleaving) are primarily about study strategies. These four studying methods have been shown to be much more effective than the standard/default study strategies of re-reading and highlighting. They're not directly applicable to our current instructor training curriculum, but I can see these being very useful if we ended up creating a second-stage (intermediate) instructor training or were running a "Teaching Carpentries" set of workshops (both options have been discussed as long-term possibilities). 

Concrete examples are perhaps more applicable to our current materials. Concrete examples relates to what we talk about in the motivation and demotivation episode and a reference to this poster might be added there.

**Comment by ChristinaLK** [comment]
True re: studying not so much teaching.  I think I'll just close for now.
