### ISSUE TITLE
Early activities need more interaction

### ISSUE THREAD

**Issue by karenword** [carpentries/instructor-training#566]
How Learning Works: The Importance of Practice, as the first main module, is an opportunity to establish community & collaborative culture. The multiple choice activity can be extended to a explain-to-a-partner/group type thing, but even that is a little late. This could also be done in the Welcome module, e.g. having people introduce themselves to a partner then introducing their partner. These activities are already tight on time, so this may also mean trimming a bit elsewhere.

**Comment by ChristinaLK** [comment]
The mental model activity comes fairly early in that module, and I usually use that for a fairly extended discussion for exactly this reason.
