### ISSUE TITLE
github links on instructor training contributing page need updating

### ISSUE THREAD

**Issue by nkindlon** [carpentries/instructor-training#573]
Hi Everyone,
     I'm Neil Kindlon, a programmer analyst at The Jackson Laboratory in Farmington, CT, USA, and a carpentries instructor candidate currently working on the checkout certification requirements. I was reading the page on "Contributing", under instructor training, found here:
https://github.com/carpentries/instructor-training/blob/gh-pages/CONTRIBUTING.md

In the section, "How to Contribute", under item 2), the first sentence ends with the text "creating an issue", which is hyperlinked to a defunct site:
https://github.com/swcarpentry/instructor-training/issues/

Clicking on it results in a 404 error. I believe the link should point to:
 https://github.com/carpentries/instructor-training/issues/

The same is true of text in the next section, "What to contribute", where there are hyperlinks for "bug reports" and "the list of issues for this repository". 

I'm happy to make the changes and submit a pull request if folks agree that my suggested change should apply to these three hyperlinks. If not, please let me know what you'd suggest instead. Thanks, and I look forward to working with you all!
-Neil

**Comment by ErinBecker** [comment]
Thanks for catching this @nkindlon! We've moved our instructor training materials to https://github.com/carpentries/instructor-training and all of the links should be changed to direct contributors to that repo, as you noted. It would be excellent if you would be able to put in a PR to fix those links. Thanks again!

**Comment by ErinBecker** [comment]
Fixed with https://github.com/carpentries/instructor-training/pull/574
