### ISSUE TITLE
issues around worksheet in Teaching Practices

### ISSUE THREAD

**Issue by elliewix** [carpentries/instructor-training#589]
We just ran through the worksheet in the Teaching Practices episode (http://carpentries.github.io/instructor-training/files/handouts/Carpentries_teaching_practices.pdf).  

Overall positive!  They liked the summative aspect to it.

A few comments:

* Active learning isn't defined or mentioned in the lesson that I could find
* Deliberate practice only appears in the glossary 
* Many people were confused about what Practical Skills meant 

I also noticed that I don't think we explicitly talk about how to manage the wrap up.

**Comment by amyehodge** [comment]
Good points, @elliewix. I think this exercise & its worksheet could use a little more clarity.

Unless we feel that some of the phrases @elliewix mentioned above are important to incorporate into the lesson materials (I personally don't think so), then I recommend we modify the terminology on the handout. 

"Active Learning" could possibly be changed to "Student Involvement," or "Active Student Participation."
"Practical skills" actually seems like it would be subsumed by the category above -- I'm not sure how that's different.
Is "Deliberate Practice" intended to be about the learners providing feedback to themselves by doing deliberate practice? I'm not sure deliberate practice is something that happens a lot *during* a workshop, based on the definition I read.

I think we may need some clarifications of intent by the person who made the worksheet. I did really like this exercise as well (though I didn't lead it), but clarifications here could really improve this.

**Comment by kariljordan** [comment]
Deliberate practice relates to skill acquisition, but I'm not sure how much it incorporates self-reflection. I agree that we should ask the person who made the worksheet. Does anyone know who that is?

**Comment by lexnederbragt** [comment]
I think that was @tracykteal.

**Comment by tracykteal** [comment]
I did make the worksheet, but I only used it once, so I think we should use what we've learned from teaching with it to update it. I
[Carpentries_teaching_practices_filled.pdf](https://github.com/carpentries/instructor-training/files/1685802/Carpentries_teaching_practices_filled.pdf)
 put here one that is filled out to give an idea of what I was thinking of in the different categories. I'll put in a PR to add the Powerpoint file to the handouts repo, so it can be updated too.

**Comment by tracykteal** [comment]
PR is here https://github.com/carpentries/instructor-training/pull/617

**Comment by tracykteal** [comment]
I realized the 'Deliberate practice' section isn't filled out. What I had in mind here is maybe more "guided practice", the idea that they're trying something and get prompt feedback on how it went. I think there is this in workshops, because learners try the exercises and use the sticky notes to say if they got it, then they can get help from a helper if they didn't, and the instructor at the front of the room goes through the responses. But it definitely could be that this is included in other categories.

**Comment by ChristinaLK** [comment]
Does our updated version of the wrap-up address these issues?

**Comment by elliewix** [comment]
The links to the handouts on this page http://carpentries.github.io/instructor-training/24-practices/index.html are broken now.  Were these the replacements?

**Comment by ChristinaLK** [comment]
We have the handouts -- the links are just wrong.  I'll fix quick.

**Comment by ChristinaLK** [comment]
they were missing a folder.  now fixed!
