### ISSUE TITLE
providing guidance for helpers

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/instructor-training#593]
Several conversations have been raised about how we bring helpers into workshops, how we prepare them to follow our pedagogical practices and make them aware of the CoC. We should add something explicit about this to instructor training and update our template emails for helper recruitment to include this info.

**Comment by kariljordan** [comment]
Are you asking for a small task force to pull something together for review?

**Comment by ErinBecker** [comment]
For right now, I'm just putting this in as a reminder to myself to look at this next time I go through the issues (about once a week). I'll post follow-up steps here.

**Comment by DanielleQuinn** [comment]
In a recent workshop I was working with two instructors and five helpers who were not yet certified or familiar with the Carpentries pedagogical model. A few days before the workshop I pulled together what I thought were some of the most easily accessible and readily use-able pieces of the training curriculum and did a 60 minute training session.  Although I am not entirely convinced that I've necessarily picked the "best" pieces, I think that it was well received (it helped nudge several people toward applying to become instructors!) and was really helpful in putting us all into the same mindset for the workshop.

Here are the notes that I used:
https://github.com/DanielleQuinn/sc-helper-info

**Comment by mfoos** [comment]
If this goes task force, I'd like to participate!

**Comment by karinlag** [comment]
On 22.12.2017 02:55, M. Foos wrote:
> If this goes task force, I'd like to participate!
> 

May I suggest that whatever we create be added to what we already have 
for helpers in the SWC helper checklist?

https://software-carpentry.org/checklists/helper/

Not sure what the structure of websites etc is going to be after the 
merger, but I assume that these will be transferred somehow.

Karin

**Comment by brownsarahm** [comment]
This is superceded by #1072
