### ISSUE TITLE
Instructor Contribution (Instructor guide link broken?)

### ISSUE THREAD

**Issue by adityaSrik** [carpentries/instructor-training#594]
The instructor (notes) guide in the Ecology workshop lesson; which could be found at (http://www.datacarpentry.org/lessons/) in the ecology curriculum is broken? the data is not present unlike the other lessons.

The link to the page with the issue is (http://datacarpentry.github.io/ecology-workshop/guide/)

**Comment by katrinleinweber** [comment]
In other contexts, I saw `FIXME`indicating that there is no content, yet.

**Comment by ChristinaLK** [comment]
I think @katrinleinweber is right - the page is there, but there hasn't been any content added.
