### ISSUE TITLE
remove "bad" from section header in Live Coding section

### ISSUE THREAD

**Issue by elliewix** [carpentries/instructor-training#598]
I have concerns about the use of "bad" in the section header called "The Bad and the Good" of Live Coding.  The language in the pod is nice, "live coding done poorly" to take that stigma off.  I'm hesitant to call anyone or any behavior bad, particularly when the example in the video isn't "bad" but has room for improvement.

I'm just unsure what to rename the pod.  Maybe just "Compare and Contrast"?  While generic, that's kind of what they're doing.

**Comment by lexnederbragt** [comment]
+1 to renaming to 'Compare and contrast'

**Comment by anenadic** [comment]
+1 to changing the language. We have also started using "what went well" and "what can be improved on" instead of "positive" and "negative" when doing instructor training's 2x2 matrix of (content, style) x (positive, negative) comments on people's presentations.
