### ISSUE TITLE
Improve wording for screen readers accessibility

### ISSUE THREAD

**Issue by dpshelio** [carpentries/instructor-training#604]
There are some links that refers to `here` or `this website`.  That [doesn't follow good practices](https://webaccess.berkeley.edu/ask-pecan/click-here), they should be more informative.

Examples I've found so far:
- [20-carpentries](https://github.com/carpentries/instructor-training/blob/gh-pages/_episodes/20-carpentries.md]
   - If you would like to host a Software Carpentry workshop at your institution, `visit this website for more information`.
  - Policies related to instructor training and workshops for both Software Carpentry and Data Carpentry can be found `here`.

**Comment by remram44** [comment]
I'm on it with some regex trickery!

**Comment by remram44** [comment]
Thanks for the report @dpshelio, I think this is worth fixing. I reworded the links I could find over in pull request #605, don't hesitate to let me know if I forgot some or if you can improve on the wording!

**Comment by ChristinaLK** [comment]
Thanks for this @dpshelio, I've been recently trying to do this at my work, so I'm glad you picked it up in the training materials.  And thanks for the PR @remram44!
