### ISSUE TITLE
Etherpad is missing.  Should be in "How We Operate".

### ISSUE THREAD

**Issue by symulation** [carpentries/instructor-training#614]
Given the role that Etherpad plays is running Carpentry workshops there should be 5 minutes spent on it.  This should include:

1. how to make a pad
2. what pads can be used for
3. how long pads stick around

etc.

**Comment by symulation** [comment]
If people agree I'm happy to make the change and submit a pull request.

**Comment by kariljordan** [comment]
I like this idea as well. It could also be incorporated into the workshop website setup - wait, do we still have them create a workshop website? I have to look at the most current curriculum, but I like this idea.

**Comment by amyehodge** [comment]
This is definitely some information that we haven't included anywhere, but the lessons are already so packed. Maybe we could document this somewhere and write up a blog post about it, and include a reference to the documentation in the lesson materials?

**Comment by amyehodge** [comment]
@kariljordan yes, we do still have them create a workshop web site

**Comment by symulation** [comment]
Perhaps there could be a link in the lesson template to such a blog post, right where it says "FIXME" by the Etherpad line? Or just a line of instruction there (it wouldn't take much).  This might help more than just the first time instructors.

**Comment by symulation** [comment]
Adding a link in the template _plus_ putting the pad of pads in the lesson as a community connection/resource with the other pieces might be all that is needed.

**Comment by ChristinaLK** [comment]
@symulation I should have read this issue before the last one I commented on!  Definitely like the idea of having a resources *somewhere* about using the communities tools.

**Comment by kariljordan** [comment]
@symulation let me know if you're still interested in submitting a PR because I'd love to review it and help with it.

**Comment by brownsarahm** [comment]
i will work on this and #615

**Comment by brownsarahm** [comment]
@ChristinaLK are you working on this? or should I still do it?

**Comment by ChristinaLK** [comment]
You can! Let me see if @karenword or @raynamharris can merge a big PR I made that changes the content of the "how we operate" section so that you can work from what will be the updated version.
