### ISSUE TITLE
Pad of pads is missing.  Should be in "How we operate"

### ISSUE THREAD

**Issue by symulation** [carpentries/instructor-training#615]
Lots of info and connections are shared throughout but given how often that we all end up using various etherpads we should be including a link to the pad of pads.

**Comment by symulation** [comment]
If people agree I'm happy to make this change and submit a pull request.

**Comment by kariljordan** [comment]
I like the idea. I normally end up referencing the pad of pads at some point. It would be nice if it were officially in the training somewhere.

**Comment by amyehodge** [comment]
I think it's a good idea to add it in as well.

**Comment by ChristinaLK** [comment]
+1 from me

**Comment by murraycadzow** [comment]
+1 for me
