### ISSUE TITLE
Change to a section in Teaching Practices worksheet 

### ISSUE THREAD

**Issue by cderose** [carpentries/instructor-training#619]
For the digital worksheet in 'Teaching Practices,' I've been thinking about alternative presentations to the Teaching segment that has the four quadrants: Formative Assessment, Active Learning, Practical Skills, and Feedback to Learners. I recently went through the instructor training, and when my group got to this section we found the division into four separate boxes a little limiting. Something like a Venn Diagram or no boxes at all where you could more easily draw lines between activities to demonstrate scaffolding in a lesson could be helpful for thinking about the flow of activities. If there were no boxes at all, Formative Assessment, Active Learning, etc. could still be listed at the top by Teaching as things for instructors-in-training to keep in mind when considering activities.

**Comment by ChristinaLK** [comment]
Thanks for the feedback @cderose !  I can't speak to this because I haven't used the worksheet in training yet, but I'd be interested in hearing more about this from others who have used it.

**Comment by karinlag** [comment]
Personally, I'd love it if somebody could talk about it in an upcoming Discussion session, I'm not really sure of how to use this one.

**Comment by ChristinaLK** [comment]
@karinlag, noted.  I've also thought the same.  We have at least 1 other topic to line up, but will try to get this on the slate.

**Comment by ChristinaLK** [comment]
addressed in #778
