### ISSUE TITLE
Instructor Notes Accessibility SWC vs DC

### ISSUE THREAD

**Issue by sheraaron** [carpentries/instructor-training#626]
During the Instructor Discussion this morning it was discovered that accessing the Instructor Notes on the [SWC ](https://software-carpentry.org/lessons/) page is not as easy to obtain as it is on the [DC](http://www.datacarpentry.org/lessons/) page. 

For SWC you must click on the Lesson Site -> Extras (top menu) -> Instructor Notes
On DC it's listed right next to the Lesson Curriculum 

Can we make this uniform so that new instructors can go directly to the notes without having to take the extra steps?

**Comment by fmichonneau** [comment]
Should we have a "instructor guide" and a "reference" column on both pages?

**Comment by sheraaron** [comment]
I believe it would be helpful just so that it makes it easier to navigate the pages.

**Comment by fmichonneau** [comment]
I created the pull requests on both site to make them consistent (see above). This can be closed.
