### ISSUE TITLE
add link to troubleshooting

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/instructor-training#627]
This link should be included somewhere:  https://github.com/swcarpentry/workshop-template/wiki/Configuration-Problems-and-Solutions

Maybe in "Teaching practices"

**Comment by kariljordan** [comment]
I submitted a PR [here](https://github.com/carpentries/instructor-training/pull/763), but then realized @karenword had already addressed this issue.

**Comment by karenword** [comment]
Oh no! Sorry for failing to close this issue :( Thanks for the fix anyway and for the headsup @kariljordan! I'll run through now and be sure we don't have any more of these lying around.
