### ISSUE TITLE
"Adapting Challenges While Teaching" too advanced?

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/instructor-training#630]
`14-lesson-study` ends with a (new to me) section on "Adapting Challenges While Teaching". The text seems to suggest it is possible to practice on-the-fly adjusting exercises if you discover "available  exercises don’t exactly meet the needs of the learners you have in the room".

I would say that being able to do this undoubtedly would be very helpful. But given the difficulty of writing a good exercise even given plenty of time to do it, I would argue that this part is a bit too advanced for our trainees, and potentially off-putting. In addition, improvising during a workshop is tricky, as you may run into situations you did not see coming.

I have never done this 'on-the-fly' creation of exercise variants myself. Are other instructors doing this a lot?

Can this me removed, or at least not be an exercise during instructor training workshops?

**Comment by anenadic** [comment]
+1

I often struggle with this section, and there is almost never enough 
time to do the exercise. People normally feel more time is needed for 
live coding and discussions on other topics and this topic seems very 
distant and advanced.

BW,
Aleks

**Comment by ErinBecker** [comment]
+1

I also have never had time for this section.

**Comment by fmichonneau** [comment]
+1

It's exceedingly difficult to do this correctly.

**Comment by lexnederbragt** [comment]
PR submitted to remove this part.

**Comment by weaverbel** [comment]
Happy for it to go but I just did this exercise with the small group I trained yesterday and they LOVED this exercise. 

BUT the curriculum is still too full so I am happy to wave bye bye to it.

**Comment by ChristinaLK** [comment]
Can we change this to "adjusting challenges in preparation for teaching"

**Comment by ChristinaLK** [comment]
I'm going to leave this open -- I'd like to keep some sort of material about preparing challenges for teaching (or even just *selecting* challenges from a list).
