### ISSUE TITLE
illustration for fluid representation

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/instructor-training#634]
Stumbled upon this illustration from the New Yorker. I'm not sure whether we can include this in our lessons without licensing it first.

![upl_1493173172_193554](https://user-images.githubusercontent.com/5502922/36813016-0a09afa4-1ca1-11e8-90ea-f6162eb1d6e6.jpg)

**Comment by ChristinaLK** [comment]
I think this could also work for expert versus novice!

**Comment by ChristinaLK** [comment]
@fmichonneau , can you determine if we need a license for this?  Otherwise, I'll close.

**Comment by fmichonneau** [comment]
it looks like we'd need to pay to include it in the lesson and then we'd need to figure out language around the fact that it doesn't follow the CC-BY license as the rest of the lesson. Maybe add a link to it instead?

**Comment by ChristinaLK** [comment]
Link sounds good to me.  
Other opinions?  Worth adding a link, and if so, where?

**Comment by alex-konovalov** [comment]
This could also work for mental models, I think.

**Comment by LuisMossburger** [comment]
Hey guys!

Last week I finished my instructor training with @konrad and @arockenberger - in the exercise regarding fluid representation our group actually googled and the illustration in this issue really helped us understand the concept! So, as a contribution to the course material for my checkout process, I made an illustration myself - you can use it if you like (CC0 from my side, then of course the standard Carpentry License). Notice however, this is my first illustration ever and might not be the best you have seen so far ;)

The style is "flat" and "simplified", which is commonly used throughout modern websites at the moment. 

Thanks for all the good work in the Carpentries, excited to be part of it - cheers!
(The Inkscape-SVG file is in ZIP as github does not allow the filetype in this comment.)

![LC_FluidRepresentation](https://user-images.githubusercontent.com/44579990/99180969-4a62d480-272b-11eb-863d-eb44a8d725bf.png)

[LC_FluidRepresentation.zip](https://github.com/carpentries/instructor-training/files/5542065/LC_FluidRepresentation.zip)

**Comment by twitwi** [comment]
Good job, while I could do better, here are some comments:
- I think the original "pointing" gesture helps understanding the concept faster,
- we might consider what would be the most appropirate gender for the characters

**Comment by brownsarahm** [comment]
Thank you for your effort, I love the idea of adding more images to instructor training.  

However, he more abstract/ neater map made this really hard for me to figure out what it was saying.  I actually only understood this after looking at the above.  While police imagery is not ideal in many ways, it does signal that the one person is knowledgeable about the local area. 

I wonder if we could do something else to signal that one person is knowledgeable and that the other is a novice.  Maybe even text bubbles with a question/answer and the images as thought bubbles?

**Comment by LuisMossburger** [comment]
Thank you to you both for your feedback!
I tried to include all your ideas and to make the meaning of the illustration as obvious as possible, new suggestion below!

![LC_FluidRepresentation_v2](https://user-images.githubusercontent.com/44579990/101238271-6d0b5c00-36df-11eb-9fff-a6ef80dc11b9.png)

[LC_FluidRepresentation_v2.zip](https://github.com/carpentries/instructor-training/files/5646753/LC_FluidRepresentation_v2.zip)

**Comment by Denubis** [comment]
@LuisMossburger I'm not sure I see the fluid representation in this illustration. Right (instruction) versus right (orientation) doesn't seem like the sort of fluid representation we want to illustrate, where multiple terms can refer to the same thing instead of one thing referring to multiple confusing things.

I think the illustration can be quite useful though -- maybe if we swap between orienteering and landmark navigation? Maybe use the amusing https://en.wikipedia.org/wiki/Llanfairpwllgwyngyll as part of this? Maybe something like: "Well, you'll want to go to the 7-11, right, and then go over to the big tree near the church and then west (but not really, more northish) and then right, right?"

**Comment by LuisMossburger** [comment]
@Denubis On second thought, I agree with you here. I remember the way we actually understood the concept was knowing that some people are familiar with route descriptions by directions and numbers, while others focus on waymarks to move forward.
So, I would propose a third option with two pictures that could be shown one after another and "tell the story" better, I hope.

![LC_FluidRepresentation_v3_directions](https://user-images.githubusercontent.com/44579990/101529562-0319dd80-3991-11eb-905a-98b4b04214d9.png)
![LC_FluidRepresentation_v3_waymarks](https://user-images.githubusercontent.com/44579990/101529569-057c3780-3991-11eb-9f86-e4fee7679d03.png)


[LC_FluidRepresentation_v3.zip](https://github.com/carpentries/instructor-training/files/5661298/LC_FluidRepresentation_v3.zip)

**Comment by Denubis** [comment]
This seems more like expert blind spot than fluid. Perhaps if we have two people giving directions in your two styles, with the one person confused? It's not about one set of concepts being able to understand. It's that both people are describing the same thing with entirely different conceptual representations. Cause the issue here is that purple shirt is hearing "go through the dpeartment store/500m west/down the road with that lovely tree/300ft to your right" and is hopelessly confused because the languages are swapping between registers.

**Comment by Denubis** [comment]
Maybe the narrative is asking for help twice. So the first time the purple-shirt gets orienteering directions, and the second, they get landmark and are hopelessly confused? 

Or it's "How do you get to Llanfair­pwllgwyngyll­gogery­chwyrn­drobwll­llan­tysilio­gogo­goch?" and two people are trying to explain the same thing using completely different systems? Neither of which is wrong, but they don't combine well... (And maybe the puzzlement is the recipient trying to combine concepts from both without knowing how they can be replaced?)

**Comment by LuisMossburger** [comment]
To be honest, I feel that the introduction of a third person would not make this clearer. The glossary says fluid representation is "The ability to move quickly between different models of a problem."[1], the respective section in the training "Two ways of thinking about a problem will seem interchangable to an expert, but will not seem that way to a novice."[2]. It seems to me that the main focus here lies on the expert being able to switch, the novice not - not that different experts have different mental models - @konrad & @arockenberger , please correct me if I understood that wrong!

How about changing the first bubble to mix numbers, arrows and waymarks and then in the second picture only the waymark? I also do not think that an illustration (that I am able to create) alone can explain the concept of fluid illustration, there needs to be verbal description along with it..

[1] https://github.com/carpentries/instructor-training/blob/d04e15e2a72f425d6d046590abd5ccbc8ede4f44/_extras/glossary.md 
[2] https://carpentries.github.io/instructor-training/03-expertise/index.html

So, my final proposal for a two picture "comic" to explain the difficulty of switching between different concepts - not standalone but with the need for a verbal explanation along with it. Maybe it would be a good idea to do a "poll" here? I do not consist on these pictures being used, so if we end up with the feedback that the illustrations make it more complex than verbal description only that's completely fine with me!

![LC_FluidRepresentation_v3_FluidDirections](https://user-images.githubusercontent.com/44579990/101588063-d217c800-39e5-11eb-8dfe-ef5277eee2e8.png)
![LC_FluidRepresentation_v3_WaymarksOnly](https://user-images.githubusercontent.com/44579990/101588069-d512b880-39e5-11eb-9a7e-c8deb7f20a62.png)
[LC_FluidRepresentation_v4.zip](https://github.com/carpentries/instructor-training/files/5663632/LC_FluidRepresentation_v4.zip)
