### ISSUE TITLE
standardize use of Carpentry/Carpentries/The Carpentries

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/instructor-training#639]
Following the merger, it would be good to go through the material and define editorial rules to be consistent in our use of singular, plural and capitalized forms of "The Carpentries" and derivatives.

**Comment by rgaiacs** [comment]
@fmichonneau I created https://github.com/swcarpentry/lesson-example/issues/183. For the moment, I'm keeping a list of editorial rules on http://swcarpentry.github.io/lesson-example/06-style-guide/index.html.

**Comment by remram44** [comment]
Is this issue about describing/applying the rules? Or are they still to be determined?

**Comment by ChristinaLK** [comment]
@ErinBecker @tracykteal can you chime in here?  Is there a chosen consistent style + we just need to apply?

**Comment by tracykteal** [comment]
The Carpentries is the name of the project. 

If we're referring to multiple lesson sets, e.g. Software Carpentry, Data Carpentry and Library Carpentry, then it would be Carpentries, as in multiple lesson Carpentries. 

Example: We see that The Carpentries have an instructor training program that prepares people to teach Carpentries lessons - Software Carpentry, Data Carpentry and Library Carpentry.

Does that help? Suggestions for better clarity are welcome.

**Comment by raynamharris** [comment]
I've hear two fans of the organization refect to certified instructors as "Carpenters", and I quite like it. Is that an official term that we use?

**Comment by ChristinaLK** [comment]
Cool!  I think this would be a good bug bbq project -- different people could go through different sections of the material + sanity check for consistency.

**Comment by maneesha** [comment]
I also want to know if "The Carpentries" as the whole project is singular or plural.  
Is it then different when we are talking about "The Carpentries" as multiple lessons?

"The Carpentries is..."  or "The Carpentries are..."

**Comment by weaverbel** [comment]
The Carpentries is a single (singular) entity. However because "The
Carpentries is ... " or "The Carpentries does ... " SOUND wrong, I usually
reword sentences to avoid that kind of construction.

Belinda Weaver
Community and Communications Lead
The Carpentries
e: bweaver@carpentries.org | p: +61 408 841 882 | t: @cloudaus

**Comment by weaverbel** [comment]
I use 'Carpenters' a lot too @raynamharris but it is not an official term.

**Comment by amyehodge** [comment]
This construction doesn’t bother me at all, but then I’m used to referring to Stanford Libraries as singular, while referring to multiple individual branches as libraries is plural. Same exact issue as with the Carpentries.

~ Amy

Amy E. Hodge, PhD
Science Data Librarian
amyhodge@stanford.edu<mailto:amyhodge@stanford.edu>
650.556.5194
[cid:image001.png@01D3C154.441B9BB0] orcid.org/0000-0002-5902-3077<https://orcid.org/0000-0002-5902-3077>

Data Management Services
Branner Earth Sciences Library, 212 Mitchell
397 Panama Mall; MC 2211
Stanford University
Stanford, CA 94305

**Comment by MelliGyal** [comment]
It would be better that instructor training commence early in the year

**Comment by raynamharris** [comment]
I've suggested some updates to the "The Carpentries" episode here https://github.com/carpentries/instructor-training/pull/814. I've attempted to use language taken from blog posts written by staff, but feel free to change anything that is incorrect.

**Comment by raynamharris** [comment]
@fmichonneau. I went through and changes all instances of singular "Carpentry" to "Carpentries" and added Library Carpentry where appropriate. However, I am certain I left "the" lower case in a few instances. I saw some instance of lowercase "the" in the handbook, so I left it lower case here. I'm happy to go back through an give al the lessons another once over if you think its necessary.

**Comment by fmichonneau** [comment]
Thanks for doing this @raynamharris! I believe that we favor "The Carpentries" (see draft style guide here: https://docs.google.com/document/d/10KutjajR-5RJfPAF8UQlxzcd8tx4PNFXH0acDFD2dBs/edit)

**Comment by karenword** [comment]
With all due respect to the style guide, I have found that I just don't like the capital "The." Because I'm not seeing it heavily in use (e.g. Carpentries.org splash page does not use it), I'm suspecting others feel the same, and we may want to consider adjusting our style guide to reflect practical usage. @fmichonneau do you think it's ok to let this rest for a while as-is?

**Comment by gvwilson** [comment]
I agree with @karenword: "the biggest success of the Carpentries" reads a lot better to me than "the biggest success of The Carpentries".

**Comment by fmichonneau** [comment]
I'm happy to leave it at "the Carpentries", I was simply relaying what was in the style guide.

**Comment by raynamharris** [comment]
Excellent! Thanks, @fmichonneau. I that case, I think we are good to close this :)
