### ISSUE TITLE
"Follow Code of Conduct" in Lesson 20: How We Operate?

### ISSUE THREAD

**Issue by symulation** [carpentries/instructor-training#649]
Lesson 20 currently says:

**Using the Names**
The names “Software Carpentry” and “Data Carpentry” and their respective logos are all trademarked. You may only call a workshop a Software Carpentry or Data Carpentry workshop if:

- it covers the core topics,
- at least one instructor is certified,
- you run our standardized pre- and post-workshop assessments and ensure everyone participates, and
- you send us summary information about attendees (at a minimum, the number of people who attended).

Should there be a fifth point:

- code of conduct is followed

?

**Comment by weaverbel** [comment]
+1 to that suggestion ! @symulation

**Comment by lexnederbragt** [comment]
+1 from me too, but I suggest a slight rephrase. "Is followed" can only be established after the workshop. I'm not a native English speaker, but would "code of conduct is applied" work better?

**Comment by sheraaron** [comment]
+1 agree with @lexnederbragt

**Comment by ChristinaLK** [comment]
+1 but also should probably be confirmed by executive council + director.

**Comment by brownsarahm** [comment]
per the [workshop website](https://static.carpentries.org/workshops/) this is true and can be added or we can refer only to that page instead of repeating as per #1103

**Comment by karenword** [comment]
Recent updates (#1268) remove this text and point at carpentries.org (where this and everything else is correctly outlined). Thanks all!
