### ISSUE TITLE
GitHub labels pilot

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/instructor-training#651]
I just added the prototype github labels to the repository. Please let me know how they work for you and any feedback you might have. For reference the current definitions of the labels are in Carpentries handbook: http://docs.carpentries.org/topic_folders/lesson_development/github_labels.html

We are going to test them first in a few repositories including this one until the end of the month, and we are planning to have a revised version of these labels ready in time for the Bug BBQ on April 12-13.

To test these labels, it would be great if you could assign at least 2 labels to each issue: one in the "status" category, and on the "type" category. Depending on the context, you may also want to add the "bug-bbq", the "good first issue" or the "high-priority" labels.

I'd really like your feedback on how well these labels capture the type of issues that are currently in the repository, or that we have or can receive. If you feel that some labels don't capture the nature of the issue, or if the meaning of the labels is too unclear to make a call, I'd really like to hear about it.

There is also a little more information about these labels in the proposal: https://docs.google.com/document/d/1b3nIZ6N4IHY24JmLNQ5rkwUACEVS9Hls3auzZD7zHqk/edit

Feel free to ping me on Slack, by email or here if you have any questions or with your comments/feedback. Thanks!

**Comment by karenword** [comment]
Thanks @fmichonneau -- we'll give it a try!

**Comment by remram44** [comment]
I see that both old and [new labels are set](https://github.com/carpentries/instructor-training/labels). That's somewhat confusing, but that also means you will have to remove the old ones and add the new ones to all issues, whereas they would have stayed set if you had just renamed them.

On the labels themselves, I see a couple issues:
* `status:help-wanted` means it won't show up for people looking for GitHub's default `help wanted` label
* There is no point having `status:completed` when you can just close the issue. I think the feedback on the Google Doc was pretty clear we didn't want this, I'm surprised you added it against our will
* `status:need-contributor` and `status:help-wanted` are duplicates
* The `type:teaching-example` is a very weird ideas. Filing PRs that are not meant to be merged?

Overall I think there might be too many labels. I'm not sure we need to categorize issues between "typo", "formatting", "enhancement", "clarification". Contributors are very unlikely to search for a specific type they want to address anyway. Do we need to add this classification burden on maintainers?

Thanks

**Comment by ChristinaLK** [comment]
Thanks @fmichonneau!  We'll see how it goes. :) 
Is there a process for giving feedback on the labels, if we run into some of @remram44's or our own concerns?

**Comment by fmichonneau** [comment]
@remram44  Yes, at this time both old and new labels are set. As you mentioned, deleting the old set of labels before deploying the new set would have meant that previous work put into tagging the issues would have been lost. There isn't a one-to-one correspondence between old and new set, so renaming wasn't an option. The [label overview](https://github.com/carpentries/instructor-training/labels) makes it relatively clear which labels are new given that they have a short description (which the old labels don't have).

As mentioned in today's call, we might rename the "status:help-wanted" to something that signals that this issue needs expertise. No decision has been made on this, and I also agree with your point that this can be too vague to be useful. Regarding GitHub's default, we'll have "good first issue".

I added a note in the google doc proposal to explain why having "status:completed" is different from relying on merged and closed issues. Let me know what you think.

We've gotten several teaching examples pull requests for instance: https://github.com/datacarpentry/R-ecology-lesson/pull/342 I think they are useful when revamping the content of the lesson to see how other Instructors approach the lesson. Adding the label and closing seems reasonable to me.

As for the number of labels, several maintainers echoed Naupaka's comment that it helps them process the nature of the issue. Being able to categorize issues was requested by many maintainers in the interviews Erin conducted a few months ago. I think finding the right balance to make these labels useful to both maintainers and contributors will take a few iterations.

@ChristinaLK You can add comments here or on the Google doc: https://docs.google.com/document/d/1b3nIZ6N4IHY24JmLNQ5rkwUACEVS9Hls3auzZD7zHqk

**Comment by karenword** [comment]
It would be useful to have a label for items that, if changed, would require associated changes to be propagated to other materials. In the case of this curriculum this would be mainly the Etherpad and/or Google Doc templates. However, this could also include changes to data files etc. more relevant to other curricula.

**Comment by katrinleinweber** [comment]
That use-case can also be covered by adding checkboxes to the original post of an issue. Like:

- [ ] update pad... with ...

It's visible then on the issue overview.

**Comment by fmichonneau** [comment]
The main purpose is to help maintainers and contributors. The type and the status of the issue are useful for both, and for people within the community to step in when needed (e.g., `status:refer to cac`). We might derive statistics on them in the future, but it's not implemented yet. 

I'm sorry you feel that I'm "charging ahead without any direction" given that:

- I incorporated feedback from the community including yours (e.g.;  I removed the `completed` label) in the [labels that are currently in use](https://docs.carpentries.org/topic_folders/maintainers/github_labels.html)
- Most of the feedback we have gotten on the labels has been positive.

**Comment by remram44** [comment]
Thanks for clarifying the purpose.

Apologies for the harsh words, I did not know [an update](https://github.com/carpentries/handbook/pull/169) had been made at all. This definitely looks better.

I see that a CSV file is included, is there an easy way to create labels in a repository from it? I am mostly concerned about [datacarpentry/sql-ecology-lesson/labels](https://github.com/datacarpentry/sql-ecology-lesson/labels) which has very unusual labels.
