### ISSUE TITLE
How long does the post-training survey take?

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#653]
I was just looking at the post survey with @sheraaron and noticed the following:

On this page:
http://carpentries.github.io/instructor-training/23-checkout/

it says:

> Assessment is very important to us! Please take 5 minutes to complete this five-minute post-workshop survey.
> This exercise should take 10 minutes.
> 

How long are we suggesting the survey takes?

**Comment by ChristinaLK** [comment]
Should be 5 minutes all around, I think.
