### ISSUE TITLE
How do you pronounce "João"?

### ISSUE THREAD

**Issue by arokem** [carpentries/instructor-training#655]
It's in the learner profile example in the beginning of episode 14. I always stumble on it, because I have no idea how I am supposed to pronounce it. I have been tempted to use "John" instead.

**Comment by weaverbel** [comment]
Let's ask @rgaiacs ! He will know how to pronounce a Portuguese name.

**Comment by arokem** [comment]
This helped: https://www.youtube.com/watch?v=_fOndVOl5SE

I'll just be thinking "jew - ow"

**Comment by weaverbel** [comment]
I think it is more "zhew-ow" - i.e. it is more a soft j than a hard one

**Comment by weaverbel** [comment]
But good to know you can get these tips online @arokem

**Comment by arokem** [comment]
Yeah - we truly live in an age of wonders.
