### ISSUE TITLE
Including demo rubric in Live Coding lesson

### ISSUE THREAD

**Issue by karenword** [carpentries/instructor-training#657]
The rubric that is provided to Trainers to evaluate checkout demonstrations isn't provided to learners to evaluate each other. Is there any reason for this, or should we add it to the Live Coding lesson?
https://github.com/carpentries/instructor-training/blob/gh-pages/files/teaching-demo-rubric.md

**Comment by lexnederbragt** [comment]
There is no reason not to add it. +1 to adding from me.
