### ISSUE TITLE
Local Code of Conduct & Mandated Reporters

### ISSUE THREAD

**Issue by PLNReynolds** [carpentries/instructor-training#659]
Instructors should be made aware to verify their host institution's code of conduct (as well as become familiar with the Carpentry Code of Conduct). Designating "reporters" - people participants can talk to with potential issues (including instructors/helpers and participants or hosts) - but it is also important for learners to know if any of them are "mandated reporters" (required by their institution to report).

**Comment by ChristinaLK** [comment]
Potential PR: add to section about introductions (along w/ text in issue #645)

**Comment by karinlag** [comment]
@PLNReynolds I get the feeling there's some background here that I'm not familiar with. If so, could you possibly expand? I have never encountered or heard of learners being mandated to report anything to anybody...

**Comment by PLNReynolds** [comment]
Hi Karin,

This came up at the instructor training session Karen Word (cc’d here) led at UC Davis the past two days. Karen asked me to file this as an issue for adding a line to the instructor curricula: 1) different universities, institutions, etc. may have their own codes of conduct that instructors should be aware of and make the learners aware of (although I doubt that they would differ greatly from that of the Carpentries’ code.). 2) learners should be made aware if of how raising an issue may be reported at the local level.

More detail: When Titus Brown led a workshop here recently he used the SWC Code of Conduct and designated a few people as whom learners could go to with any issues – himself, an ‘external’ (non SWC, non UC Davis person) and myself. That gave a nice balance of genders and roles for learners to be able to talk to regarding any issues. But, there was one important fact that he remembered to say which I thought was very important for the learners to know - since both Titus and I work for UC Davis with specific job titles we are considered ‘mandated reporters’ – if issues arise (sexual harassment, etc.) on the UC Davis campus or at a UC Davis affiliated event we are required to take action by reporting it to the university even if the person telling it to us doesn’t want us to report it.

Karen – please let me know if I’m forgetting anything or not explaining this well.

~Pamela

**Comment by karenword** [comment]
Thanks @PLNReynolds -- this is a very clear explanation of the things we discussed. I think especially the mandatory reporter issue is an important one for us to highlight (and explain!) precisely because many if not most are probably unaware that this is a thing.

**Comment by ChristinaLK** [comment]
Agree w/ @karenword -- I would never have thought of this (because we aren't mandated to report at UW Madison, if I remember correctly), but that may not be the case everywhere and it's important to communicate.

**Comment by karinlag** [comment]
@PLNReynolds Thanks for the explanation, this helps clarify things indeed. I would never have thought about people being mandatory reporters, although it kind of is obvious that employees would be obliged to report things when I actually stopped to think of it.

**Comment by ChristinaLK** [comment]
I'm going to add this for the October 2018 release.
