### ISSUE TITLE
Permission to use lunar baboon cartoon?

### ISSUE THREAD

**Issue by gvwilson** [carpentries/instructor-training#672]
Do we have permission from the creator to include <http://www.lunarbaboon.com/comics/feedback.html> in Episode 11 (as opposed to linking to it)? We obtained that permission for the DeathBulge cartoon.

**Comment by ChristinaLK** [comment]
Agreed.  Whoever chooses to do this, please comment on this thread, so that we don't email the author several times.

**Comment by ChristinaLK** [comment]
I guess that will be me.

**Comment by karenword** [comment]
@ChristinaLK can you verify that this is done and we an close this issue?

**Comment by ChristinaLK** [comment]
I don't think I ever heard back from the person. :P

To be safe, we should probably link instead of embed.
