### ISSUE TITLE
online listing of upcoming workshops

### ISSUE THREAD

**Issue by raynamharris** [carpentries/instructor-training#673]
Discussion point, ht https://swcarpentry.slack.com/archives/C03LE48AY/p1523817601000052
Should we include a list of the upcoming instructor training workshop on the instructor training website? 

I would like to see a calendar feature on the website, and I don't have the expertise to implement this, but this feature do exist on the SWC and DC homepages, so it is feasible.

**Comment by ChristinaLK** [comment]
Training is a bit different than workshops in this way because there is an application/invitation process instead of just registering.  If we include a list, we need to make it *abundantly* clear that people can't just show up, and provide pathways for how they can access training if they're interested.

**Comment by raynamharris** [comment]
So, maybe there is semi-private or less public place where we could easily view all the upcoming workshops so that instructor trainers and maintainers are easily in the know about upcoming events. Or, is that place AMY and everyone has access?

**Comment by karenword** [comment]
What we currently have in the curriculum is this page: http://carpentries.github.io/instructor-training/training_calendar/ but it only has the 'when' not the where, and doesn't include dates assigned for locally-organized events. Trainers can currently view the detailed schedule in the same spreadsheet where we enter our availability -- @maneesha creates a new tab in that spreadsheet with the schedule once it's created.

**Comment by ChristinaLK** [comment]
Can we close this?

**Comment by maneesha** [comment]
Yes we can close.  Training events are intentionally less transparent than our regular workshops since they are for members only or by application only.
