### ISSUE TITLE
The Great Slide Issue

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#680]
This has come up multiple times -- how to use slides in instructor training.

**Comment by laufers** [comment]
One point to consider is to have the deck as part of the materials, keeping a format that promotes the Foundation rather than having a page of the points that could be turned into slides. It will keep content on point that the group has vetted. This way it keeps from having us upload our individual slide decks and having a large number of differing formats of slides.

**Comment by gvwilson** [comment]
A slide deck full of diagrams, cartoons, etc. (but sans text) would be useful.

**Comment by ChristinaLK** [comment]
There is already jekyll-y code to do this (or was at one point) to produce the figures + overview pages for the lessons.  Would need to be translated into something like deck.js, I think?

Before diving into the technical implementation, can I get more thoughts on pedagogical value?  So far I've heard: 
- give people something to look at besides you online (pro)
- show learning objectives up front (pro)
- people can get distracted if you skip something (con)

More pro/con?  I don't think it will change whether or not we make slides, but will help us provide recommendations about when/how to use them.

**Comment by maneesha** [comment]
Some things to consider (as discussed on today's call)
* When do we use slides?
* Where do the slides live?
* What do the slides contain?
* Do we have someone with the skills to autogenerate slides based on our lessons?

**Comment by elliewix** [comment]
To add to the images/diagrams, it would be great to add activity directions for (at least) the most complex activities.  We have a hard time reciting them to participants in a way that people can remember.

**Comment by ChristinaLK** [comment]
We now have a folder where people can dump the slides that they've used before: 
https://drive.google.com/drive/folders/10ncHtw4ZtNZD0ozW0rG5C-Q4yFetRY1t

**Comment by ChristinaLK** [comment]
Next up: recommendations for how to use slides + a scripted/automated solution.

If anyone wants to write up the do's/don'ts of using slides, please feel free!

**Comment by davis68** [comment]
I find it useful not to have scripted slides, but a collection of images I can refer to at need (like the roadmap ones I just posted to that folder).  This lets the discussion evolve organically per the local event needs.

**Comment by kariljordan** [comment]
+1 to the collection of images. I use images for:

- Concept Maps, although the one in the instructor training is actually confusing to me.
- Faded examples
- Teach most useful first
- Feedback is hard
- Learner profiles
- Top 10 tips for live coding in a workshop
- [Carpentries History](https://carpentries.github.io/instructor-training/20-carpentries/)

**Comment by ChristinaLK** [comment]
Comments from @raynamharris : 
- slides were a big issue in a hybrid training (online + in-room)
- everyone in the room thought that we teach w/ slides, gives the impression that we find the way 
- people look at the etherpad more, can teach effectively without them (just occasionally bring up images)

@mkuzak 
- don't want to use slides (except for showing a few images)
- risk for online training is that they only see slides and not you, you lose contact with trainer

@elliewix 
- use for personal use to keep self on track

@orchid00 : if you did use them, when?
- @mkuzak : using images, exercise (can also use Google Doc for this)
- @karinlag : concept maps
- @kariljordan : concept maps, teach useful thing first, carpentries history --> usually use personal links to the images and then go back to the etherpad.
- @_christinaLK : introduction
- @alex-konovalov : exercises

**Comment by raynamharris** [comment]
I'm going to attempt to incorporate this discussion of "pros, cons, and tips" into the section called "Using slides" in the instructor notes in https://github.com/carpentries/instructor-training/pull/809

**Comment by raynamharris** [comment]
Closed with the merging of #809. Feel free to bring up the issue again later or add additional comments about using slides to the instructor notes section :)
