### ISSUE TITLE
remove exercise where you create a website

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#681]
takes a lot of time, variable experience, can be done in other ways (mentoring)

**Comment by karinlag** [comment]
Could I suggest maybe having this as a once-a-month recurring subject at a mentoring session? I know this is not something this committee controls, but maybe we could suggest it?

**Comment by arokem** [comment]
I am -1 to removing this exercise.

What Lex describes sounds a lot like another instructor training event.

In my opinion, the cost in time and effort of organizing these additional
events would exceed the benefit you would get from removing the exercise
from the curriculum.

I've found this exercise to be a welcome break in the curriculum for some
-- some participants take this is an opportunity to finally do something
with their computers, after all the talking and teaching.

**Comment by ChristinaLK** [comment]
We've had a lot of mixed opinions so will probably leave it for now.  Ideally, we would mark this as "skip at your discretion" for the trainer, but we don't have a nice way to do that yet, so it'll stay the way it is.
