### ISSUE TITLE
Spelling mistake in the Rubric

### ISSUE THREAD

**Issue by wgriffa** [carpentries/instructor-training#687]
Hi I noticed a spelling mistake in https://github.com/carpentries/instructor-training/blob/gh-pages/files/teaching-demo-rubric.md

In the, "Negative Content" section on the third line the work "factual" is misspelled.

Walter G.

**Comment by arokem** [comment]
Thanks for pointing this out! Fixed in https://github.com/carpentries/instructor-training/pull/688
