### ISSUE TITLE
some ideas from incident response training into curriculum

### ISSUE THREAD

**Issue by tracykteal** [carpentries/instructor-training#690]
The Code of Conduct committee went through incident response training, and some general guidelines. We could add some things from that training to the CoC section of instructor training.

**Comment by raynamharris** [comment]
I was thinking writing up the training as the blog post rather than turning it into something we could teach in less time, somehow squeezed into an already full curriculum.

We could turn the blog into some sort of recommended reading for hosts and instructors.

**Comment by karenword** [comment]
+1 to a blog post!

**Comment by karinlag** [comment]
Maybe we could have a section of "Extras" in the IT materials that refer 
to selected blog posts? This one could then be one of these, and I'm 
willing to bet we have more that would be useful for people to read.

Karin

**Comment by kariljordan** [comment]
I'm a fan of @karinlag's idea! I agree that the curriculum is already super full, but we need to somehow have supplementary information included.

**Comment by raynamharris** [comment]
I thought there used to be a page of like 100 recommended books and papers... We could do something similar, as its own webpage in the extras section

**Comment by tracykteal** [comment]
This is all great! Everyone is right that instructor training is already really full. Maybe rather than putting this into instructor training materials, we could add things like LASER and RACING to the handbook in the CoC section. Then link to them from the instructor training materials for people to reference if they want more information on CoC enforcement. I know this is a question that comes up, and then we could have something to point people towards. 

A blog post about incident response training would also be great and could reference those things in the handbook for people who want more information.

**Comment by kariljordan** [comment]
Even better idea @tracykteal! That sounds fantastic.

@raynamharris if you need help with the blog post once it's drafted please let me know.

@karinlag let me know if you want to tackle adding LASER and RACING to the handbook.

**Comment by ChristinaLK** [comment]
+1 to adding to the handbook, since I think information that's useful for all instructors should go there.

**Comment by ChristinaLK** [comment]
Hi all - can I close this issue, since it's more for the handbook.  Is there anything from this discussion that *will* be useful for instructor training?

Will close in a week or so if I don't hear anything.

**Comment by kariljordan** [comment]
I'm fine with closing

**Comment by karinlag** [comment]
I am wondering if some instructors, especially new instructors, might feel uncertain about to what extent they have the authority to enforce the CoC then and there if something happpens in a workshop. Maybe that would be something we should adress in the curriculum somehow?

**Comment by ChristinaLK** [comment]
I'm actually going to leave this open -- I'm warming to the idea of having more "extras" pages as reference...
