### ISSUE TITLE
Add helpers 

### ISSUE THREAD

**Issue by sstevens2** [carpentries/instructor-training#694]
https://carpentries.github.io/instructor-training/20-carpentries/

I've been browsing the websites and instructor lessons for some statements about why we have helpers and how useful they are and noticed that helpers are missing from the page linked above.  I could make a PR if you'd like?

**Comment by ChristinaLK** [comment]
Thanks Sarah!  Hold that thought because that page may be changing soon -- once I've merged those changes, we'll see where we should put the helpers in.

**Comment by ChristinaLK** [comment]
We're now linking to this page on the Carpentries website: 
http://static.carpentries.org/community/

A PR there adding helpers would be great!
