### ISSUE TITLE
What does this sentence mean?

### ISSUE THREAD

**Issue by arokem** [carpentries/instructor-training#696]
In episode 03 (expertise):

"Believing that something will be hard to learn is a self-fulfilling prophecy. This is why it’s important not to say that something is easy: if someone who has been told that tries it, and it doesn’t work, they are more likely to become discouraged."

I don't understand how the first sentence relates to the second sentence here. The first one seems to imply that we should tell learners that learning what we are teaching them is not hard. The second sentence, on the other hand, seems to suggest that we shouldn't tell them that it's easy, because then they will be discouraged. Am I misreading this as a contradiction? Is there any empirical evidence either way?

Thanks!

**Comment by vahtras** [comment]
I agree totally that it is a contradiction. The second part relates to
Gregs "Avoid the j-word"-rule. Phrases like "You just", or "You can
easily..." are  demotivating if something does not work easily the first
time.

/Olav

**Comment by katrinleinweber** [comment]
Maybe both were intended as advice to avoid extreme messages ("too hard" and "that's easy"). If so I agree that the section could be made a bit more implicit.

**Comment by arokem** [comment]
Just to see that I understand the original intention, would this work?

"It is important not to say that something is easy to learn: if someone who has been told that tries it, and it doesn’t work, they are more likely to become discouraged. This is because this experience -- that something is harder to learn than expected -- can become a self-fulfilling prophecy."

**Comment by ChristinaLK** [comment]
I think the meaning is hidden in the following paragraph: 

> The real problem is that every such failure reinforces the belief that computing is hard, and that they’d have a better chance of making next Thursday’s conference submission deadline if they kept doing things the way they always have. 

So it might be more accurate to say that 
"Believing that something will be hard to learn is a self-fulfilling prophecy.  Researchers already believe that computing is hard, a belief that exacerbated by "experts" telling them that things should be easy when, in the researcher's experience, they're not."  

Maybe?  I'd welcome other opinions as well.

**Comment by arokem** [comment]
Yeah - that makes sense to me!
