### ISSUE TITLE
surveys on training website

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#698]
Can we include the training pre/post surveys on the website (just like they are for our regular workshops)? 

I don't know how to make the slug tag on to the end of the survey url, but that functionality exists in the regular workshop template and we should add that here as well.

I would also like to see the survey collector links updated to be a meaningful name rather than the current code. (I can take care of this part)

**Comment by maneesha** [comment]
Meaningful names:
https://www.surveymonkey.com/r/instructor_training_pre_survey?workshop_id=[workshop_id_value]
https://www.surveymonkey.com/r/instructor_training_post_survey?workshop_id=[workshop_id_value]

**Comment by maneesha** [comment]
I have this same issue in two places
https://github.com/carpentries/training-template/issues/24

**Comment by fmichonneau** [comment]
closed in favor of carpentries/styles#332
