### ISSUE TITLE
Create a Library Carpentry tag

### ISSUE THREAD

**Issue by dheles** [carpentries/instructor-training#703]
One of the ideas that came from discussion in the Library Carpentry Onboarding session @ #CarpentryCon was that it might be useful to have an issue label for Library Carpentry. It could be used to find issues relating to edits that incorporate LC-related language, etc.

**Comment by ChristinaLK** [comment]
@fmichonneau?

**Comment by fmichonneau** [comment]
no problem on my end for you to create additional labels if it makes your workflow easier.

**Comment by raynamharris** [comment]
I created a tag. It's not part of the whole system that @fmichonneau created for the other repos, but it may not be necessary for an LC specific label to be used in every repository.
