### ISSUE TITLE
merge/link/relocate handbook material as appropriate

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#711]
https://github.com/carpentries/handbook/pull/222

**Comment by ChristinaLK** [comment]
In particular: 
- preparing to teach?
- Code of Conduct stuff?

**Comment by ChristinaLK** [comment]
* also, how to contribute to lessons / use GitHub (if that material is there)

**Comment by brownsarahm** [comment]
I think this is addressed through other issues at this point, so I'm closing this one.
