### ISSUE TITLE
favicon is broken

### ISSUE THREAD

**Issue by remram44** [carpentries/instructor-training#715]
It links to `/favicon-swc.ico` instead of `favicon-swc.ico`. I'm not fixing because it looks like the template needs to be updated (should there be a favicon for carpentries?)

**Comment by ChristinaLK** [comment]
Yes, this sounds like a carpentries/styles question.  I think we use the base template.

**Comment by maneesha** [comment]
This is defined in `instructor-training/_layouts/base.html`
However it is defined as a conditional based on the Carpentry type being LC, SWC, or DC.  I don't know if fixing it is as simple as replacing the conditional with an absolute, or if there are any other changes required.

We have The Carpentries logo as a favicon [here](https://github.com/carpentries/handbook/tree/master/img) that we can grab the image file from.

**Comment by fmichonneau** [comment]
this has been fixed in the styles repo (https://github.com/carpentries/styles/pull/250), but the latest version hasn't made its way to this repository yet. A release is planned soon, and this repository will be updated.

**Comment by remram44** [comment]
A "cp" category. Perfect! I thought something like that might be the right fix.

Going to close this since I'm sure the update will happen soon enough.
