### ISSUE TITLE
Improvement: Instructor training Lessons 19 & 20

### ISSUE THREAD

**Issue by jananiravi** [carpentries/instructor-training#726]
Hi,
I recently (June 12–13, 2018) attended the Software/Data Carpentry Instructor training workshop at MSU hosted by @sheraaron and Rob Davey. It was most helpful to get me started.

Quick feedback regarding [Lesson 20: How We Operate](https://carpentries.github.io/instructor-training/20-carpentries/) and [Lesson 19: Introductions](https://carpentries.github.io/instructor-training/19-introductions/):
There was no sufficient time to set up a new GitHub workshop page unlike some of the earlier sessions on Day 1, which were much simpler but much >> time was dedicated to it. It would also be most helpful if significantly more time was allotted for Day 2's afternoon session where workshop preparation and workshop set-up were given priority since those were the most crucial lessons. Repeated sessions from explaining a select Software/Data lesson could be cut down to make time for this.

Thanks again for a great workshop! Look forward to hosting one soon.

**Comment by ChristinaLK** [comment]
Thanks @jananiravi!  We've had multiple discussions about whether to keep the Github workshop page exercise (because it can take a long time) -- I think you're right that, if kept, we need to shuffle timing.  

Would you have found it useful to create the workshop website, if there was enough time?

**Comment by jananiravi** [comment]
Thanks for your response, @ChristinaLK. I understand that it may take a considerable amount of time but we could potentially get some 'borrowed time' from easier tasks.
And yes, I think creating the website would help in reconciling all that has been taught in the workshop. Each of the customizations (changes) that need to be made to the website would reveal important elements of the workshop that needs deliberate thought and planning. So, I think designing the website would help bring together technical and non-technical aspects of the 2-day workshop, especially given that it's towards the end of day #2.

**Comment by karenword** [comment]
This issue is addressed in time reallocations with coming updates, currently in our sandbox repository: https://data-lessons.github.io/instructor-training/
