### ISSUE TITLE
Improvement: "The Carpentries: Workshop Introductions" practice your introduction section

### ISSUE THREAD

**Issue by bchen2** [carpentries/instructor-training#727]
Hi, I attended the Software Carpentry Instructor training workshop at Space Telescope Science Institute on June 12-13 by @sheraaron and Rob Davey. 

The course is well designed, however, I have a little suggestion on the "practice your introduction section" part on "The Carpentries: Workshop Introductions" section.

The instructions go as follows:
Imagine you have completed instructor training and you are about to teach a full lesson around the material you have been practicing teaching today.
1. Rehearse your introduction in your mind. (3 minutes)
2. Return to your groups of 2 or 3 and each give your 90-second introduction. (5 min)
3. Discuss what you liked about each other’s introductions. (6 min: optional, if there is time.)
This exercise will take 8 minutes or 14 minutes depending on whether time is included for feedback or not.

the step 2 in this exercise only give us 90 seconds to do our introduction. We assumed that we need to cover all the suggested information in the lesson, which is impossible to go over in 90 seconds. we ended up speak super fast to cover everything in 90 seconds. 
I think it will be nice to have an example introduction that is well planned and can be covered in 90 seconds. So that we can have a better picture of what we need to do in this exercise.

**Comment by ChristinaLK** [comment]
Thanks for this @bchen2 -- we'll try to incorporate in our revisions of this section.

**Comment by ChristinaLK** [comment]
Also addressed in #778

**Comment by ChristinaLK** [comment]
Make sure this exercise is clear about what can/should be covered in the 90 seconds (maybe provide an example?)

**Comment by annajiat** [comment]
I am under the impression that this is now adequately addressed via the following two sections and voting to close this issue. 

-[What is in an introduction?](https://carpentries.github.io/instructor-training/23-introductions.html#what-is-in-an-introduction)

- [Practice Your Introduction](https://carpentries.github.io/instructor-training/23-introductions.html#practice-your-introduction)
