### ISSUE TITLE
Add links to handouts for printing from instructor notes (for in-person)

### ISSUE THREAD

**Issue by karenword** [carpentries/instructor-training#728]
Because this would be useful when preparing! :)

**Comment by kariljordan** [comment]
I'm a +1 for this!

**Comment by anenadic** [comment]
Just to clarify (I am thinking of tackling this issue) - put links to instructor notes in the intro as well as in the lessons somewhere to make it more obvious to the instructor trainers these exist? @karenword

**Comment by karenword** [comment]
Thanks @anenadic! I think the goal here was to put links to the handouts/worksheets (not to the instructor notes) in the instructor notes (somewhere near the top), to make it easier to find them and print in advance when preparing for an in-person event. Should be a quick fix! As for finding the instructor notes themselves... if this is a problem worth solving it could have a separate issue?
