### ISSUE TITLE
Cutting Down Introductions Section

### ISSUE THREAD

**Issue by sheraaron** [carpentries/instructor-training#732]
I recently taught an Instructor Training at UC Davis. I shortened the Introduction section to allow more times for creating workshop websites. 

Here is what I did to cut down the Introduction section:

    Asked everyone what they thought was a good introduction?
    Asked everyone what a bad introduction was?
    Asked them to share examples of good and bad?
    Asked for specific characteristics of an introduction

After we had discussed this, we had literally gone over all of the points in our curriculum. Therefore, I simply stated what we believed were the best practices for an Introduction.

Then I had them to write their own intro (combining the 2 exercises for them to write and then rewrite).

Afer they had written their intros, I asked them to share in their groups and get any feedback and make changes accordingly.

**Comment by ChristinaLK** [comment]
Thanks @sheraaron.  We'd like to rearrange this section to be more interactive, which sounds like is what you did.  :)  

How long did this take?

**Comment by sheraaron** [comment]
@ChristinaLK  It carved off about 25 minutes.

**Comment by ChristinaLK** [comment]
thanks!

**Comment by karenword** [comment]
Addressed in current updates!
