### ISSUE TITLE
Several contact links broken on instructor training checkout page

### ISSUE THREAD

**Issue by jcoliver** [carpentries/instructor-training#736]
There are multiple links which appear to be contact links ("email", "send us", "let us know", "contact us"), but are self-referential. Related (identical?) to #734 , but that issue was closed with no apparent resolution?

**Comment by ChristinaLK** [comment]
Is there a particular page where this happens?

**Comment by jcoliver** [comment]
Instructor training checkout page: [https://carpentries.github.io/instructor-training/checkout/](https://carpentries.github.io/instructor-training/checkout/)
