### ISSUE TITLE
Checkout checklist on Data Carpentry site no longer there

### ISSUE THREAD

**Issue by jcoliver** [carpentries/instructor-training#737]
Episode 23-checkout refers to a "helpful checklist" for the checkout process. The link is to [http://www.datacarpentry.org/checkout/](http://www.datacarpentry.org/checkout/), which does not appear to contain a checklist (anymore).

And my apologies for a nearly indecipherable title for this issue.

**Comment by ChristinaLK** [comment]
Thanks @jcoliver.  
Is this an appropriate replacement?  https://carpentries.github.io/instructor-training/checkout/

**Comment by jcoliver** [comment]
Ah, that link is already included. The line with the link I'm referring to is in episode 23-checkout:

> [This page](https://carpentries.github.io/instructor-training/checkout/) explains the procedure in detail. There’s also a [helpful checklist](http://www.datacarpentry.org/checkout/) if you’d prefer a brief summary."

The "This page" link is the one for the checkout procedure in detail. The "helpful checklist" links to a Data Carpentry site which does not appear to actually have a checklist. Removal of the second sentence might be the easiest fix if the checklist is not available anymore.

**Comment by weaverbel** [comment]
Since all checkout stuff is now either on the instructor training website or in the Handbook, this info has been taken down from the DC site. So I suggest removing the sentence altogether. @jcoliver @ChristinaLK

**Comment by ChristinaLK** [comment]
👍

**Comment by alex-konovalov** [comment]
Removed the sentence as suggested, in #757.
