### ISSUE TITLE
In 08-motivation, link to Shapiro & Neuberg is broken

### ISSUE THREAD

**Issue by remram44** [carpentries/instructor-training#739]
Duplicate of #716 which was closed with no explanation.

-----

This link is 404:

http://carpentries.github.io/instructor-training/08-motivation/#stereotype-threat
> the problem is that [the term has been used in many ways](http://www.europhd.net/html/_onda02/07/PDF/20th_lab_materials/jane/shapiro_neuberg_2007.pdf)

I couldn't find this PDF on www.europhd.net anymore

**Comment by ChristinaLK** [comment]
Thanks @remram44, not sure why I closed that previous issue.  :P

**Comment by ChristinaLK** [comment]
PR request to either: 
- remove sentence
- find PDF to replace missing one

**Comment by orchid00** [comment]
Hi @ChristinaLK I think it is the link cited by @alex-konovalov, but it is under paidwall. But, I found another link: http://shapiro.psych.ucla.edu/Papers_files/Shapiro%20PSPR2007.pdf 
Are you guys happy for me to send a PR with the new link?

**Comment by ChristinaLK** [comment]
Yes! that would be great.

**Comment by orchid00** [comment]
Done: https://github.com/carpentries/instructor-training/pull/758 

happy #hacktoberfest

**Comment by ChristinaLK** [comment]
Thank you! <3
