### ISSUE TITLE
Remove fluid representations from memory lesson 05_memory

### ISSUE THREAD

**Issue by amyehodge** [carpentries/instructor-training#741]
The terms "persistent memory"/"long-term memory" and "working memory"/"short-term memory" are fluid representations that should be removed from this lesson. Keep it to a single term for each.

"Persistent memory" is only used once on the page so should be easy to remove and just stick with "long-term memory", but "short-term" and "working memory" are both used a lot. We should pick one of these terms and stick with that.

https://carpentries.github.io/instructor-training/05-memory/index.html

**Comment by ChristinaLK** [comment]
My vote would be for "short-term" as the pair of "long-term"

**Comment by kariljordan** [comment]
Are there trainers who notice trainees getting confused when "short-term" and "working memory" are used interchangeably? I rarely use the term "persistent memory", but I do use "short-term memory" and "working memory" interchangeably.

**Comment by sheraaron** [comment]
Short term and Long term memory are widely used and are easy to identify with. Wheras working memory and consistent memory, I find myself always referencing back to see which is which.

**Comment by ChristinaLK** [comment]
I think this is ready for a PR for consistency.

**Comment by raynamharris** [comment]
I submitted PR https://github.com/carpentries/instructor-training/pull/786. let me know what you think @amyehodge and @sheraaron
