### ISSUE TITLE
carpentry teaching practices hidden in a solution

### ISSUE THREAD

**Issue by raynamharris** [carpentries/instructor-training#743]
There is an exercise on https://carpentries.github.io/instructor-training/22-practices/index.html where the solution contains a beautiful list of teaching practices:

> Instructors should ensure that the following topics are discussed: sticky notes (as status flags), minute cards, one up/one down, collaborative note taking (Etherpad), instructor notes, live coding, formative assessments, Code of Conduct, going slowly, concept maps, pre- and post-workshop surveys, accessibility planning, error framing, modeling life-long learning, lesson study, and feedback. Any of these that aren’t covered in the class discussion should be elaborated on by the instructors.

Can we move this list out of the hidden solution and add it to the main page?

**Comment by ChristinaLK** [comment]
I think we can take the same approach as the top 10 tips for live coding in https://carpentries.github.io/instructor-training/15-live/index.html, where the list is put in the text of the lesson proper and the solution refers to it.

**Comment by orchid00** [comment]
Hi @raynamharris @ChristinaLK I can take the solution out of the box, and send a PR Would then this be a normal paragraph or a bullet point list?

**Comment by ChristinaLK** [comment]
I think a bullet point list is clearer.

**Comment by orchid00** [comment]
PR ready https://github.com/carpentries/instructor-training/pull/759

**Comment by raynamharris** [comment]
Thank you! I think I'm not the only one who will find this really useful!
