### ISSUE TITLE
Question for Faded Example exercise?

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#755]
In the Faded Example section we give learners the following exercise: 

1. Pick a block of code from an existing Software or Data Carpentry lesson, or from another lesson you have taught recently.
2. Replace 2-3 pieces of the code with a blank.
3. Write a question to test the student’s ability to correctly fill in that blank.
4. Paste your faded example in the Etherpad.

However for step 3, we never give them an example of what that kind of question looks like (thus betraying our own philosophy of guided practice).  What is the question they're supposed to come up with in step 3 supposed to look like?

**Comment by raynamharris** [comment]
I think a ggplot exercise from [R novice gampinder ggplot](http://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/index.html) would work well for this.

**Question**  In this example, we will the change in life expectancy over time as a line graph, giving each country a unique color and each continue will have its own unique panel or facet.  What would you add to the blank spaces to specific this graph? 

```
 ggplot(data = az.countries, aes(x = year, y = lifeExp, color = ________)) +
      geom_line() +  facet_wrap( ~ _______)
```

**Answer** `country` and  `continent`
