### ISSUE TITLE
Stop referring to Carpentries as organizations

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/instructor-training#760]
I gather that we are on unsure ground when referring to SWC and/or DC as organizations, which is done in a number of episodes in the instructor training material. In #606 I changed this to "project" or "projects" - perhaps the same should be done for the other episodes in the curriculum?

**Comment by murraycadzow** [comment]
I had a look through all of the episodes and also did a search for "organization" and there don't appear to be any references to SWC or DC as organizations anymore

**Comment by ChristinaLK** [comment]
Thanks @murraycadzow !  I'll go ahead and close this.
