### ISSUE TITLE
remove/replace the 3rd multiple choice question

### ISSUE THREAD

**Issue by raynamharris** [carpentries/instructor-training#769]
I've never had more than 1 student correctly answer the 3rd MCQ at the very beginning of the workshop. I find it frustrating because it can create confusion that I don't think is necessary. 

Is anyone else in favor of removing or omitting this question?

"Which of these questions assesses flaws in a student’s mental model of a domain? You don’t need to provide answers for these questions."

**Comment by k8hertweck** [comment]
We talked about this in trainer training last month. I agree that this could easily turn demotivating for some learners and would prefer to remove/replace/modify

**Comment by amyehodge** [comment]
Agreed. If we can't find a better way to ask this so that people don't answer the individual answers instead of choosing one, it's better removed.

**Comment by raynamharris** [comment]
Okay, I have created a PR to remove this question in #771. If we want to add a different question we can, but I think 2 questions is sufficient to collect information, to motivate the transition to talking about MCQ, and to occupy 3 min of class time.

**Comment by ChristinaLK** [comment]
The idea was to have a MCQ that unpacked trainee's knowledge, as a model for the later content, but I'm okay with removing, as it doesn't work as well as it used to within the material.
