### ISSUE TITLE
shorten & rename episodes, add overview

### ISSUE THREAD

**Issue by raynamharris** [carpentries/instructor-training#770]
I have a few issues with the names of because 1) they are really long and 2) they don't all match the content as well as I think they should if you only look at the second part of the episode titles. 

To address the length can we remove the "theme" portion of the titles? We could create an overview table at the beginning if it would be useful, but i don't think we need those things in the title

Here are some examples of content mis-match. Can we rename these after reorganizing? 
- [11 "importance of practice"](https://carpentries.github.io/instructor-training/11-practice-teaching/) is about using feedback to get better
- [2 "importance of practice"]( https://carpentries.github.io/instructor-training/02-practice-learning/index.html) is about novices/experts, mental models, and assessment
- [6 "getting feedback"](https://carpentries.github.io/instructor-training/06-feedback/index.html) is about _collecting_ feedback 
- [14 "lesson study"](https://carpentries.github.io/instructor-training/14-lesson-study/index.html) is about learner profiles and challenges 

This issue replaces PR https://github.com/carpentries/instructor-training/pull/686

**Comment by karenword** [comment]
+1! And yes, we need to reorganize (to the extent that we're able in this update) first, and rename second. Will add more comments & suggestions once we have a clearer idea about what that will look like, but everyone should feel free to chime in in the mean time if a perfect/catchy title for an existing section comes to mind!

**Comment by raynamharris** [comment]
See suggestions in https://github.com/data-lessons/instructor-training/pull/18

**Comment by raynamharris** [comment]
Was closing this premature? I'm not aware of any decisions made yet about the titles...

**Comment by ChristinaLK** [comment]
We renamed them as part of the big update today but if you still think some of the names are unclear, go ahead and re-open and indicate which episodes to consider.

**Comment by raynamharris** [comment]
Ah, I see. I was waiting for some sort of announcement and PR https://github.com/data-lessons/instructor-training/pull/18 was closed without a comment that mentioned the titles were changes elsewhere
