### ISSUE TITLE
Lesson study - change example in "Designing good challenges"

### ISSUE THREAD

**Issue by murraycadzow** [carpentries/instructor-training#772]
The example (Challenge 4) used in this section can be off putting for some learners as it requires some understanding of R.

I would suggest the example gets changed to a more accessible example

**Comment by raynamharris** [comment]
This refers to https://github.com/carpentries/instructor-training/blob/gh-pages/_episodes/14-lesson-study.md

Yes, there are a few challenges in the lesson that require R or python knowledge. Would it help if the output were provided? Would it help if a pthon or non-computational example were provided?

the output would be 

    ##      [,1] [,2] [,3] [,4] [,5] [,6]
    ## [1,]    1    4    7   10   13   16
    ## [2,]    2    5    8   11   14   17
    ## [3,]    3    6    9   12   15   18

**Comment by amyehodge** [comment]
As someone who doesn't use R or python, I think it's super helpful to have the output.

**Comment by raynamharris** [comment]
Okay, let me know if PR https://github.com/carpentries/instructor-training/pull/775 works for you @murraycadzow

**Comment by murraycadzow** [comment]
@raynamharris I think that is a great improvement, thanks. I do still wonder if we need a non-programming example too.
In a wider context it would start to ask the question of "how familiar with Carpentries workshop content would learners need to be before becoming instructors".

What originally sparked this was I had someone who had very minimal experience of Carpentries, with no programming background on an instructor training and they commented that there was a very high cognitive load for them with the examples we used during the instructor training because of the programming examples we used, that to them were jargon so the ideas behind them were getting lost.

**Comment by karenword** [comment]
We received a fair amount of feedback in this vein after a library carpentry instructor training recently, and I suspect this will be an increasing problem as our curriculum expands and diversifies. I wonder what kind of content would be Carpentries- relevant but also more broadly inclusive to be a useful alternative here?

**Comment by ChristinaLK** [comment]
I'm pretty sure there's an issue open in the repo about this.  :P

**Comment by ChristinaLK** [comment]
Thanks for the PR @raynamharris !

**Comment by amyehodge** [comment]
Can we also update this example so that it explicitly mentions that this is in R? Thanks.
