### ISSUE TITLE
"contact us" link

### ISSUE THREAD

**Issue by ws155west** [carpentries/instructor-training#777]
The contact us link at the bottom  links to https://carpentries.github.io/instructor-training/checkout/  rather than a contact page or email address.

**Comment by ChristinaLK** [comment]
@karenword who should that link go to? checkout@carpentries? team@carpentries?

**Comment by ws155west** [comment]
checkout@carpentries.org
there is a "contact us" in the text near the top of the page that lins to this email address, and, coincidentally, I posed a question and got an answer, so it works :-)

**Comment by ChristinaLK** [comment]
@rgaiacs why is
`[contact us]({{ mailto:site.email }})` resolving to the page itself if
`email: "checkout@carpentries.org"`
is in the `_config.yml` file?

**Comment by rgaiacs** [comment]
```
$ git remote get-url origin
git@github.com:swcarpentry/instructor-training.git
$ git log -1             
commit bfc5d71b78f55c792ce065152e2d7338fdddd015 (HEAD -> gh-pages, origin/gh-pages, origin/HEAD)
Merge: afea777 c88dbcd
Author: Christina K <christinakconnect@gmail.com>
Date:   Mon Oct 22 13:49:07 2018 -0500

    Merge pull request #775 from carpentries/raynamharris-patch-2
    
    add out challenge output
$ grep -nr "site\.email" _extras
_extras/checkout.md:14:1.  Make (and [send us a link to](mailto:{{ site.email }})) a [contribution to a lesson's content, exercises, or instructor's guide](#lesson-change).
_extras/checkout.md:39:and must be requested before the three months are up. To request an extension, please [contact us](mailto:{{ site.email }}).
_extras/checkout.md:63:Contributions to Data Carpentry materials may be submitted through GitHub or by [email]({{ site.email }}).
_extras/checkout.md:74:1.  If you submit your contribution through GitHub, you need to [send us]({{ mailto:site.email }})
_extras/checkout.md:132:please [let us know]({{ mailto:site.email }})
_extras/checkout.md:238:please [contact us]({{ mailto:site.email }}).
```

Please replace lines 

- 63 with `Contributions to Data Carpentry materials may be submitted through GitHub or by [email](mailto:{{ site.email }}).`
- 74 with `If you submit your contribution through GitHub, you need to [send us](mailto:{{ site.email }})`
- 132 with `please [let us know](mailto:{{ site.email }})`
- 238 with `please [contact us](mailto:{{ site.email }}).`

`mailto` **must** be outside of `{{` and `}}`. cc @maneesha

**Comment by ChristinaLK** [comment]
That was my guess!  Thanks @rgaiacs.
