### ISSUE TITLE
becoming non-programmer friendly

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#780]
Ongoing project to include more non-programming examples, per: 
* https://github.com/carpentries/instructor-training/issues/509 (faded example exercise)
* https://github.com/carpentries/instructor-training/issues/772 (designing challenges)

Also consider
* concept maps
* MCQ examples

**Comment by geatana** [comment]
I used this a a guide: https://www.slideshare.net/JeanSingian/lit-concept-map
