### ISSUE TITLE
Remove permalink from YAML

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/instructor-training#781]
We are not using permalink on YAML because this makes hard for local/offline reading of the lesson, including the copy stored in Zendo.

```
$ grep -rP '^permalink' _extras  
_extras/members.md:permalink: /members/
_extras/guide.md:permalink: /guide/
_extras/about.md:permalink: /about/
_extras/training_calendar.md:permalink: /training_calendar/
_extras/checkout.md:permalink: /checkout/
_extras/icebreakers.md:permalink: /icebreakers/
_extras/glossary.md:permalink: /glossary/
```

need to be removed. You can run

```
for file in $(find _extras -type f); do sed -i '/^permalink/d' $file; done
```

to remove the lines.

**Comment by remram44** [comment]
All my lessons have this permalink. Should they be removed as well?

https://github.com/swcarpentry/sql-novice-survey/blob/ac75b2457e4de5b32ace3648ab312df66540aa97/_extras/about.md#L2

https://github.com/datacarpentry/sql-ecology-lesson/blob/0cd347da74fb362fd204e68fc65a66649bf09121/_extras/about.md#L2

**Comment by ChristinaLK** [comment]
Thanks @rgaiacs.

**Comment by rgaiacs** [comment]
> All my lessons have this permalink. Should they be removed as well?

Yes.
