### ISSUE TITLE
Issue in checkout procedure: Part 2: Take Part in An Online Discussion Session

### ISSUE THREAD

**Issue by malvikasharan** [carpentries/instructor-training#789]
Should this be named to "Take Part in An Instructor Discussion"? I am proposing this as I had a chat with @karenword and she suggested that running an in-person instructor discussion is possible and that is something I/other trainers might be interested in doing when the instructor training is organized in countries where The Carpentries is new or a stable internet connection is still a big issue.

**Comment by raynamharris** [comment]
+1 to calling in instructor discussion. However, see https://github.com/carpentries/instructor-development/issues/71

**Comment by ChristinaLK** [comment]
yes, let's wait until the RFC is over.

**Comment by karenword** [comment]
Update: language has been updated to reflect changes to discussion sessions along with a link. At the present time in-person Discussion events are rare, and have not been uniformly accepted within the Trainer community, so I'm not sure that we're ready to explicitly address them in the curriculum. We could, however, add a reference to CarpentryCon/Connect events as qualifying here?
