### ISSUE TITLE
links to memory quiz don't match

### ISSUE THREAD

**Issue by amyehodge** [carpentries/instructor-training#796]
https://carpentries.github.io/instructor-training/05-memory/index.html links to http://opencoglab.org/memtest1/#interactive_test while etherpad links to https://cat.xula.edu/thinker/memory/working/serial. Is there some reason this was changed in the lesson? With one of these, some learners had trouble with Flash needing to be installed.

**Comment by fmichonneau** [comment]
the link in the etherpad should be updated to use http://opencoglab.org/memtest1/#interactive_test 

It's a recent switch to avoid having to use flash (see #540)

**Comment by amyehodge** [comment]
Another learner left feedback that the one with words was more geared toward learners whose first language is English. Agreed on that. I’ll try to update the etherpad template tonight and close this issue. 

I was surprised when they told me they were seeing something different than the old quiz because I didn’t know it had changed. I apparently need to keep up better!

**Comment by amyehodge** [comment]
The link has now been updated in the etherpad template. I have also had to alter the text for this exercise in the etherpad. This tesxt should also be updated in the curriculum materials to match, since it says you'll be presented with a list of words, but this is a test of symbols. I'm going to close this issue and create a new one for that.
