### ISSUE TITLE
update etherpad and google doc templates

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#806]
If anyone is looking for a 15-20 minute project and wants to update the template etherpad + google doc templates with the new material, that'd be great.  

https://pad.carpentries.org/ttt-template

https://docs.google.com/document/d/1P_w1rgdVk4SpXvILSS-ZKz8Ujqklfujpc_zHf8D-G1A

**Comment by ChristinaLK** [comment]
awesome, thanks!

**Comment by Denubis** [comment]
I've added a tool to automate this #1010 in case this comes up again.

**Comment by brownsarahm** [comment]
I think the exporter means we can close this issue @ChristinaLK ?

**Comment by ChristinaLK** [comment]
yup!
