### ISSUE TITLE
Update Etherpad template

### ISSUE THREAD

**Issue by jcoliver** [carpentries/instructor-training#808]
With the excellent revisions to the Instructor Training curriculum, I think the Etherpad template needs also to be updated. A few places in particular include the section about reverse instructional design & Bloom's taxonomy (episode 15) and teaching together (episode 18). There's also some rearrangements of the Day 2 material that would also need to be reflected in the Etherpad template.

**Comment by ChristinaLK** [comment]
#806

**Comment by jcoliver** [comment]
:D Opened the issue while updating my own Etherpad (before #806 ), else I wouldn't have duplicated.

**Comment by ChristinaLK** [comment]
I figured.  :)  We're so on it!
