### ISSUE TITLE
9 am to 5 pm schedule each day?

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#811]
Can we tweak the schedule so that it is more precisely 9 am to 5 pm each day?  Right now on day 1 we say we end at 5:05 which can look concerning to people who need to leave precisely at 5 pm.

Note: When I teach I aim to end at 5pm each day, but I know trainees often look at the schedule to plan their day.

**Comment by ChristinaLK** [comment]
Yes!  Someone can pick a session to shave off 5 minutes and make that change.

**Comment by raynamharris** [comment]
Maybe the memory episode? This would make lunch start at 12:30 and would end at 5. https://carpentries.github.io/instructor-training/05-memory/index.html

**Comment by ChristinaLK** [comment]
sounds good to me.
