### ISSUE TITLE
teaching tips section of guide is outdated

### ISSUE THREAD

**Issue by raynamharris** [carpentries/instructor-training#813]
In the guide, there is a section called "Curriculum Teaching Tips" but it is empty. Well, it has section headers, but they correspond to the old lesson title names. 

Can we delete this entirely? Or should we revise it with the episode titles so that later it can be elaborated?

**Comment by raynamharris** [comment]
See https://github.com/carpentries/instructor-training/blob/gh-pages/_extras/guide.md

![screen shot 2018-11-13 at 12 31 39 pm](https://user-images.githubusercontent.com/7544197/48434855-90ea5680-e740-11e8-8dcf-b96d51ad16e6.png)

**Comment by karenword** [comment]
I think this is addressed here: https://github.com/carpentries/instructor-training/pull/809/files

**Comment by raynamharris** [comment]
Excellent! I noticed it in a different pull request. Thanks!
