### ISSUE TITLE
Library Carpentry additions

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#821]
From @libcce in #814
* Add new Venn diagram based on LibraryCarpentry/governance#8 (style option 2)
* LC is not trademarked, Software and Data Carpentry are, but it is on our staff list of tasks
* There is now a unified "Request a Carpentries Workshop" form https://amy.software-carpentry.org/forms/workshop/. Should we collapse the request workshops links under 'How a Workshop Works' into one form for all the Lesson Programs?
* Under 'Who Can Teach What', certified instructors can teach all the Lesson Programs. What language should we use?

**Comment by raynamharris** [comment]
Yea! Thanks @ChristinaLK
