### ISSUE TITLE
Men seek help less?

### ISSUE THREAD

**Issue by arokem** [carpentries/instructor-training#825]
The article used as a reference to demonstrate that [men ask for help less](https://www.ncbi.nlm.nih.gov/pubmed/15737222) is about health care, not education. I wonder whether it's a bit of a stretch to refer to it in an instructional/pedagogical context. Also, as I understand it, the main conclusion from the article is that the findings on the topic are inconclusive.

**Comment by ChristinaLK** [comment]
I agree that this seems specific to health care and not education, so unless there's an explicit reference / tie to education in the paper, we should probably remove it.

**Comment by katrinleinweber** [comment]
Thanks to the merged PR, can this be closed to indicate completion of this topic?

**Comment by ChristinaLK** [comment]
yes, thanks @katrinleinweber
