### ISSUE TITLE
live coding exercise needs clarifying

### ISSUE THREAD

**Issue by orchid00** [carpentries/instructor-training#840]
the current exercise in this episode looks like this 

> > Teach 3 minutes of your chosen lesson episode using live coding to one or two
> fellow trainees, then swap and watch while the other person(s) live codes for
> you. (For this exercise, your peers will not "code-along", but will instead observe and give feedback.)
>
> Explain in advance to your fellow trainee(s) what you will be teaching
> and what the learners you teach it to are expected to be familiar with.
>
> **Don't record this exercise.** Give each other feedback
> using the 2x2 rubric we discussed previously and enter the feedback
> you received in the Etherpad.
>
> To make this exercise as similar to the workshop experience as possible,
> ask your fellow trainees to code along with you, as if they were learners at your
> workshop.
>
> This exercise should take about 25 minutes.  

I suggest to remove this last part, because it is contradicting to the first part of the exercise

> To make this exercise as similar to the workshop experience as possible,
> ask your fellow trainees to code along with you, as if they were learners at your
> workshop.

**Comment by ChristinaLK** [comment]
Agreed!
