### ISSUE TITLE
Correction to history diagram

### ISSUE THREAD

**Issue by gvwilson** [carpentries/instructor-training#842]
`fig/SWCDChistory.png` refers to "Greg Wilson and Dr. Brent Gorda" - Brent isn't a PhD, so "Dr." should be removed. (Couldn't find source for the PNG, so was unable to repair and PR.)

**Comment by ChristinaLK** [comment]
@raynamharris is this diagram yours?

**Comment by raynamharris** [comment]
This was merged a while back. Closing now :)
