### ISSUE TITLE
motivation/demotivation versus mindset

### ISSUE THREAD

**Issue by raynamharris** [carpentries/instructor-training#845]
I was teaching the [motivation/demotivation](https://carpentries.github.io/instructor-training/08-motivation/index.html) and [mindset](https://carpentries.github.io/instructor-training/09-mindset/index.html) episodes today, and it occurred to me that perhaps some of the material could be moved from the former to the latter episode. [According to wikipedia](https://en.wikipedia.org/wiki/Mindset), a mindset is a set of assumptions, methods, or notations held by one or more people or groups of people; [Merriam-Webster](https://www.merriam-webster.com/dictionary/mind-set) says is a mental attitude or inclination.

This makes me think that it might be worth moving the "Impostor Syndrome" and "Stereo type threat" subsection to the mindset episode since these topics relate to mental attitudes. 

I would keep the accessibility and inclusivity sections in the motivation section because these relate more to things the instructor can do to create a positive learning enviornment that is welcoming for all. 

Thoughts?

**Comment by karenword** [comment]
This is at the top of my list for the next curriculum push. My thought had been to do the same but inverse — ball mindset in with motivation, and strip out accessibility to feature that more loudly. I’d be glad to hear other thoughts on this!

**Comment by gvwilson** [comment]
Given everything I've read in the last two years, I think mindset and stereotype threat shouldn't be given more than a few sentences each: other things (like accessibility) seem much more solid these days.
