### ISSUE TITLE
Core lessons only on training checkout?

### ISSUE THREAD

**Issue by darachm** [carpentries/instructor-training#847]
I had some confusion about which lesson to do in my recent checkout. This is similar to #317 , but about which lessons are in-play (not which modules within a lesson).  

For my teaching session, I prepared for teaching 'Automation and Make', but agreed to switch to an R lesson on the day of (the instructor trainer felt more comfortable with me doing a core lesson). Another instructor trainer told me that they would be excited to see non-core lessons, so it seems there's a diversity of wants on this.

To err on the side of caution and less stress for instructor trainers, I propose that we ask all checkouts to use core lessons. Perhaps instructors can specifically state their willingness to try out new non-core lessons on the etherpad. So, I think we can change the language near line 245 in the instructor checkout procedures to ask:

"Please pick one of the Core Lessons for your teaching checkout, unless the instructor trainer specifically indicates they are interested in evaluating teaching on non-core lessons."

Does this make sense?

**Comment by ChristinaLK** [comment]
@karenword @raynamharris we should discuss at the upcoming trainers meeting? Also need to get LC lessons in the table of starting points?

**Comment by karenword** [comment]
I think this issue (and others like it) can now be resolved by linking directly to the new table with recommended episodes. For maximum flexibility we can suggest that anyone who wishes to checkout with a lesson not on the list should seek permission from their demo host.

https://carpentries.github.io/instructor-training/demo_lessons/index.html

**Comment by karenword** [comment]
( but also see conversation here: https://github.com/carpentries/instructor-training/pull/942 )

**Comment by raynamharris** [comment]
What do you think about this change to 1) emphasize that episodes should be chosen from actively maintained lessons and 2) provide a link to the table of episodes.

I've made a change here, 
https://github.com/carpentries/instructor-training/pull/1028 which was inspired by this https://github.com/carpentries/instructor-training/issues/1019
