### ISSUE TITLE
Update or delete template messages in files/messages

### ISSUE THREAD

**Issue by gvwilson** [carpentries/instructor-training#849]
The email message templates in files/messages are out of date - they should be deleted, or updated to match https://docs.carpentries.org/topic_folders/instructor_training/email_templates_admin.html.

**Comment by ChristinaLK** [comment]
Since operations stuff has mostly moved to the handbook, I'm happy to remove them here.  @karenword @sheraaron @maneesha ?

**Comment by raynamharris** [comment]
PR submitted https://github.com/carpentries/instructor-training/pull/866
