### ISSUE TITLE
Wondering about small shift to lesson order...

### ISSUE THREAD

**Issue by symulation** [carpentries/instructor-training#850]
After teaching a few of these both in-person and online I've noticed a spontaneous schedule switch that repeatedly happens that it might just be worth codifying directly into the suggested lesson order.

What happens is that we send participants home at the end of day one with a request to look up more about the Carpentries workshop types and then we ask them what questions they have at the start of day two.  While the intent is that these questions will be put in the etherpad and then taken up later in one way or another this doesn't happen or at least only happens in part.  The result is either a lot of saying, "We'll cover that this afternoon" or pulling parts of the relevant afternoon sessions into the morning.  Participants thus either end up a little frustrated (because they'd really like an answer now) or the schedule ends up being a little fractured.

Is this the experience of others?

Would there be interest in taking "Checkout Process" and "How We Operate", dropping them right after "Welcome" on day two, and then shifting everything else down accordingly?

**Comment by ChristinaLK** [comment]
What if we had people read the guides overnight but didn't actually take questions until lunchtime?  

I'm reticent to move checkout/how we operate forward, because they are a bit slower and I don't want to kill the momentum at the start of the day.  But if participants would be more engaged because they don't have lingering questions, I guess that's worth considering.

**Comment by symulation** [comment]
Not asking until later is another option.  I suspect though that they would be asking questions in the morning just the same.  Even before the workshop starts on day #2 they are asking questions about what they can and can't do.

I don't find the background section too slow, especially if they get to build their own course page and signup for things that they are now a little more excited about.  I    L O V E    the new content / layout of these two background sections and suspect that it will help these areas too.

What do others think about this?

**Comment by ChristinaLK** [comment]
@symulation if we don't get a lot of comments on this issue, I'll make sure to bring it up at our next trainer meeting, because I think it's worth discussing.

**Comment by DanielleQuinn** [comment]
@symulation and I recently taught instructor training and switched up the schedule to cover checkout/how we operate on the morning of day two. I really liked being able to address questions right away and thought that the flow of the morning was improved, though I felt like the switch back to the other material for the afternoon was a bit awkward.

I do agree with @ChristinaLK that the background material is a little dry and we don't want to bring down people's energy for the afternoon session. It didn't seem to be too much of a problem on the day, but it's something to keep in mind for sure. I would point out that the afternoon of day two is usually when people are tired anyway, so maybe it's a good idea to not also cover the slower material then?

**Comment by ChristinaLK** [comment]
@DanielleQuinn and I answered questions first and it seemed to go well?  I think the moral of the story is that you can do the day 2 material in almost any order?  It's pretty flexible that way.  

Potential action items: 
- discuss at next trainer's meeting if we want to change the official order of materials on day 2 (or at least point them to this issue).  
- maybe add something to the curriculum notes about the fact that day 2 can be flexible, so trainers can discuss amongst themselves what order they'd prefer.

**Comment by amyehodge** [comment]
My concern about doing questions on the morning of day 2 is that I think the practice teaching should not get shifted to the afternoon when people are really hitting the overload stage. When you do questions in the morning, what gets shifted?

**Comment by ChristinaLK** [comment]
There's two rounds of practice teaching, so when Danielle and I did questions early, we did the 2nd round after lunch.

**Comment by ChristinaLK** [comment]
To do: add a note to the instructor notes about re-ordering day 2 (if you want)
