### ISSUE TITLE
Update setup page

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/instructor-training#851]
https://github.com/carpentries/instructor-training/edit/gh-pages/setup.md

Currently lists a set of episodes from SWC and DC lessons but doesn't mention LC. Should add LC and take out specific episodes?

**Comment by ChristinaLK** [comment]
Yes! recommendations welcome. might also be a good opportunity to read through list of recommended swc/dc lessons and see if we want to make changes.

**Comment by ChristinaLK** [comment]
I think this has been done.
