### ISSUE TITLE
mention the handbook

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#867]
Do we talk about the handbook at all?  Can someone check and confirm?

As brought up in #865

**Comment by ChristinaLK** [comment]
Probably in the "How we operate" episode?
https://carpentries.github.io/instructor-training/21-carpentries/index.html

**Comment by raynamharris** [comment]
Yes, I think it would be good to mention the handbook explicitly. what do you think about #881

**Comment by karinlag** [comment]
That one is very good. However, I think it might be good to have a mention of various resources as such at the beginning of the workshop. When I teach a normal workshop, I always show that the material exists to stop people fretting about taking notes. By mentioning various resources, such as the IT pages, the handbook and the like at the start, I'm thinking it could give people a framework to work from in that they don't need to remember all by themselves.

**Comment by ChristinaLK** [comment]
@karinlag that's more of telling people about the IT material, maybe open a separate issue to add it to the intro?
