### ISSUE TITLE
Key points for "Wrap-Up and Homework for Tomorrow" lesson

### ISSUE THREAD

**Issue by anenadic** [carpentries/instructor-training#874]
"Wrap-Up and Homework for Tomorrow" lesson has no key points (which was probably the intention) but they appear at the bottom as an empty green box with a single empty bullet point. So we should either add key points (if any) or look into checking that empty key points box does not appear if possible (if not - it is OK).

**Comment by anenadic** [comment]
I think the file to have a look at is in _includes/all_keypoints.md and the code should look something like (this is not correct syntax probably):
{% if episode.keypoints not empty %}      
       <td class="col-md-9">
        <ul>
        {% for keypoint in episode.keypoints %}
        <li>{{ keypoint|markdownify }}</li>
        {% endfor %}
        </ul>
      </td>
{% endif %}

**Comment by ChristinaLK** [comment]
is this change worth making in the upstream lesson template, not just locally?

@rgaiacs @fmichonneau
