### ISSUE TITLE
how to handle audience of mixed experience with the Carpentries

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#882]
This issue is to brainstorm strategies (and eventually prs ;)) for how to handle the situation when some or all of the learners in instructor training have no experience with the Carpentries (have not attended / helped or taught at a workshop).

**Comment by ChristinaLK** [comment]
One suggestion: have a third pre-reading about the Carpentries that is optional for people who have some experience w/ the Carpentries, but required for those who haven't.

**Comment by ChristinaLK** [comment]
Another: revamp the welcome email to include an introduction to the Carpentries.

**Comment by ChristinaLK** [comment]
Rework the opening to include an intro to the Carpentries and segue into the overview of intstructor training and how what we're going to cover relates to different aspects of the Carpentries.

**Comment by ChristinaLK** [comment]
Include a mandatory opening exercise where everyone shares their goals/what they're hoping to get out of the training. Then you have a sense of where people are at, what they know, and what you may need to emphasize.

**Comment by amyehodge** [comment]
> Include a mandatory opening exercise where everyone shares their goals/what they're hoping to get out of the training. Then you have a sense of where people are at, what they know, and what you may need to emphasize.

I really like this. It has a dual purpose of getting people to know each other a little better, though it will take more time. I find people don't read the emails as it is and don't do the advance work, so I'm hesitant about relying on that if this is critical.

**Comment by karinlag** [comment]
How about including a link to a videoed Carpentries workshop to be viewed before attending?

**Comment by chrispunjoku** [comment]
The **opening exercise suggested by Christina is a wonderful idea**.  This really gives the instructor a sense of participants’ current data/software skills level and experience with Carpentries. It as well helps instructor form some ideas of how to carry everyone along.  I agree with Amy that this’s gonna take a fraction of lessons time. I think **time spent on this will be time well spent**.  After all, excellent in-person training events go with icebreakers, energizers and some other motivational, engaging, fun learning activities, which we should find ways of incorporating into online context.
[IceBreakers in the online environment.pdf](https://github.com/carpentries/instructor-training/files/2845221/IceBreakers.in.the.online.environment.pdf)

**Additionally**, instructors and helpers need to notice countenances that signal “confused”, “not following”, etc. and actions of inattentiveness (like face-less video, persistent face-down or working on something else, which suggest participant probably isn’t watching/listening again) and promptly intervene with remarks like: “Karen [participant’s name], are you still there/here?”, “Am I fast?”, “Is there anything I need to clarify?”, etc.  These are as helpful in online situation as they are in face-to-face teaching.  I think also an instructor ought to call for questions intermittently and make answering open to anyone (being careful to observe and restructure any unhelpful reply by a participant.

There's also **high potential in **Karin’s idea****.  That potential can be fully tapped if what hinders prospective participants from doing good, important pre-workshop reading (about the Carpentries, Handbook, CoC, _How Learning Works_, _The Science of Learning_) and from doing in-workshop assignments (as had been commonly reported) won’t come into play here.  **Am I being pessimistic?**

**Comment by raynamharris** [comment]
I think revamping the introduction with a new exercise about their motivations could be a great thing to add. I also like the idea of adding links to optional videos to watch, but I worry we might need to cut something out of the pre-workshop reading materials to make space... 

How do people feel about linking one or more of these videos:
- Tracy Teal, PyCon 2016, DC Python Ecology https://www.youtube.com/watch?v=Ws34Ho-1aDs
- Maxim Belkin, SciPy 2017, SWC Shell https://www.youtube.com/watch?v=7VO4pUGCcMI
- Katy Huff, SciPy 2013, Git https://www.youtube.com/watch?v=T0BE9ApIegc&t=2706s

**Comment by raynamharris** [comment]
I've suggested adding a bullet point to ask attendees to read the 2018 executive summary before attending a training event. This could help solve the problem. 

https://github.com/carpentries/handbook/pull/454

**Comment by karenword** [comment]
Closing as this topic has been substantially addressed in updates. I really like the idea of collecting example videos from workshops somewhere, but this may be better in a general community space as opposed to the IT curriculum. @kmomar is there a home for the YouTube workshop links in this issue?
