### ISSUE TITLE
add images from 2018 annual report and/or provide report to read beforehand

### ISSUE THREAD

**Issue by raynamharris** [carpentries/instructor-training#890]
I recently saw a talk about The Carpentries by @serahrono, and two images from [the 2018 annual report](https://carpentries.org/files/assessment/TheCarpentries2018AnnualReport.pdf) really stood out. This makes me wonder if we should make any or all of the following changes:

1. Replace the current ["brief history" image in episode 21](https://carpentries.github.io/instructor-training/21-carpentries/index.html) with this image (maybe rotated 90 degrees and without the mission statement). 

![screen shot 2019-02-20 at 11 23 14 am](https://user-images.githubusercontent.com/7544197/53111168-36f8ea00-3502-11e9-84f7-b541b9ef09b2.png)

2. Add this image of our impact and reach to [the welcome episode](https://carpentries.github.io/instructor-training/01-welcome/index.html)

![screen shot 2019-02-20 at 11 23 25 am](https://user-images.githubusercontent.com/7544197/53111427-a4a51600-3502-11e9-902a-669112b4d788.png)

 3. Add [the 2018 annual report](https://carpentries.org/files/assessment/TheCarpentries2018AnnualReport.pdf) as a required reading to the [workshop setup](https://carpentries.github.io/instructor-training/setup.html) and [the email template](https://docs.carpentries.org/topic_folders/instructor_training/email_templates_admin.html).

I think points 2 and 3 could help with the problem raised in #882 on handling workshops where many people are not familiar with the carpentries.

**Comment by kariljordan** [comment]
I love the image you created originally, and am fine with this one as well. I'd like to hear from a few more trainers before we have @serahrono submit a PR to fix it (she volunteered:))

**Comment by gvwilson** [comment]
I would like to see 2010 listed as the reboot of Software Carpentry in its modern form - lots else happened in those 16 years, but that's really when the clock started for the organization and content as they are now.

**Comment by katrintirok** [comment]
I also like the image that is in the material at the moment, 'brief history ...'. , would not really change that
For the other points, 2. and 3.,  - they area good suggestions and could improve the material. I also think the report is a good intro to what the carpentries are and do, not only for people new to the carpentries but also those who know already some things

**Comment by raynamharris** [comment]
Okay, rather than including the report or the images from the report in the curriculum, I've added it to the suggested reading list in the welcome email for online workshops. 

https://github.com/carpentries/handbook/pull/454

**Comment by karenword** [comment]
The Annual Report is now linked in all versions of the updated [pre-training email](https://github.com/carpentries/docs.carpentries.org/pull/766/files) as well as from the [setup page](https://carpentries.github.io/instructor-training/setup.html). Thanks all! :)
