### ISSUE TITLE
Ep11 Poor exercise wording

### ISSUE THREAD

**Issue by gcapes** [carpentries/instructor-training#904]
https://carpentries.github.io/instructor-training/11-practice-teaching/index.html#feedback-on-yourself
This exercise doesn't really make sense and needs clarifying:
> teach a 90s segment of a lesson episode ... don't live code

What are you supposed to teach if it isn't live coding? Have trainees chosen a 90s non-live coding snippet of a SWC lesson to teach?

**Comment by ChristinaLK** [comment]
I think the idea is to just introduce the topic (because you only have 90 seconds).

I'd like to bring this up at a trainers meeting to get people's feedback. Should definitely clarify what we're hoping to accomplish with this exercise.
