### ISSUE TITLE
Ep 21:  SWC is not domain-specific

### ISSUE THREAD

**Issue by gcapes** [carpentries/instructor-training#906]
> Their aligned missions are accomplished by running accessible, inclusive training workshops; teaching openly available, high-quality, domain-tailored lessons; 

> Software Carpentry workshops are: ... not domain-specific,

Maybe I'm reading this wrongly but it seems like this intro paragraph is explaining what the lesson domains have in common, but the following details contradict this. Perhaps the *domain-tailored* claim can be dropped from the intro? 

It also doesn't mention whether library carpentry is domain specific.

**Comment by ChristinaLK** [comment]
We can take out "domain-tailored".
