### ISSUE TITLE
Confusing wording about "chosen lesson" for checkout

### ISSUE THREAD

**Issue by krismyu** [carpentries/instructor-training#907]
On the [checkout page describing the teaching demo](https://carpentries.github.io/instructor-training/checkout/#demo-lesson), it describes the "chosen lesson" as in the following:

> For your teaching demonstration, you will teach a short segment from your chosen lesson(s). We will pick the segment of the lesson(s) you are to teach on the day of the demonstration, so you must be prepared to teach any part of your chosen lesson(s)

It doesn't specify *who* is doing the choosing. At first I thought it meant that the people running the demo session would do the choosing and you would have to be responsible for teaching any lesson in any one of the carpentries.  It could be helpful to say somewhere that part of the procedure is to choose a lesson.

So one idea for a revision might be:

> Choose a lesson for your teaching demonstration. You will be asked to teach a short segment from your chosen lesson(s). We will pick the segment of the lesson(s) you are to teach on the day of the demonstration, so you must be prepared to teach any part of your chosen lesson(s)

**Comment by ChristinaLK** [comment]
thanks @krismyu ! We're always looking to improve the description of the checkout process.

**Comment by raynamharris** [comment]
Thanks @sstevens2 !
