### ISSUE TITLE
Introduce Regional Coordinators

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#909]
When we talk about The Carpentries it would be good to introduce the role of the Regional Coordinators so people know who they can turn to for questions about running workshops, connecting with community members, etc.  

Somewhere here would make most sense:
https://carpentries.github.io/instructor-training/21-carpentries/index.html

Open to suggestions about where best to include this.

Tagging @sheraaronhurt  since she works closely with the RC team as well as @anenadic  and @symulation since they are both trainers and RCs.

**Comment by sheraaronhurt** [comment]
@maneesha yes! I would like for it to be there under "How a workshop works" It would be nice to introduce the RCs there. Because most likely before getting started they will need assistance from their RC who can assist. 

Also, the [worksheet](https://carpentries.github.io/instructor-training/files/handouts/Carpentries_roles_worksheet_v3.pdf) needs to be updated to say Regional Coordinator. I'll do an issue for that.

**Comment by maneesha** [comment]
Thanks @sheraaronhurt .

@karenword  What do we need to do to integrate this into the lesson?

**Comment by ChristinaLK** [comment]
This sounds fine to me - whoever wants to submit a PR can.

**Comment by raynamharris** [comment]
I think the paragraph to edit is this one:

"Briefly, there are two types of Carpentry workshops: self-organized and centrally-organized. For a centrally-organized workshop, Carpentry staff takes care of organization and administration such as finding instructors and handling workshop registration. For a self-organized workshop, all of these details are handled by the instructors or organization hosting the event."

What do you think about replacing that text with the following text:

Briefly, there are two types of Carpentry workshops: centrally-organized and self-organized. **Centrally-organized workshops**, are organized by a team of [Regional Coordinators](https://carpentries.org/regionalcoordinators/) who take care of logistics and administration such as finding instructors and handling workshop registration. For a self-organized workshops, the organization hosting the event is responsible for these details." 

Please feel free to suggest something else. I have already started PR #923 to update the exerside and worksheet about regional coordinators, so I can add whatever text we decide on there

**Comment by raynamharris** [comment]
We decided to merge #923 because it addresses the issue related to the handout and exercise. Changes to the text about the role of the coordinator can be added in a new PR.

**Comment by raynamharris** [comment]
Yea! Thanks @ChristinaLK
