### ISSUE TITLE
Updating Carpentries Role Worksheet 

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/instructor-training#911]
The [Participating in the Carpentries – What’s Your Role?](https://carpentries.github.io/instructor-training/files/handouts/Carpentries_roles_worksheet_v3.pdf) worksheet should now say Regional Coordinator and not Workshop Administrator.

**Comment by amyehodge** [comment]
Sher -- since I made this, I'll put it on my list to update today or tomorrow. Though I may send it to you in email, because I seem to regularly do updates to this repo incorrectly. 🙄

**Comment by amyehodge** [comment]
[Carpentries_roles_worksheet_v4.docx](https://github.com/carpentries/instructor-training/files/2994037/Carpentries_roles_worksheet_v4.docx)
[Carpentries_roles_worksheet_v4.pdf](https://github.com/carpentries/instructor-training/files/2994038/Carpentries_roles_worksheet_v4.pdf)

Here are the new files. I'll submit another ticket to for changing the link and the text for the answer key.
