### ISSUE TITLE
Training calendar needs time-date links

### ISSUE THREAD

**Issue by karenword** [carpentries/instructor-training#912]
Maybe one for @sheraaronhurt ? Open trainees are having difficulty figuring out which trainings are at what times in their local time zones. Time-date conversion links would be a super helpful addition!

**Comment by ChristinaLK** [comment]
Who should do this? If it's a quick change, I'd like to close this issue. :)

**Comment by maneesha** [comment]
Is it this page you are referring to?
https://carpentries.github.io/instructor-training/training_calendar/
These are all listed by time zone with the UTC offset.

Let me know what specific change you'd like to see.

**Comment by karenword** [comment]
Thanks @maneesha ! I was thinking like the links we have on the etherpad, e.g.
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Carpentries+Instructor+Training+2-day+event+%28start+time%29&iso=20190530T09&p1=3921

I'd be happy add these as part of our update this week if you're ok with the addition, but figured we should ask since we don't normally maintain this page. People who aren't used to doing UTC conversions and aren't in one of the identified time zone areas are sometimes confused about what is closest to them.

While we're at it, it might also be good to add some explanation about how/when Aus/NZ events are scheduled on this page (even/especially when they are not available), as that is another source of questions! But that could be a separate issue if it's not a quick fix.

**Comment by maneesha** [comment]
Let's consider the AU/NZ as a separate issue.

Adding the local time conversion is a great idea.  if you want to do that as part of your update this week that would be great.  We should be sure to add in some text to note that the converted time reflects just the start time for day 1.  

Maybe this line:

> All trainings are offered online from 9 am to 5 pm in the time zone noted. You do not need to be in the same time zone yourself but need to accommodate that time zone.

can have added to it:

> ... Click the link for each event to view the start date/time in your local time zone.

**Comment by raynamharris** [comment]
Thanks @karenword! Closed with #959
