### ISSUE TITLE
Chemistry example of fluid Representation

### ISSUE THREAD

**Issue by thandocharmane** [carpentries/instructor-training#913]
I would like to contribute an example of a fluid example that might be beneficial to potential trainers with a chemistry background or who are chemistry experts.

Chemistry Example: Switching between technical terms "Reference material" and "Standard" 

These two terms refer to a solution of known origin and concentration, however the term standard  is also used to refer to quality related guidelines which are used a lot in the chemistry environment. So this could be very confusing to a novice learner.

**Comment by ChristinaLK** [comment]
Thanks for the example @thandocharmane !
