### ISSUE TITLE
PDFs and screen readers

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/instructor-training#924]
At a training recently, a learner noted that the [PDFs used for the exercise on accessibility](https://github.com/UKHomeOffice/posters/blob/master/accessibility/dos-donts/posters_en-UK/accessibility-posters-set.pdf) aren't actually that accessible (there are issues with screen readers and PDFs). It would be worth noting, or perhaps asking as a meta-level question, associated with this with exercise.

**Comment by rgaiacs** [comment]
@k8hertweck Thanks for this issue. PDF can store "metadata" to make it accessible or not. Generally, PDF is not accessible --- think when you copied and pasted something from one PDF and spend more time fixing the text then would take you to type the text. The PDF on the lesson is one of the few that has short, objective and meaningful instructions. We could find another source.

**Comment by ChristinaLK** [comment]
To do: add a callout to this lesson that mentions pdf accessibility and requests a submission.
