### ISSUE TITLE
Unclear link in homework assignment

### ISSUE THREAD

**Issue by amyehodge** [carpentries/instructor-training#929]
The link to the information about self-organized workshops redirects people to https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html#host-checklist. This page doesn't specifically mention self-organized workshops. In fact, the link to the centrally-organized workshops at https://datacarpentry.org/workshops-host/ actually may be the best place to direct people, though this isn't the focus of the page. I couldn't find anything in the handbook that discussed these two types of workshops that was directed at the public as opposed to tasks for staff.

**Comment by karenword** [comment]
I think this may be a handbook problem, where the issue of self vs centrally organized workshops could be better discussed there. @maneesha what do you think about this?

**Comment by raynamharris** [comment]
Yea! Thanks @ChristinaLK
