### ISSUE TITLE
Request a workshop

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/instructor-training#930]
There is now a single workshop request form for all our workshops. The text in the section "[How a workshop Works](https://carpentries.github.io/instructor-training/21-carpentries/index.html#how-a-workshop-works)" needs to be updated to reflect this.

**Comment by maneesha** [comment]
It also only refers to request for SWC and DC. Need to incorporate LC as well.

**Comment by maneesha** [comment]
Fixed with 8f928bb96513eb4694477624c598df7fa0a7b5ba
