### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/instructor-training#934]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by karenword** [comment]
@fmichonneau will everyone who has contributed since the last official release be listed as an author for this release?

**Comment by fmichonneau** [comment]
yes, they will!

**Comment by ErinBecker** [comment]
Hi Maintainers! - Just confirming that you're still planning on including your lesson in the June 2019 release. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone. I'll make a first pass and add issues currently marked "help-wanted" to the milestone, but please feel free to update the milestone issue list at your convenience. Please let me know if you have any questions!

**Comment by karenword** [comment]
Thanks @ErinBecker -- the issues we have identified for prioritization in this release have been added to our release Project: https://github.com/carpentries/instructor-training/projects

**Comment by ErinBecker** [comment]
@karenword - Nice! I've never used the Projects feature before and it looks pretty. I've updated the link in our upcoming blog post to direct contributors for your lesson to the Project rather than the Milestone. Cheers!

**Comment by ChristinaLK** [comment]
After #960 and #961 are we set? Anything to do for the final check box (File structure is clean (e.g. delete deprecated files, insure filenames are consistent))?

**Comment by ErinBecker** [comment]
Hey Maintainers - just checking in to see if you're still planning on joining the release this month. We're asking that all lessons have completed the checklist by [Tuesday, 4 June, Anywhere on Earth time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190604T235959&p1=3399) in order to be included in the release. Please let me and @fmichonneau know if you have any questions or are running into any technical issues with preparing your lesson.

**Comment by karenword** [comment]
Also @ErinBecker are changes still allowed after this date as long as the checklist is complete? Or are we supposed to be finished with all updates (not just those related to the checklist) by today?

**Comment by raynamharris** [comment]
@fmichonneau and @ErinBecker We are done with our checklist!

**Comment by ErinBecker** [comment]
Woohoo!!! 🎉 Congrats!

You're welcome to continue making changes after completing your checklist, just please make sure that the changes don't break any of the things on the checklist! 😄

**Comment by ErinBecker** [comment]
Awesome work @ChristinaLK, @raynamharris, @karenword and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
Lesson released! :tada: https://doi.org/10.5281/zenodo.3258398

(The DOI might not resolve quite yet)
