### ISSUE TITLE
Does the handouts PDF filename need a version number?

### ISSUE THREAD

**Issue by scottgruber** [carpentries/instructor-training#938]
During our instruction training workshop we were given a link to the Carpentries role workshop that was broken. It went to Carpentries_roles_worksheet_v3.pdf, and the [current version is /Carpentries_roles_worksheet_4.pdf](https://github.com/carpentries/instructor-training/blob/gh-pages/files/handouts/Carpentries_roles_worksheet_v4.pdf). 

Should a version number be included on a file put into a git repository? Git itself could provide version control and file history. It might also make it easier for trainers to only need to keep one permalink. The filename could be something like https://github.com/carpentries/instructor-training/blob/gh-pages/files/handouts/Carpentries_roles_worksheet.pdf

I reviewed [issue 611]( https://github.com/carpentries/instructor-training/issues/611) and a similiar problem occurred when the file was named Carpentries_roles_worksheet__2.pdf.

**Comment by ChristinaLK** [comment]
That's a good question @scottgruber .  I'm not sure if there was a particular reason for the numbered files, or if it would be better to let git do the versioning, as you suggest.  

@amyehodge @karenword @raynamharris do you have any thoughts?

**Comment by amyehodge** [comment]
I think this is because I made the handout and then modified the subsequent versions and I don't know how to make those changes on my machine but have the files tracked in this repo. I needed to give them new names to track locally, so that's what I did. I don't see any reason to need to keep it that way in the future, though if I continue to do updates, someone might need to explain some things to me. :)

**Comment by scottgruber** [comment]
There are definitely a number of strategies to work with git. I think one that might work would be is a release branch strategy.  Releases use based on Git tags, and mark a specific point in your repository's history. 

See if the section of [this article](https://nvie.com/posts/a-successful-git-branching-model/) about half way down where Release Branches starts explains a rationale clearly. GitHub has some [articles](https://help.github.com/en/articles/about-releases) too. 

There are other strategies too, and, it certainly took me a while to understand git. And I still have a lot more to learn too. Maybe this is a good opportunity to improve my teaching skills too so I can try to explain again if any of this causes confusion.

**Comment by amyehodge** [comment]
I think part of the complication is that I don't have the power to upload files into the repo, so I have to send them to someone else. I seem to recall running into that issue, but, again, I may be mistaken or have missed something about the process.

**Comment by raynamharris** [comment]
My personal preference would be to remove the version numbers from file names so that changes to the code within the lessons do not have to be made when newer versions of the pdf are uploaded.

**Comment by scottgruber** [comment]
I read through a [process for june lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release). 

@ErinBecker @ChristinaLK @raynamharris I didn’t notice if the release strategy might adopt a release number branch to preserve the history. Assuming it does is the instructor training repository included in the release schedule in June? I didn’t see if release numbers tag are part of the strategy. If they are that might offer a solution to this issue.

@amyehodge Do you have write access to branches you create and make pull requests? Is the person you email your changed files on this thread?

I’m registered for the May 24 online discussion and could bring it up as a topic. 

I could try to create new branch to change the filename and put in a pull request with time for review before the June lesson release.

Thanks for the chance to help.

**Comment by ErinBecker** [comment]
Thanks for the questions @scottgruber. On the staff side, @fmichonneau will be handling the technical aspects of the lesson release. @fmichonneau, could you clarify whether our release process includes adopting a release number branch and tag? (I'm not sure what this means.)
