### ISSUE TITLE
Refer to rubric during session on checkout process

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#941]
We refer to the lesson demo evaluation rubric here: (https://carpentries.github.io/instructor-training/17-performance/index.html) but it would be good to also reference it during the session on the checkout process (https://carpentries.github.io/instructor-training/20-checkout/index.html), on the checkout info page (https://carpentries.github.io/instructor-training/checkout/), and on the etherpad (https://pad.carpentries.org/teaching-demos-recovered).

**Comment by kariljordan** [comment]
Reminder to @kariljordan to submit a PR for this.

**Comment by lexnederbragt** [comment]
Maybe it would be good to mention it in the ['Reminder teaching demo'](https://docs.carpentries.org/topic_folders/instructor_training/email_templates_trainers.html#reminder-teaching-demo) email as well?

**Comment by maneesha** [comment]
Can we also link to the suggested lessons? I don't want someone to not pass their demo because they choose a lesson that was not appropriate for the demo.

**Comment by lexnederbragt** [comment]
Suggested lessons yes (suggested episodes, no...). We say in https://carpentries.github.io/instructor-training/checkout/#demo-lesson "You can refer to the lists of [Software Carpentry lessons](https://software-carpentry.org/lessons/), [Data Carpentry lessons](http://www.datacarpentry.org/lessons/), and [Library Carpentry lessons](https://librarycarpentry.org/lessons/) on the websites." That should cover it, right?

**Comment by raynamharris** [comment]
As for the name, I would short both this and the subsequent page to "Episodes for TEaching Demos" and "Rubric for Teaching Demos" to shorten both of the labels in the dropdown menu. 

To answer @lexnederbragt's question, only pointing to the lessons on the websites raises a lot of uncertainty. Many episodes have features that make them unsuitable for 3 minutes teaching demonstration, so this is a roadmap for that. There could be an alternative, but right now this table helps learns and host prepare for demos.

**Comment by raynamharris** [comment]
See also current progress at https://github.com/carpentries/instructor-training/pull/944

**Comment by kariljordan** [comment]
I added the rubric to line 23 of the Etherpad: https://pad.carpentries.org/teaching-demos-recovered

**Comment by raynamharris** [comment]
Thanks @kariljordan
