### ISSUE TITLE
"homework" episode needs keypoints

### ISSUE THREAD

**Issue by raynamharris** [carpentries/instructor-training#961]
As part of the lesson release (#934), all episodes need key points. The homework episode is lacking in this https://carpentries.github.io/instructor-training/12-homework/index.html

Any suggestions?

**Comment by ChristinaLK** [comment]
I think we could summarize into: 
* today we learned about how people learn, how to build a positive classroom environment, and how to give feedback.
* tomorrow will cover specifics of Carpentries workshops and teaching practices.

Basically what the episode says!

**Comment by ChristinaLK** [comment]
I'll do a quick PR for this.
