### ISSUE TITLE
Should OpenRefine (LC) be a suggested lesson for demos?

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#972]
I just used it for a demo following the guidelines. The only recommended lesson is "Importing data into OpenRefine" but it's a super short lesson - even too short for the 5 minute teaching demo.

**Comment by karenword** [comment]
This is true. However once they've completed the first lesson the second seems to be ok to move on to (just not to start on). So I've just let them move on when the lesson ended before the 5 minutes was up.

**Comment by ChristinaLK** [comment]
To do (for someone): make a note to this effect in the table of starting points?
