### ISSUE TITLE
Teaching demo starting points for Python gapminder lesson

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/instructor-training#979]
The [Suggested Episodes for Teaching Demonstrations page](https://github.com/carpentries/instructor-training/edit/gh-pages/_extras/demo_lessons.md) does not have an entry for the [Plotting and Programming in Python](http://swcarpentry.github.io/python-novice-gapminder/) lesson. Is there any reason not to allow this lesson for teaching demo's?

**Comment by ChristinaLK** [comment]
I don't think so.

**Comment by ChristinaLK** [comment]
Feel free to submit a PR with starting points. ;)

**Comment by brownsarahm** [comment]
I did a demo for someone today using that lesson. 

I think the only episodes to avoid are:

[Variable Scope](http://swcarpentry.github.io/python-novice-gapminder/15-scope/index.html) it's very short and more conceptual/exercises than live coding
[Programming Style](http://swcarpentry.github.io/python-novice-gapminder/18-style/index.html) again, breif and mostly concepts/excercises more than live coding
