### ISSUE TITLE
more background info

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/instructor-training#983]
A learner at this morning's workshop suggested, "also asking about instruction in relation to library research instruction." in reference to this exercise:

https://github.com/carpentries/instructor-training/blob/gh-pages/_episodes/01-welcome.md#background

**Comment by raynamharris** [comment]
Would this work? I've added **a new suggestion in bold.**

6. I have taught informally through outreach programs, hackathons, **libraries,** laboratory demonstrations, and similar activities.

**Comment by brownsarahm** [comment]
I think so, unless people who do this type of instruction wouldn't consider it informal?

**Comment by karenword** [comment]
Looks like this issue was addressed, but not closed. Thanks all -- closing now! :)
