### ISSUE TITLE
Include section on Workshop Conclusions as well as intros

### ISSUE THREAD

**Issue by angela-li** [carpentries/instructor-training#989]
Something that I would love to see included in this guide is _how to end a workshop_. In my experience, it's too easy to just taper off at the end of the workshop (and I've seen this happen in workshops), so having a plan in place ahead of time would be fantastic.

Questions I'd like to see answered include:

- **What should instructors include in their workshop conclusion?** (Links to groups for further learning, ie. community learning groups, departmental study groups; contact information for instructors?; resources to dig more into learning; where to get help in the future)
- **How can instructors end the workshop with energy?** (Even when instructors are tired from teaching a whole day. Perhaps the instructor who didn't just finish teaching can do the wrap-up for the workshop...)
- **How can instructors motivate students to continue on their learning journey?** (There's only so much that can be covered together; it would be wonderful to learn techniques to motivate learners to self-study; perhaps a recap of a growth mindset would be good?)

I would be happy to draft something with regards to this based on my experiences, if that is of interest to folks!

**Comment by karenword** [comment]
+1! At the present time, we cannot add new material to this curriculum until we can carve out the space for it. However I agree that this would be an excellent addition -- I would love to see it prioritized during our next curriculum push.

**Comment by angela-li** [comment]
Sounds good. I'm wondering if this would make a good blog post in the meantime (or in addition to an add to the curriculum)? Is that something you think would be interesting to people?
