### ISSUE TITLE
Consider how two-day training format excludes instructors who would otherwise teach

### ISSUE THREAD

**Issue by angela-li** [carpentries/instructor-training#990]
I bring this up because we have a stellar lecturer in my research center who would love to become trained, but is unable to dedicate two full days of training time due to her family and work situation (will not go into details, but involves childcare, rescheduling important commitments, etc).

She mentioned that it would be extremely helpful to her to have an asynchronous way to go through training, or perhaps show proof of having worked through the materials in order to become trained. 

Currently, the instructor training selects in favor of individuals who have the supports in place to dedicate 2 full days to training. For some, this is simply not a feasible economic or personal situation. Perhaps these are not the individuals who "should" become instructors, but I'm inclined to think that the instructor community would benefit from having passionate, dedicated individuals who would otherwise become instructors, but cannot take 2 days off from work/teaching/personal schedule.

cc @kariljordan @serahrono - this is an inclusivity concern in the instructor community that I would like to bring up!

**Comment by karenword** [comment]
@angela-li thank you for raising this issue! As it happens, we are considering options for training on non-consecutive days. This topic is currently being explored by @elizabethwilliams8 in the context of membership. We will base further planning on her conclusions, but this feedback -- which also applies to the Open training pool -- is also instructive.

**Comment by elizabethwilliams8** [comment]
@angela-li Thank you for your thought about this! We have just sent out our survey to member organisations where this question is included, but I will come back to this issue with what we find!

**Comment by karenword** [comment]
4-half-day training events have now become a standard part of our offerings, thanks in part to comments like these. Closing with thanks!
